/** Design notes shown behind the "Read the design notes" affordance. */
export const README_TEXT = `Unself is a six-and-a-half-minute, drug-free journey in which you watch your own self peel away from you. It is stateful, not a loop: a single autonomous dissociation parameter D climbs from zero to a peak and back down over the whole run, and everything you see and hear is derived from it — so minute six does not look or sound like minute one.

It moves through five phases. EMBODIED: a single luminous point-cloud figure that mirrors your tilt exactly — warm, present, one self. DEPERSONALIZATION: a delayed ghost-self peels off, a ring-buffer replaying your figure a growing delay behind (about 0.4 up to 3 seconds), brightening toward parity until you cannot tell which one is you. DEREALIZATION: the field drains toward grey, the figure flattens into a cardboard cutout behind a faint sheen of glass — unreal. DISSOLUTION, the peak: the figure disperses into drifting motes, boundaries melt into a soft centre-out glow, and time slows hard. RETURN: the motes re-coalesce, the ghost catches up and re-merges, colour comes back, a soft landing — never abrupt.

The engine is the research payload. Dissociation, in the cortical model, is thalamocortical DISCONNECTION plus a breakdown of sensory gating plus subjective TIME DILATION, and each is a line of code. Disconnection is audio-visual DESYNC: as D rises, the audio envelope increasingly lags the visual motion, up to about 600 ms at the peak — the two streams the brain normally binds come apart, which is the felt core of dissociation. Time dilation is a global timeScale that shrinks as D rises, stretching every animation and every audio glide, then snapping back on return. The palette drain, the boundary melt, and the ghost delay all scale with D as well.

The sound is drones only — no struck or plucked events, no pitched lattice. Two sustained clusters are built on an irregular, non-harmonic ratio set so the harmony beats rather than resolves: a warm PRESENT "you", and a GHOST "you" that is the same cluster detuned about -30 cents, lowpassed toward cotton-wool, collapsed to mono and delayed — the sonic twin of the visual doppelgänger. A convolution-reverb void (a seeded synthetic impulse) opens toward the dissolution peak, with a lowpass that opens at the light moment. Master gain sits near 0.14 into a compressor, and the whole graph tears down on exit.

Input is tilt only — DeviceOrientationEvent beta and gamma, the first reading taken as your resting baseline. No pointer, no mouse, no touch, no microphone. If there is no motion sensor, or no reading arrives within about 1.5 seconds, a seeded auto-drive (mulberry32 keyed to 0x2094 plus performance.now) gently wanders the tilt so the entire journey self-demos with zero sensor and zero interaction; a small chip shows whether the source is tilt or auto. Your tilt modulates D slightly — a little felt agency — but never resets the autonomous clock.

Safety is non-negotiable: no strobe, no full-screen flicker, only slow luminance drift; prefers-reduced-motion softens the mote wander and the drift; and Stop silences the audio and halts the animation the same frame.

This is a cycle-3 deepening of the lab's out-of-body line. 2080 Exo Vantage built the room — a single decoupling of sight from balance that breathed between embodied and out-of-body. 2094 folds in the banked echo-self doppelgänger mechanic and, crucially, replaces the breath with a genuine multi-phase TIMELINE that evolves and does not return you to where you started until it chooses to. The honest next step: the phase transitions are currently time-gated on a fixed clock; a cycle-4 version would let accumulated tilt engagement actually advance or hold the arc, so the journey's pace becomes yours.

References: Bera, Looger, Proekt & Cichon, "Cortical Mechanisms Contributing to Ketamine-Induced Dissociation," The Neuroscientist (2026), doi:10.1177/10738584251403946 — dissociation as thalamocortical disconnection, sensory-gating breakdown and time dilation. Lenggenhager, Tadi, Metzinger & Blanke, "Video ergo sum," Science (2007) — seeing your body from outside displaces the felt self. Blanke & Metzinger, "Full-body illusions and minimal phenomenal selfhood," Trends in Cognitive Sciences (2009). Cento, Gammeri et al. (2026) on the vestibular contribution to depersonalization and derealization.`;
