// ─────────────────────────────────────────────────────────────────────────────
// audio.ts — the "third ear" engine for 1165-third-ear.
//
//   The instrument is INSIDE the listener's cochlea. This module plays two loud,
//   close PURE tones (the "primaries" f1 & f2, both in the ~1–3 kHz sweet spot)
//   and MOVES them together so their DIFFERENCE, f2 − f1, traces a slow melody
//   in a low/mid register (~110–660 Hz). That difference tone ("Tartini tone",
//   Amacher's "third ear") is generated by the nonlinear mechanics of the ear —
//   NO oscillator ever plays it. The music lives entirely in the gap Δ.
//
//   Mapping (symmetric so the pair "moves together"):
//       f1 = carrier − Δ/2      f2 = carrier + Δ/2      difference = f2 − f1 = Δ
//   `carrier` is the mean of the pair — the user sweeps it up/down (both
//   primaries rise together) while Δ, the phantom melody, is unchanged. That is
//   the proof-of-phenomenon: the played pitch climbs, the phantom pitch does not.
//
//   Composition lives in Δ: a just-intonation major-pentatonic scale of
//   difference values, developed by a seeded (mulberry32) state machine over
//   minutes — statement → variation → rest → return, drifting by transposition
//   so minute 3 differs from minute 0. No Math.random / Date.now anywhere.
//
//   Safety: master path ends in a DynamicsCompressor (limiter) → conservative
//   master GainNode that only ever ramps (setTargetAtTime / linear). No hard
//   onsets; tones capped well under 4 kHz; stop() ramps down then tears down.
// ─────────────────────────────────────────────────────────────────────────────

/** Deterministic PRNG (mulberry32). Seeded from a constant so the whole
 *  composition is reproducible — never Math.random / Date.now. */
export function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export type PhaseName = "statement" | "variation" | "rest" | "return";

export type EngineState = {
  running: boolean;
  /** lower primary (Hz) — actually played */
  f1: number;
  /** upper primary (Hz) — actually played */
  f2: number;
  /** phantom difference tone (Hz) — only in the ear */
  delta: number;
  /** mean of the pair (Hz) — what the carrier control moves */
  carrierHz: number;
  phase: PhaseName;
  /** true when both primaries sound (phantom present); false = single tone */
  phantom: boolean;
};

type WebkitWindow = typeof window & { webkitAudioContext?: typeof AudioContext };

// ── tuning constants ─────────────────────────────────────────────────────────
const SEED = 0x7ea3ea2;

/** carrier (mean of the pair) range in Hz — kept inside the effective sweet
 *  spot for difference tones and safely under 4 kHz once Δ/2 + LFO are added. */
const CARRIER_MIN = 1200;
const CARRIER_MAX = 2700;

/** conservative master ceiling — starts at 0 and only ever ramps up. */
const MASTER_TARGET = 0.22;
const REST_GAIN = 0.42; // phrase gain during a "rest" phase
const RUN_GAIN = 1.0;

const BEAT_SEC = 1.05; // slow, meditative
const LOOKAHEAD = 0.12; // scheduler horizon (s)
const TICK_MS = 25; // scheduler poll

// just-intonation major pentatonic (one octave of ratios); extended across
// octaves by ratioForDegree(). Δ = BASE_DELTA × ratio.
const PENTA = [1, 9 / 8, 5 / 4, 3 / 2, 5 / 3];
const BASE_DELTA = 150; // Hz — degree 0
const DEG_MIN = 0;
const DEG_MAX = 9; // clamps Δ into ~150–500 Hz

function ratioForDegree(i: number): number {
  const o = Math.floor(i / 5);
  const w = ((i % 5) + 5) % 5;
  return PENTA[w] * Math.pow(2, o);
}

function clampDeg(d: number): number {
  return Math.max(DEG_MIN, Math.min(DEG_MAX, Math.round(d)));
}

type Note = { degree: number; beats: number; phase: PhaseName; rest: boolean };

// ── the seeded composer ──────────────────────────────────────────────────────
// Produces an endless stream of notes whose difference-tone degrees develop
// over minutes. All randomness comes from a single seeded generator.
class Composer {
  private rng = mulberry32(SEED);
  private transpose = 0;
  private queue: Note[] = [];
  private qIdx = 0;

  private pick<T>(arr: readonly T[]): T {
    return arr[Math.floor(this.rng() * arr.length)];
  }

  private buildMotif(): Note[] {
    const len = 4 + Math.floor(this.rng() * 3); // 4–6 notes
    const durs = [1, 1, 1.5, 2] as const;
    const notes: Note[] = [];
    let deg = this.pick([0, 2, 3] as const);
    for (let i = 0; i < len; i++) {
      notes.push({
        degree: deg,
        beats: this.pick(durs),
        phase: "statement",
        rest: false,
      });
      // mostly stepwise walk, occasional leap
      const step = this.rng() < 0.75 ? this.pick([-1, 1] as const) : this.pick([-2, 2, 3] as const);
      deg += step;
      if (deg < 0) deg += 2;
      if (deg > 6) deg -= 2;
    }
    return notes;
  }

  private vary(motif: Note[]): Note[] {
    let seq = motif.map((n) => ({ ...n, phase: "variation" as PhaseName }));
    if (this.rng() < 0.5) seq = seq.slice().reverse();
    return seq.map((n) => {
      const degree = this.rng() < 0.35 ? n.degree + this.pick([-1, 1] as const) : n.degree;
      const beats = this.rng() < 0.4 ? this.pick([1, 1.5, 2] as const) : n.beats;
      return { ...n, degree, beats };
    });
  }

  private transposed(motif: Note[], k: number, phase: PhaseName): Note[] {
    return motif.map((n) => ({ ...n, degree: n.degree + k, phase }));
  }

  private buildCycle(): void {
    const motif = this.buildMotif();
    const variation = this.vary(motif);
    const rest: Note[] = [{ degree: 0, beats: 4, phase: "rest", rest: true }];
    const lift = this.pick([-2, -1, 1, 2] as const);
    const ret = this.transposed(motif, lift, "return");
    this.queue = [
      ...this.transposed(motif, 0, "statement"),
      ...variation,
      ...rest,
      ...ret,
    ];
    this.qIdx = 0;
    // drift the whole piece so it is different minutes later
    this.transpose = Math.max(-2, Math.min(3, this.transpose + this.pick([-1, 0, 1] as const)));
  }

  next(): Note {
    if (this.qIdx >= this.queue.length) this.buildCycle();
    const n = this.queue[this.qIdx++];
    return { ...n, degree: clampDeg(n.degree + this.transpose) };
  }

  reset(): void {
    this.rng = mulberry32(SEED);
    this.transpose = 0;
    this.queue = [];
    this.qIdx = 0;
  }
}

// ── the audio engine ─────────────────────────────────────────────────────────
export class ThirdEarEngine {
  private ctx: AudioContext | null = null;
  private osc1: OscillatorNode | null = null;
  private osc2: OscillatorNode | null = null;
  private g1: GainNode | null = null;
  private g2: GainNode | null = null;
  private mixBus: GainNode | null = null;
  private phraseGain: GainNode | null = null;
  private comp: DynamicsCompressorNode | null = null;
  private master: GainNode | null = null;
  private lfo: OscillatorNode | null = null;
  private lfoGain: GainNode | null = null;

  private composer = new Composer();
  private timer: ReturnType<typeof setInterval> | null = null;
  private nextNoteTime = 0;
  private lastF1 = CARRIER_MIN;
  private lastF2 = CARRIER_MIN;

  private carrierNorm = 0.45; // 0..1
  private phantom = true;

  private state: EngineState = {
    running: false,
    f1: 0,
    f2: 0,
    delta: 0,
    carrierHz: this.carrierHz(),
    phase: "statement",
    phantom: true,
  };

  private carrierHz(): number {
    return CARRIER_MIN + (CARRIER_MAX - CARRIER_MIN) * this.carrierNorm;
  }

  /** True only if Web Audio exists in this environment. */
  static isSupported(): boolean {
    if (typeof window === "undefined") return false;
    return Boolean(window.AudioContext || (window as WebkitWindow).webkitAudioContext);
  }

  getState(): EngineState {
    return { ...this.state };
  }

  /** Build the graph and begin. MUST be called from a user gesture. */
  start(): void {
    if (this.ctx) return;
    const Ctx = window.AudioContext || (window as WebkitWindow).webkitAudioContext;
    if (!Ctx) throw new Error("Web Audio unavailable");
    const ctx = new Ctx();
    this.ctx = ctx;
    void ctx.resume();

    const now = ctx.currentTime;
    const carrier = this.carrierHz();

    // ── master safety chain: sum → phrase env → limiter → conservative master ──
    const master = ctx.createGain();
    master.gain.setValueAtTime(0.0001, now);
    master.connect(ctx.destination);

    const comp = ctx.createDynamicsCompressor();
    comp.threshold.setValueAtTime(-18, now);
    comp.knee.setValueAtTime(12, now);
    comp.ratio.setValueAtTime(12, now);
    comp.attack.setValueAtTime(0.003, now);
    comp.release.setValueAtTime(0.25, now);
    comp.connect(master);

    const phraseGain = ctx.createGain();
    phraseGain.gain.setValueAtTime(RUN_GAIN, now);
    phraseGain.connect(comp);

    const mixBus = ctx.createGain();
    mixBus.gain.setValueAtTime(0.5, now); // two tones sum
    mixBus.connect(phraseGain);

    // two pure primaries
    const g1 = ctx.createGain();
    const g2 = ctx.createGain();
    g1.gain.setValueAtTime(1, now);
    g2.gain.setValueAtTime(1, now);
    g1.connect(mixBus);
    g2.connect(mixBus);

    const osc1 = ctx.createOscillator();
    const osc2 = ctx.createOscillator();
    osc1.type = "sine";
    osc2.type = "sine";
    osc1.frequency.setValueAtTime(carrier, now);
    osc2.frequency.setValueAtTime(carrier, now);
    osc1.connect(g1);
    osc2.connect(g2);

    // gentle shared carrier glide — keeps the ear-tone vivid, preserves Δ
    // because it is summed identically into BOTH primaries' frequency params.
    const lfo = ctx.createOscillator();
    lfo.type = "sine";
    lfo.frequency.setValueAtTime(0.06, now);
    const lfoGain = ctx.createGain();
    lfoGain.gain.setValueAtTime(85, now); // ±85 Hz
    lfo.connect(lfoGain);
    lfoGain.connect(osc1.frequency);
    lfoGain.connect(osc2.frequency);

    osc1.start(now);
    osc2.start(now);
    lfo.start(now);

    // smooth master rise — never an instant onset on loud tones
    master.gain.setTargetAtTime(MASTER_TARGET, now, 0.9);

    this.ctx = ctx;
    this.osc1 = osc1;
    this.osc2 = osc2;
    this.g1 = g1;
    this.g2 = g2;
    this.mixBus = mixBus;
    this.phraseGain = phraseGain;
    this.comp = comp;
    this.master = master;
    this.lfo = lfo;
    this.lfoGain = lfoGain;

    this.lastF1 = carrier;
    this.lastF2 = carrier;
    this.composer.reset();
    this.applyPhantom(now);

    this.state.running = true;
    this.nextNoteTime = now + 0.15;
    this.timer = setInterval(this.scheduler, TICK_MS);
  }

  /** 0..1 carrier height. Both primaries ramp together; Δ (the melody) holds. */
  setCarrier(norm: number): void {
    this.carrierNorm = Math.max(0, Math.min(1, norm));
    const carrier = this.carrierHz();
    this.state.carrierHz = carrier;
    if (!this.ctx || !this.osc1 || !this.osc2) return;
    const now = this.ctx.currentTime;
    const delta = this.state.delta;
    const f1 = carrier - delta / 2;
    const f2 = carrier + delta / 2;
    // smooth, shared move — never a jump
    this.osc1.frequency.setTargetAtTime(f1, now, 0.08);
    this.osc2.frequency.setTargetAtTime(f2, now, 0.08);
    this.lastF1 = f1;
    this.lastF2 = f2;
    this.state.f1 = f1;
    this.state.f2 = f2;
  }

  /** true = both primaries (phantom present); false = mute upper → phantom gone. */
  setPhantom(on: boolean): void {
    this.phantom = on;
    this.state.phantom = on;
    if (this.ctx) this.applyPhantom(this.ctx.currentTime);
  }

  private applyPhantom(now: number): void {
    if (!this.g2) return;
    // muting one primary removes the nonlinear interaction → no difference tone
    this.g2.gain.setTargetAtTime(this.phantom ? 1 : 0, now, 0.05);
  }

  private scheduler = (): void => {
    if (!this.ctx) return;
    const horizon = this.ctx.currentTime + LOOKAHEAD;
    while (this.nextNoteTime < horizon) {
      this.scheduleNote(this.nextNoteTime);
    }
  };

  private scheduleNote(time: number): void {
    if (!this.ctx || !this.osc1 || !this.osc2 || !this.phraseGain) return;
    const note = this.composer.next();
    const delta = BASE_DELTA * ratioForDegree(note.degree);
    const carrier = this.carrierHz();
    const f1 = carrier - delta / 2;
    const f2 = carrier + delta / 2;
    const dur = note.beats * BEAT_SEC;
    const glide = Math.min(0.4, dur * 0.45);

    // legato frequency glide on both primaries — anchored, then ramped
    this.osc1.frequency.setValueAtTime(this.lastF1, time);
    this.osc2.frequency.setValueAtTime(this.lastF2, time);
    this.osc1.frequency.linearRampToValueAtTime(f1, time + glide);
    this.osc2.frequency.linearRampToValueAtTime(f2, time + glide);

    // phrase envelope: rest phases breathe softer (never a hard gate)
    const target = note.rest ? REST_GAIN : RUN_GAIN;
    this.phraseGain.gain.setTargetAtTime(target, time, 0.12);

    this.lastF1 = f1;
    this.lastF2 = f2;
    this.nextNoteTime = time + dur;

    // reflect what is (about to be) sounding for the diagram
    this.state.delta = delta;
    this.state.f1 = f1;
    this.state.f2 = f2;
    this.state.carrierHz = carrier;
    this.state.phase = note.phase;
  }

  /** Ramp everything down, then fully tear down the graph and context. */
  stop(): void {
    const ctx = this.ctx;
    if (!ctx) return;
    this.state.running = false;
    if (this.timer !== null) {
      clearInterval(this.timer);
      this.timer = null;
    }
    const now = ctx.currentTime;
    if (this.master) this.master.gain.setTargetAtTime(0.0001, now, 0.18);

    const osc1 = this.osc1;
    const osc2 = this.osc2;
    const lfo = this.lfo;
    // let the fade breathe, then hard-stop + disconnect + close
    window.setTimeout(() => {
      try {
        osc1?.stop();
        osc2?.stop();
        lfo?.stop();
      } catch {
        /* already stopped */
      }
      for (const n of [
        this.osc1,
        this.osc2,
        this.lfo,
        this.lfoGain,
        this.g1,
        this.g2,
        this.mixBus,
        this.phraseGain,
        this.comp,
        this.master,
      ]) {
        try {
          n?.disconnect();
        } catch {
          /* ignore */
        }
      }
      if (this.ctx && this.ctx.state !== "closed") {
        this.ctx.close().catch(() => {
          /* ignore */
        });
      }
      this.ctx = null;
      this.osc1 = null;
      this.osc2 = null;
      this.lfo = null;
      this.lfoGain = null;
      this.g1 = null;
      this.g2 = null;
      this.mixBus = null;
      this.phraseGain = null;
      this.comp = null;
      this.master = null;
    }, 320);

    this.state.f1 = 0;
    this.state.f2 = 0;
    this.state.delta = 0;
  }
}

export const CARRIER_RANGE = { min: CARRIER_MIN, max: CARRIER_MAX };
