/**
 * 7480 — Einstein (Spectre monotile) substitution system.
 *
 * A faithful TypeScript port of Craig S. Kaplan's compact Spectre substitution
 * system (https://cs.uwaterloo.ca/~csk/spectre/), which realises the 2023
 * aperiodic monotile of Smith, Myers, Kaplan & Goodman-Strauss.
 *
 * The tiling is generated by SUBSTITUTION / INFLATION — nine metatiles
 * (Gamma, Delta, Theta, Lambda, Xi, Pi, Sigma, Phi, Psi) each with a fixed
 * rule that replaces it with eight children under fixed affine transforms.
 * Inflate N times, then walk the tree to emit the final Spectre (Tile(1,1))
 * polygons. This is the real aperiodic monotile, not a random or hand-placed
 * layout: no periodic tiling of the plane by this shape is possible.
 */

// ── Affine transforms (2x3 row-major: [a b c d e f]) ─────────────────────────
// A point (x,y) maps to (a*x + b*y + c, d*x + e*y + f).
export type Mat = readonly [number, number, number, number, number, number];
export interface Pt {
  x: number;
  y: number;
}

export const IDENT: Mat = [1, 0, 0, 0, 1, 0];

export function mul(A: Mat, B: Mat): Mat {
  return [
    A[0] * B[0] + A[1] * B[3],
    A[0] * B[1] + A[1] * B[4],
    A[0] * B[2] + A[1] * B[5] + A[2],
    A[3] * B[0] + A[4] * B[3],
    A[3] * B[1] + A[4] * B[4],
    A[3] * B[2] + A[4] * B[5] + A[5],
  ];
}

function trot(ang: number): Mat {
  const c = Math.cos(ang);
  const s = Math.sin(ang);
  return [c, -s, 0, s, c, 0];
}

function ttrans(tx: number, ty: number): Mat {
  return [1, 0, tx, 0, 1, ty];
}

export function transPt(M: Mat, p: Pt): Pt {
  return { x: M[0] * p.x + M[1] * p.y + M[2], y: M[3] * p.x + M[4] * p.y + M[5] };
}

function transTo(p: Pt, q: Pt): Mat {
  return ttrans(q.x - p.x, q.y - p.y);
}

function radians(deg: number): number {
  return (deg * Math.PI) / 180;
}

// ── Tile tree ────────────────────────────────────────────────────────────────
interface Child {
  transform: Mat;
  child: TileNode;
}
interface TileNode {
  kind: "leaf" | "node";
  label: string;
  points?: Pt[]; // leaf only: the 14 Spectre outline points
  children?: Child[]; // node only
  quad: Pt[]; // four "key" points used to align substitutions
}

type System = Record<string, TileNode>;

const METATILES = [
  "Gamma",
  "Delta",
  "Theta",
  "Lambda",
  "Xi",
  "Pi",
  "Sigma",
  "Phi",
  "Psi",
] as const;

// ── Base level: the Spectre outline (Tile(1,1), 14 equilateral edges) ─────────
function buildSpectreBase(): System {
  const spectre: Pt[] = [
    { x: 0, y: 0 },
    { x: 1.0, y: 0.0 },
    { x: 1.5, y: -0.8660254037844386 },
    { x: 2.366025403784439, y: -0.36602540378443865 },
    { x: 2.366025403784439, y: 0.6339745962155614 },
    { x: 3.366025403784439, y: 0.6339745962155614 },
    { x: 3.866025403784439, y: 1.5 },
    { x: 3.0, y: 2.0 },
    { x: 2.133974596215561, y: 1.5 },
    { x: 1.6339745962155614, y: 2.3660254037844393 },
    { x: 0.6339745962155614, y: 2.3660254037844393 },
    { x: -0.3660254037844386, y: 2.3660254037844393 },
    { x: -0.866025403784439, y: 1.5 },
    { x: 0.0, y: 1.0 },
  ];
  const quad: Pt[] = [spectre[3], spectre[5], spectre[7], spectre[11]];

  const ret: System = {};
  for (const lab of ["Delta", "Theta", "Lambda", "Xi", "Pi", "Sigma", "Phi", "Psi"]) {
    ret[lab] = { kind: "leaf", label: lab, points: spectre, quad };
  }

  // Gamma is the "mystic": a bonded pair of two Spectres.
  const gamma1: TileNode = { kind: "leaf", label: "Gamma1", points: spectre, quad };
  const gamma2: TileNode = { kind: "leaf", label: "Gamma2", points: spectre, quad };
  ret["Gamma"] = {
    kind: "node",
    label: "Gamma",
    quad,
    children: [
      { transform: IDENT, child: gamma1 },
      {
        transform: mul(ttrans(spectre[8].x, spectre[8].y), trot(Math.PI / 6)),
        child: gamma2,
      },
    ],
  };

  return ret;
}

// ── One inflation step ───────────────────────────────────────────────────────
function buildSupertiles(sys: System): System {
  const quad = sys["Delta"].quad;
  const R: Mat = [-1, 0, 0, 0, 1, 0]; // reflection

  const t_rules: [number, number, number][] = [
    [60, 3, 1],
    [0, 2, 0],
    [60, 3, 1],
    [60, 3, 1],
    [0, 2, 0],
    [60, 3, 1],
    [-120, 3, 3],
  ];

  const Ts: Mat[] = [IDENT];
  let total_ang = 0;
  let rot: Mat = IDENT;
  const tquad = [...quad];
  for (const [ang, from, to] of t_rules) {
    total_ang += ang;
    if (ang !== 0) {
      rot = trot(radians(total_ang));
      for (let i = 0; i < 4; ++i) {
        tquad[i] = transPt(rot, quad[i]);
      }
    }
    const ttt = transTo(tquad[to], transPt(Ts[Ts.length - 1], quad[from]));
    Ts.push(mul(ttt, rot));
  }

  for (let idx = 0; idx < Ts.length; ++idx) {
    Ts[idx] = mul(R, Ts[idx]);
  }

  const super_rules: Record<string, string[]> = {
    Gamma: ["Pi", "Delta", "null", "Theta", "Sigma", "Xi", "Phi", "Gamma"],
    Delta: ["Xi", "Delta", "Xi", "Phi", "Sigma", "Pi", "Phi", "Gamma"],
    Theta: ["Psi", "Delta", "Pi", "Phi", "Sigma", "Pi", "Phi", "Gamma"],
    Lambda: ["Psi", "Delta", "Xi", "Phi", "Sigma", "Pi", "Phi", "Gamma"],
    Xi: ["Psi", "Delta", "Pi", "Phi", "Sigma", "Psi", "Phi", "Gamma"],
    Pi: ["Psi", "Delta", "Xi", "Phi", "Sigma", "Psi", "Phi", "Gamma"],
    Sigma: ["Xi", "Delta", "Xi", "Phi", "Sigma", "Pi", "Lambda", "Gamma"],
    Phi: ["Psi", "Delta", "Psi", "Phi", "Sigma", "Pi", "Phi", "Gamma"],
    Psi: ["Psi", "Delta", "Psi", "Phi", "Sigma", "Psi", "Phi", "Gamma"],
  };

  const super_quad: Pt[] = [
    transPt(Ts[6], quad[2]),
    transPt(Ts[5], quad[1]),
    transPt(Ts[3], quad[2]),
    transPt(Ts[0], quad[1]),
  ];

  const ret: System = {};
  for (const lab of METATILES) {
    const subs = super_rules[lab];
    const children: Child[] = [];
    for (let idx = 0; idx < 8; ++idx) {
      if (subs[idx] === "null") continue;
      children.push({ transform: Ts[idx], child: sys[subs[idx]] });
    }
    ret[lab] = { kind: "node", label: lab, quad: super_quad, children };
  }
  return ret;
}

// ── Final emitted tile ───────────────────────────────────────────────────────
export interface FinalTile {
  points: Pt[]; // 14 transformed Spectre outline points
  d: string; // SVG path data
  label: string; // leaf metatile label (Delta, Theta, ... / Gamma1, Gamma2)
  orient: number; // orientation index 0..11 (30-degree steps)
  reflected: boolean; // chirality (which mirror form)
  cx: number;
  cy: number; // centroid
}

function emitLeaf(node: TileNode, transform: Mat): FinalTile {
  const pts = node.points!.map((p) => transPt(transform, p));
  let d = "M";
  let sx = 0;
  let sy = 0;
  for (let i = 0; i < pts.length; i++) {
    const p = pts[i];
    d += (i === 0 ? "" : "L") + p.x.toFixed(3) + " " + p.y.toFixed(3);
    sx += p.x;
    sy += p.y;
  }
  d += "Z";

  const det = transform[0] * transform[4] - transform[1] * transform[3];
  const reflected = det < 0;
  const ang = (Math.atan2(transform[3], transform[0]) * 180) / Math.PI;
  let orient = Math.round(ang / 30);
  orient = ((orient % 12) + 12) % 12;

  return {
    points: pts,
    d,
    label: node.label,
    orient,
    reflected,
    cx: sx / pts.length,
    cy: sy / pts.length,
  };
}

function forEachTile(node: TileNode, transform: Mat, out: FinalTile[]): void {
  if (node.kind === "leaf") {
    out.push(emitLeaf(node, transform));
    return;
  }
  const kids = node.children!;
  for (let i = 0; i < kids.length; i++) {
    forEachTile(kids[i].child, mul(transform, kids[i].transform), out);
  }
}

export interface TilingResult {
  tiles: FinalTile[];
  bounds: { minX: number; minY: number; maxX: number; maxY: number };
}

/**
 * Build the aperiodic Spectre tiling by inflating `depth` times, then walking
 * the substitution tree. `rootLabel` picks which top-level supertile to draw.
 * Returns tiles in substitution (depth-first) order — the order the melody
 * playhead will visit them.
 */
export function buildTiling(depth: number, rootLabel = "Delta"): TilingResult {
  let sys = buildSpectreBase();
  for (let i = 0; i < depth; i++) {
    sys = buildSupertiles(sys);
  }
  const tiles: FinalTile[] = [];
  forEachTile(sys[rootLabel], IDENT, tiles);

  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;
  for (const t of tiles) {
    for (const p of t.points) {
      if (p.x < minX) minX = p.x;
      if (p.y < minY) minY = p.y;
      if (p.x > maxX) maxX = p.x;
      if (p.y > maxY) maxY = p.y;
    }
  }
  return { tiles, bounds: { minX, minY, maxX, maxY } };
}

/**
 * Reorder tiles for a smoother spatial sweep (spiral from centroid) while
 * keeping the substitution order available separately. Used by the "sweep"
 * traversal mode. This does NOT change the tiling — only the visiting order.
 */
export function spiralOrder(tiles: FinalTile[]): FinalTile[] {
  let cx = 0;
  let cy = 0;
  for (const t of tiles) {
    cx += t.cx;
    cy += t.cy;
  }
  cx /= tiles.length;
  cy /= tiles.length;
  return [...tiles].sort((a, b) => {
    const ra = Math.hypot(a.cx - cx, a.cy - cy);
    const rb = Math.hypot(b.cx - cx, b.cy - cy);
    if (Math.abs(ra - rb) > 0.5) return ra - rb;
    const aa = Math.atan2(a.cy - cy, a.cx - cx);
    const ab = Math.atan2(b.cy - cy, b.cx - cx);
    return aa - ab;
  });
}
