import { U, VISIONARY_PALETTE, ROT2 } from "./shared";

export const FRAG =
  U +
  VISIONARY_PALETTE +
  ROT2 +
  `
// ---- Quasicrystal / Penrose tiling ----
// A quasicrystal pattern with 5-fold symmetry is generated by summing
// 5 plane waves with angles k*2*pi/5. The level sets of this sum
// create an aperiodic Penrose-like tiling.

float quasicrystal(vec2 p, float freq) {
  float val = 0.0;
  for (int k = 0; k < 5; k++) {
    float angle = float(k) * 1.25664; // k * 2*pi/5
    vec2 dir = vec2(cos(angle), sin(angle));
    val += cos(dot(p, dir) * freq);
  }
  return val; // range approximately -5..5
}

// Second quasicrystal with slightly different phase — creates moiré-like depth
float quasicrystal2(vec2 p, float freq, float phase) {
  float val = 0.0;
  for (int k = 0; k < 5; k++) {
    float angle = float(k) * 1.25664 + phase;
    vec2 dir = vec2(cos(angle), sin(angle));
    val += cos(dot(p, dir) * freq);
  }
  return val;
}

void main() {
  vec2 uv = (gl_FragCoord.xy - 0.5 * u_resolution) / min(u_resolution.x, u_resolution.y);
  float t = u_time * 0.1;
  float paletteShift = u_amplitude * 0.28;

  // Infinite zoom: cycle through scale logarithmically so it never bottoms out
  float zoomBase  = 4.5;
  float zoomCycle = mod(t * 0.4, log(1.61803)); // one phi period
  float zoom      = zoomBase * exp(zoomCycle);

  // Slow rotation for infinite feel
  float rotAngle = t * 0.05 + u_mid * 0.05;
  vec2 uvR = rot2(rotAngle) * uv;

  // Scaled coordinates
  vec2 p = uvR * zoom;

  // ---- Layer 1: primary quasicrystal ----
  float freq1 = 1.0 + u_bass * 0.15;
  float qc1   = quasicrystal(p, freq1);

  // ---- Layer 2: offset quasicrystal — slightly rotated/scaled for depth ----
  float freq2    = freq1 * 1.61803; // phi times larger frequency = sub-tiling
  float phase2   = t * 0.5;
  float qc2      = quasicrystal2(p, freq2, phase2);

  // ---- Layer 3: even finer scale ----
  float freq3 = freq1 * 1.61803 * 1.61803;
  float phase3 = t * 0.8 + 0.5;
  float qc3   = quasicrystal(p * 1.61803, freq3 * 0.7);

  // ---- Edge detection: near zero-crossings of qc = tile boundaries ----
  float edge1  = 1.0 - smoothstep(0.0, 0.9 + u_treble * 0.3, abs(qc1));
  float edge2  = 1.0 - smoothstep(0.0, 0.7 + u_treble * 0.2, abs(qc2));
  float edge3  = 1.0 - smoothstep(0.0, 0.5, abs(qc3));

  // ---- Tile interior shading ----
  // Normalize qc to 0..1
  float tileVal1 = qc1 / 5.0 * 0.5 + 0.5;
  float tileVal2 = qc2 / 5.0 * 0.5 + 0.5;
  float tileVal3 = qc3 / 5.0 * 0.5 + 0.5;

  // Palette 1: primary tiles — cool spectral
  vec3 col1 = palette(
    tileVal1 + t * 0.2 + paletteShift,
    vec3(0.5, 0.5, 0.5),
    vec3(0.5, 0.4, 0.6),
    vec3(0.8, 1.0, 0.4),
    vec3(0.0, 0.15, 0.4)
  );
  // Palette 2: secondary tiles — warm
  vec3 col2 = palette(
    tileVal2 + t * 0.15 + paletteShift + 0.5,
    vec3(0.5, 0.4, 0.3),
    vec3(0.5, 0.35, 0.2),
    vec3(1.0, 0.7, 0.3),
    vec3(0.05, 0.1, 0.0)
  );
  // Palette 3: edges — bright lines
  vec3 edgeCol = palette(
    tileVal1 * 2.0 + t * 0.35 + paletteShift + 0.25,
    vec3(0.6, 0.6, 0.6),
    vec3(0.5, 0.5, 0.5),
    vec3(0.5, 0.9, 1.0),
    vec3(0.0, 0.1, 0.3)
  );

  vec3 color = vec3(0.0);

  // Base tile fill: very dim interior coloring
  color += col1 * tileVal1 * 0.04;
  color += col2 * tileVal2 * 0.03;

  // Tile boundaries (edges)
  color += edgeCol * edge1 * 0.7;
  color += edgeCol * edge2 * 0.4;
  color += edgeCol * edge3 * 0.2;

  // 5-fold symmetry lines: five directions' zero-crossings highlighted
  float symLine = 0.0;
  for (int k = 0; k < 5; k++) {
    float angle = float(k) * 1.25664 + rotAngle;
    vec2 dir = vec2(cos(angle), sin(angle));
    float proj = dot(uvR, dir) * (zoom * 0.5 + u_bass * 0.5);
    float stripe = abs(fract(proj) - 0.5);
    symLine = max(symLine, smoothstep(0.04, 0.0, stripe));
  }
  vec3 symCol = palette(
    t * 0.3 + paletteShift + 0.1,
    vec3(0.5, 0.4, 0.5),
    vec3(0.4, 0.3, 0.5),
    vec3(0.7, 0.8, 1.0),
    vec3(0.1, 0.05, 0.3)
  );
  color += symCol * symLine * 0.3;

  // Audio reactivity: bass brightens all edges
  color *= (1.0 + u_bass * 0.4);

  // Treble: sparkle at triple edge intersections
  float tripleEdge = edge1 * edge2 * u_treble;
  color += vec3(1.2, 1.15, 1.1) * tripleEdge * 0.5;

  // Depth fog: vague sense of layers receding to center
  float centerFog = smoothstep(0.9, 0.0, length(uv));
  vec3 fogCol = palette(
    t * 0.15 + paletteShift + 0.6,
    vec3(0.05, 0.04, 0.08),
    vec3(0.05, 0.04, 0.1),
    vec3(0.4, 0.6, 1.0),
    vec3(0.2, 0.1, 0.35)
  );
  color += fogCol * centerFog * 0.05;

  // Vignette
  float vign = 1.0 - smoothstep(0.5, 1.5, length(uv));
  color *= vign;

  gl_FragColor = vec4(color, 1.0);
}
`;
