/** Design notes shown behind the "Read the design notes" affordance. */
export const README_TEXT = `Exo Vantage asks one question: what if you could watch yourself from OUTSIDE your own body — a drug-free out-of-body experience induced by decoupling what you SEE from what your inner ear (the phone's motion sensor) reports?

You start embodied. The camera sits inside a luminous standing presence — a humanoid drawn only as a glowing point-cloud in a spare floor-and-fog room — gazing out through its eyes. Tilt the phone and the felt (vestibular) signal from the motion sensor drifts out of register with the lagging visual one. That MISMATCH accumulates, and as it does the camera eases out of the figure's head and floats up-and-behind to a third-person vantage: you watch "your own" body from above and outside. Hold still and the mismatch relaxes, and you sink back into the body. The piece breathes between embodied and out-of-body.

The sound splits the same way. A just-intonation drone bed plus sparse sustained tones is heard twice: DRY (clear, present, lightly stereo — your body's sound from inside) and DETACHED (a duplicate of itself, detuned about -28 cents, lowpass-filtered toward cotton-wool / underwater, given a short slap-delay, and collapsed to mono). As you detach, an equal-power crossfade moves the mix from dry toward that detached recording — the documented depersonalization percept, where everything sounds unreal, muffled, like a recording of something happening to someone else. Settle back and it returns to clear and present.

The first device reading calibrates a resting baseline, so however you comfortably hold the phone becomes "level". No motion sensor? Arrow keys nudge the tilt, and a seeded auto-drift ghost is always slowly wandering it AND pumping the mismatch — so the whole detachment effect is visible and audible with zero sensor and zero input (a phone reviewer who won't tilt still sees the body come loose). On iOS the Begin button requests motion permission; if it is denied or unavailable, the piece falls back to keys plus the ghost with an on-brand note, never a dead screen.

Safety: no strobe. Any luminance change is a slow (<1 Hz), high-floor breath routed through the shared SafeFlicker engine, and prefers-reduced-motion freezes the autonomous drift and softens the breath. The palette is deliberately drained and derealized — desaturated bone-grey with a faint sickly green-amber tint that deepens as you leave the body — unreal, not pretty.

References: the out-of-body experience arises from a failure to integrate visual, vestibular, and somatosensory signals — Cento, Gammeri et al., "The role of the vestibular system in depersonalization and derealization" (J. Vestibular Research, 2026); and the classic full-body illusion of Lenggenhager, Tadi, Metzinger & Blanke, "Video ergo sum" (Science, 2007), where seeing your body from outside displaces the felt self. Exo Vantage deliberately creates that same visual–vestibular mismatch to induce the split.`;
