// Design-notes prose for the in-app modal. Kept as a plain string so the page
// and the README.md tell one story.

export const README_TEXT = `Conductor Well asks one question: what if Karel could conduct his own recording with a real conductor's BEAT — circling a baton to set the tempo — so his piano rushes and holds to the shape of his hand, its pitch never changing?

The recording is his orchestra. Your circling gesture is the beat. Press anywhere in the well and CIRCLE the pointer like a conductor tracing a beat pattern. The ANGULAR VELOCITY of your orbit is the conducted tempo: circle faster and the music rushes; slow the orbit and it broadens; STOP with the baton held and the sound freezes into a shimmering sustain — a chord held to eternity, pitch intact; reverse the direction of the circle and the music plays backward. How far your hand sits from the center of the well is the DYNAMICS: orbit wide for forte, tight for piano. This is beating time, not scrubbing a bar.

The magic — rushing and holding without the pitch sliding up and down like a tape machine — is real-time pitch-preserving granular time-stretch, done with synchronous overlap-add. A read-head walks through his recording. Every ~45 ms of OUTPUT we emit one short grain — a ~110 ms slice of his audio played at speed 1, so its pitch is exactly his — through its own raised-cosine (Hann) envelope, and the overlapping grains sum back into continuous sound. The trick is that the read-head advances at the CONDUCTED rate, not real time: at rate 1 it tracks the recording; at rate 0 it re-triggers the same slice forever, a frozen sustain (with a few milliseconds of read jitter so it shimmers instead of buzzing); at negative rates it walks backward. Decoupling the read-head's speed from the constant grain-emission rate is what lets time stretch while pitch stays nailed to his hand.

The output is a 3D well seen in perspective. His real note-roll — from the published analysis, MIDI pitch and velocity per note — streams as motes pouring through the glowing baton ring INTO DEPTH; the flow speed into the receding dark IS the conducted tempo, so the whole field rushes and stalls with your orbit. The baton is the bright orbit ring at the mouth of the well, spinning to your beat, widening with your dynamics. Everything sits in a cool concert-hall-at-night palette — near-black under a violet ramp. If a track has no published note-roll the motes take their pitch and brightness from the live spectrum instead; before you grab the baton, a gentle auto-beat conducts the well on its own so it is never silent.

NAMED REFERENCE. The beat-conducting idea is ported from "Real-Time Control of a Virtual Orchestra by Recognition of Conducting Gestures" (arXiv:2604.27957, April 2026) — a 180-degree dome installation where visitors conduct pre-recorded orchestra audio by tempo and dynamics gestures. Here that idea is turned on Karel's OWN recording: his piano is the orchestra, his circling hand is the baton. The time-stretch engine sits in the granular overlap-add lineage — PhaVoRIT and Karrer, Lee and Borchers' 2006 real-time audio time-stretching for exactly this "conduct a recording" problem.

PLAY. Press and circle to conduct. Faster orbit rushes, stop holds, reverse rewinds; wide is forte, tight is piano. Pick any track from his verified catalog. Let go and the well holds your last breath, then the auto-beat takes over.`;
