// Design-notes prose for the in-app modal. Kept as a plain string so the page
// and the README.md tell one story.

export const README_TEXT = `Strike Temple asks one question: what if you could play a duet with Karel — striking bells and bowls that are always tuned to whatever chord his recording is playing right now?

His real piano recording plays underneath. On screen sits a small ring of touchable objects — bells, singing bowls and metal rods. Each one is a physically-modeled MODAL resonator: a strike fires six-to-ten decaying sine partials at fundamental × modal-ratio, and the ring you hear is those modes' own exponential decay. Bright high modes fade first, exactly like real struck metal. Nothing is a sample.

The trick is that the objects retune themselves in real time to HIS harmony. The page walks the recording's chord track against the playhead; when the current chord changes, it re-voices the ring — each object is handed a chord tone, spread low-to-high across the register — and the objects glide to their new pitch and glow to show it. So whenever you tap or drag one, it rings in his key, over his playing. You improvise a modal-percussion layer locked to his live chords: a duet with the recording.

MODAL SYNTHESIS. Each kind of object is a different partial set. A bell is strongly inharmonic (a hum tone a fifth below, then the tierce / quint / nominal cluster of a real cast bell: ratios 0.5, 1, 1.19, 1.71, 2, 2.74, 3, 3.76, 4.07). A singing bowl / handpan is near-harmonic (1, 2, 3, 4, 5, 6) with a slight per-partial detune so it shimmers and beats. A rod is a free–free metal bar with wide, fast-dying inharmonic partials (1, 2.76, 5.4, 8.93, 13.34). Per strike: a fast attack, an exponential decay whose time shortens for higher partials, and a brightness that rises with velocity — hit hard and the upper modes speak. Velocity comes from tap vs. drag speed. Everything is bounded — a per-strike peak, a partial count, a global oscillator budget — so the bank can never run away; safeMaster's limiter is the last line, not the first.

CHORD-FOLLOWING. The recording's analysis gives a time-sorted chord track. Each frame we find the chord under the playhead, parse it into a set of chord tones (triad quality, sus, 6 / 7 / maj7, and 9 / 11 / 13 extensions), and spread those tones across the ring as an ascending voicing. If a track has no published chord analysis, the objects instead follow the dominant peaks of the live spectrum (safeMaster's analyser) — a rough chord read from the sound itself. Before you press play, and if audio can't load at all, the temple cycles a gentle Am7–Dm7–G7–Cmaj7 loop so it is always playable in a key and never dead.

REFERENCES. The framing is arXiv:2508.01789, "Sonify Anything: Towards Context-Aware Sonic Interactions in AR" (Aug 2026) — objects given context-aware, physically-modeled modal voices; here the context is Karel's live harmony rather than a room's geometry. The synthesis sits in the modal / physical-modeling lineage: Jean-Marie Adrien's modal synthesis formulation, differentiable modal resonators (arXiv:2210.15306), and the CORDIS-ANIMA mass-interaction system from ACROE.

PLAY. Tap or drag across the ring — drag faster to strike harder. Number keys 1–7 strike the objects from your keyboard. Switch the struck material (bell / bowl / rod) to recolor the whole ring. After a while idle, the temple plays itself, striking within his current chord.`;
