// GENERATED by scripts/retheme-from-analysis.mjs — do not edit by hand.
// Per-phase beats + measured intensity for built-in journeys re-themed or
// re-arced from their v2 deep analysis (2026-10-05). Applied at module load
// in analysis-phase-bounds.ts. Mastered journeys are never listed here.
import type { JourneyPhase } from "./types";

export const BUILTIN_ANALYSIS_RETHEME: Record<string, Array<Partial<JourneyPhase> & { analysisRole?: string; gradeAs?: string }>> = {
  "the-ascent": [
    {
      "intensityMultiplier": 0.62,
      "aiPrompt": "DARK BACKGROUND — extreme close detail: dark rock at the crest of a ridge, fine mist flowing over its edge lit silver, barely lit, deep darkness all around it, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — extreme close detail: dark rock at the crest of a ridge, fine mist flowing over its edge lit silver, barely lit, deep darkness all around it, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "DARK BACKGROUND — looking down along a high bare ridge of dark rock at night, mist pooled on both sides, one thin seam of cold silver light along the crest in the lower right, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "DARK BACKGROUND — abstract: slow luminous rivers of cloud flowing over dark ridgelines, only the faintest light, wide negative space, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "dark",
      "gradeAs": "threshold"
    },
    {
      "intensityMultiplier": 0.9,
      "aiPrompt": "slow rivers of cloud flowing through a dark mountain saddle at night, their tops lit faint silver, the ridges rising above them, yearning and calm, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "slow rivers of cloud flowing through a dark mountain saddle at night, their tops lit faint silver, the ridges rising above them, yearning and calm, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "close study: dark rock at the crest of a ridge, fine mist flowing over its edge lit silver, the light gathering softly around it in deep surrounding dark, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "slow luminous rivers of cloud flowing over dark ridgelines, the light gathering and spreading outward, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "gathering",
      "gradeAs": "expansion"
    },
    {
      "intensityMultiplier": 1,
      "aiPrompt": "a long ridge of bare black rock at night seen from high above, an immense sea of moving cloud pouring over its saddle in a slow luminous cascade, cold silver and dusky violet light along every cloud edge, the brightest flow right of center, brooding and resolute, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "a long ridge of bare black rock at night seen from high above, an immense sea of moving cloud pouring over its saddle in a slow luminous cascade, cold silver and dusky violet light along every cloud edge, the brightest flow right of center, brooding and resolute, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "abstract at the largest scale: slow luminous rivers of cloud flowing over dark ridgelines, at full radiance, filling the frame with asymmetric weight, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro at the height of the light: dark rock at the crest of a ridge, fine mist flowing over its edge lit silver, glowing at full strength against deep surrounding dark, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "peak",
      "gradeAs": "transcendence"
    },
    {
      "intensityMultiplier": 0.96,
      "aiPrompt": "looking down at the cloud cascade pouring over the dark ridge, a warmer pale gold seam along its crest, light and shadow trading across the rock, poignant and suspended, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "looking down at the cloud cascade pouring over the dark ridge, a warmer pale gold seam along its crest, light and shadow trading across the rock, poignant and suspended, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "close: dark rock at the crest of a ridge, fine mist flowing over its edge lit silver, in broad steady calm light, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "slow luminous rivers of cloud flowing over dark ridgelines, the light broad, steady and calm, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "calm",
      "gradeAs": "illumination"
    },
    {
      "intensityMultiplier": 0.69,
      "aiPrompt": "looking straight down at the cloud sinking slowly back into the valleys between dark ridges, its surface softening to blue-grey, bittersweet and open, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "looking straight down at the cloud sinking slowly back into the valleys between dark ridges, its surface softening to blue-grey, bittersweet and open, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "close: dark rock at the crest of a ridge, fine mist flowing over its edge lit silver, in broad steady calm light, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "slow luminous rivers of cloud flowing over dark ridgelines, the light broad, steady and calm, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "calm",
      "gradeAs": "illumination"
    },
    {
      "intensityMultiplier": 0.37,
      "aiPrompt": "DARK BACKGROUND — the ridge alone in deep night, one faint silver seam fading along the crest, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — the ridge alone in deep night, one faint silver seam fading along the crest, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "DARK BACKGROUND — close: dark rock at the crest of a ridge, fine mist flowing over its edge lit silver, the last glow in near darkness, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "DARK BACKGROUND — slow luminous rivers of cloud flowing over dark ridgelines, almost entirely dark, one last trace of light, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "last",
      "gradeAs": "integration"
    }
  ],
  "cosmic-drift": [
    {
      "intensityMultiplier": 0.53,
      "aiPrompt": "DARK BACKGROUND — extreme close detail: the rough broken face of a jagged rock shard lit warm amber, fine dust lifting off it, seen close, barely lit, deep darkness all around it, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — extreme close detail: the rough broken face of a jagged rock shard lit warm amber, fine dust lifting off it, seen close, barely lit, deep darkness all around it, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "DARK BACKGROUND — a loose scatter of small jagged irregular rock shards drifting slowly through deep space in the lower left, their broken edges catching a faint warm amber light, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "DARK BACKGROUND — abstract: slow flowing currents of glowing golden dust in deep space, only the faintest light, wide negative space, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "dark",
      "gradeAs": "threshold"
    },
    {
      "intensityMultiplier": 0.87,
      "aiPrompt": "a gentle field of jagged irregular rock shards of many sizes drifting in slow procession, warm golden dust trailing between them, glowing softly, content, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "a gentle field of jagged irregular rock shards of many sizes drifting in slow procession, warm golden dust trailing between them, glowing softly, content, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "close study: the rough broken face of a jagged rock shard lit warm amber, fine dust lifting off it, seen close, the light gathering softly around it in deep surrounding dark, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "slow flowing currents of glowing golden dust in deep space, the light gathering and spreading outward, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "gathering",
      "gradeAs": "expansion"
    },
    {
      "intensityMultiplier": 0.43,
      "aiPrompt": "DARK BACKGROUND — wide empty dark space with a faint drift of warm golden dust across it, still, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — wide empty dark space with a faint drift of warm golden dust across it, still, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "close study: the rough broken face of a jagged rock shard lit warm amber, fine dust lifting off it, seen close, the light gathering softly around it in deep surrounding dark, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "slow flowing currents of glowing golden dust in deep space, the light gathering and spreading outward, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "gathering",
      "gradeAs": "expansion"
    },
    {
      "intensityMultiplier": 0.94,
      "aiPrompt": "jagged rock shards drifting through a vast cloud of warm golden dust, their broken faces lit amber and rose, fine particles glowing around them, uplifted, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "jagged rock shards drifting through a vast cloud of warm golden dust, their broken faces lit amber and rose, fine particles glowing around them, uplifted, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "close study: the rough broken face of a jagged rock shard lit warm amber, fine dust lifting off it, seen close, the light gathering softly around it in deep surrounding dark, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "slow flowing currents of glowing golden dust in deep space, the light gathering and spreading outward, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "gathering",
      "gradeAs": "expansion"
    },
    {
      "intensityMultiplier": 1,
      "aiPrompt": "an immense slow river of glowing golden dust flowing diagonally through deep space, countless small jagged rock shards carried within it lit warm gold, the densest glow left of center, yearning and tender, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "an immense slow river of glowing golden dust flowing diagonally through deep space, countless small jagged rock shards carried within it lit warm gold, the densest glow left of center, yearning and tender, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "abstract at the largest scale: slow flowing currents of glowing golden dust in deep space, at full radiance, filling the frame with asymmetric weight, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro at the height of the light: the rough broken face of a jagged rock shard lit warm amber, fine dust lifting off it, seen close, glowing at full strength against deep surrounding dark, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "peak",
      "gradeAs": "transcendence"
    },
    {
      "intensityMultiplier": 0.37,
      "aiPrompt": "DARK BACKGROUND — the last thin thread of golden dust and a few tiny jagged shards drifting away into deep dark, at peace, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — the last thin thread of golden dust and a few tiny jagged shards drifting away into deep dark, at peace, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "DARK BACKGROUND — close: the rough broken face of a jagged rock shard lit warm amber, fine dust lifting off it, seen close, the last glow in near darkness, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "DARK BACKGROUND — slow flowing currents of glowing golden dust in deep space, almost entirely dark, one last trace of light, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "last",
      "gradeAs": "integration"
    }
  ],
  "the-ascension": [
    {
      "intensityMultiplier": 0.75,
      "aiPrompt": "extreme macro in deep darkness — a single seed of golden light cracking open at closest range, thin filaments of warm luminance reaching upward out of the split like the first roots of a sunrise, fine gold dust lifting off the fracture, everything beyond the seed soft black with faint violet depth, the awakening small and low in the frame with vast dark above, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "extreme macro in deep darkness — a single seed of golden light cracking open at closest range, thin filaments of warm luminance reaching upward out of the split like the first roots of a sunrise, fine gold dust lifting off the fracture, everything beyond the seed soft black with faint violet depth, the awakening small and low in the frame with vast dark above, no text no signatures no watermarks no letters no writing",
        "microscopic — inside the seed's crack, a stair of light no wider than a vein climbing out of the dark kernel, gold dust rising through it in single grains, no text no signatures no watermarks no letters no writing",
        "wide — a dark plain under starless black, one small gold glow waking low in the frame, its light reaching upward in a thin first thread, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "breathe...",
        "feel the warmth...",
        "light is coming..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion"
    },
    {
      "intensityMultiplier": 0.97,
      "aiPrompt": "vertical ascent through layered golden strata — rivers of luminous particles streaming straight upward past translucent amber membranes stacked like sky above sky, each layer brighter than the one below, the viewpoint rising with the current, gold dust accelerating along the climb, warm light strengthening toward an unseen brilliance overhead, strong vertical energy with the densest stream off-center left, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "vertical ascent through layered golden strata — rivers of luminous particles streaming straight upward past translucent amber membranes stacked like sky above sky, each layer brighter than the one below, the viewpoint rising with the current, gold dust accelerating along the climb, warm light strengthening toward an unseen brilliance overhead, strong vertical energy with the densest stream off-center left, no text no signatures no watermarks no letters no writing",
        "interior — passing through one amber membrane, the layer parting around the viewpoint like warm mist, the next brighter sky already glowing through from above, no text no signatures no watermarks no letters no writing",
        "macro — one gold particle of the climb at closest range, its facets flashing the layered skies above and below as it spins in the updraft, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "rise...",
        "the light knows you...",
        "open..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion"
    },
    {
      "intensityMultiplier": 0.75,
      "aiPrompt": "aerial view from above a boundless sea of radiant golden cloud, the sunlit vapor rolling in slow immense swells to every edge of frame, deep wells opening in the cloud where shafts of white-gold light pour down into amber depth, the cloud tops burning brightest along one diagonal, serene altitude and total clarity, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "aerial view from above a boundless sea of radiant golden cloud, the sunlit vapor rolling in slow immense swells to every edge of frame, deep wells opening in the cloud where shafts of white-gold light pour down into amber depth, the cloud tops burning brightest along one diagonal, serene altitude and total clarity, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "intimate — skimming the radiant cloud-tops, gold vapor curling past the viewpoint, a deep well opening ahead with white-gold light standing in it like a pillar, no text no signatures no watermarks no letters no writing",
        "spirit-hint — over the cloud sea, the light half-gathers into a tall ancestral almost-presence of white-gold, translucent and featureless, standing on nothing, opening back into brightness, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "see how vast you are...",
        "every direction is warmth...",
        "stay in this light..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion"
    },
    {
      "intensityMultiplier": 1,
      "aiPrompt": "suspended weightless inside a monumental vault of pure golden light with no floor and no ground anywhere — colossal ribs of radiant gold geometry filling the entire frame in fibonacci curves above and below and to every side, white brilliance blazing at the convergence point off-center, luminous particles drifting through the vast interior like slow embers, only light architecture and glowing air in all directions, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "suspended weightless inside a monumental vault of pure golden light with no floor and no ground anywhere — colossal ribs of radiant gold geometry filling the entire frame in fibonacci curves above and below and to every side, white brilliance blazing at the convergence point off-center, luminous particles drifting through the vast interior like slow embers, only light architecture and glowing air in all directions, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro — one rib of the golden vault at closest range, light flowing inside it like sap in a branch of dawn, luminous motes drifting slowly past, no text no signatures no watermarks no letters no writing",
        "cosmic — the vault seen from outside, a lantern of gold geometry hanging alone in black space, its light spilling through its own ribs in long still rays, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "you are light...",
        "there is no boundary...",
        "this is home..."
      ],
      "analysisRole": "peak",
      "gradeAs": "transcendence"
    },
    {
      "intensityMultiplier": 0.66,
      "aiPrompt": "intimate slow descent through hanging veils of warm amber light, translucent petals of gold luminance planing gently downward past the viewpoint in long glide paths, each catching rose and violet iridescence as it turns, the veils parting softly ahead and closing above, warmth deepening from white-gold toward ember amber with the fall, tender unhurried motion, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "intimate slow descent through hanging veils of warm amber light, translucent petals of gold luminance planing gently downward past the viewpoint in long glide paths, each catching rose and violet iridescence as it turns, the veils parting softly ahead and closing above, warmth deepening from white-gold toward ember amber with the fall, tender unhurried motion, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro — one petal of gold light planing down at closest range, rose iridescence sweeping across its face as it turns over, no text no signatures no watermarks no letters no writing",
        "wide — the veils from below, layer after amber layer parting as the light descends toward a warm deep glow waiting at the bottom of the frame, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "gently now...",
        "the glow remains...",
        "carry the warmth..."
      ],
      "analysisRole": "lowering",
      "gradeAs": "return"
    },
    {
      "intensityMultiplier": 0.37,
      "aiPrompt": "macro stillness — one small warm amber glow resting in deep soft darkness, a faint halo of concentric golden rings breathing around it, a few last luminous motes settling toward it like sparks coming to rest, the light steady and kept, enormous quiet dark all around with the glow held low in the frame, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "macro stillness — one small warm amber glow resting in deep soft darkness, a faint halo of concentric golden rings breathing around it, a few last luminous motes settling toward it like sparks coming to rest, the light steady and kept, enormous quiet dark all around with the glow held low in the frame, no text no signatures no watermarks no letters no writing",
        "extreme macro — the glow's heart at closest range, a slow gold pulse inside soft dark, the last motes settling into it like dust after glory, no text no signatures no watermarks no letters no writing",
        "cosmic finale — the small warm glow seen from very far away, one gold point in vast dark, the whole ascent kept inside it, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "you are changed...",
        "the light lives in you now..."
      ],
      "analysisRole": "last",
      "gradeAs": "integration"
    }
  ],
  "mycelium-dream": [
    {
      "intensityMultiplier": 0.37,
      "aiPrompt": "enormous moss-covered boulder floating in deep dark space emerging from the lower right, the boulder photorealistic grey granite with thick green moss carpeting its top and sides, luminous mushrooms growing from crevices in the rock — their caps translucent and glowing soft cyan and warm gold bioluminescence, dangling roots and delicate ferns hanging from the boulder underside reaching into the void below, bioluminescent spores drifting upward from the mushroom gills in lazy spirals like tiny green-gold stars, the boulder detail anchored in one third of the frame with vast darkness and faint scattered spore-light above and left, macro texture visible on the moss and mushroom surfaces, asymmetric composition with visual weight low and right, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "night forest floor at ground level, a great mossy boulder among dark roots, luminous mushrooms glowing soft cyan and warm gold in its crevices, ferns arching over it in silhouette, bioluminescent spores spiraling up like tiny green-gold stars into the black canopy, asymmetric weight low and right, no text no signatures no watermarks no letters no writing",
        "extreme macro — one translucent mushroom cap at closest range, cyan light glowing through its flesh like a paper lantern, a single spore lifting off its gill edge lit gold, moss fronds soft and dark around the small light, no text no signatures no watermarks no letters no writing",
        "surreal — inside one glowing mushroom cap, a vaulted gill-cathedral of gold-green light, and through its translucent wall the dim shapes of the whole dark forest beyond, a chapel inside a lantern inside a wood, worlds nested three deep, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "the spores are waking...",
        "feel the soil...",
        "life begins small..."
      ],
      "analysisRole": "dark",
      "gradeAs": "threshold"
    },
    {
      "intensityMultiplier": 0.49,
      "aiPrompt": "DEEP BROWN-BLACK BACKGROUND — forest floor cross-section at cosmic scale floating in dark void, viewed from the side like a floating terrarium slice sweeping diagonally from upper left, visible layers of dark rich soil with embedded pale roots threading horizontally, fallen autumn leaves in various stages of decomposition compressed between soil strata, tiny translucent organisms and pale mycorrhizal threads glowing faint green-gold at the root interfaces, the cross-section edge raw and organic with soil crumbling away and fine earth particles dispersing into open dark void below, the top surface shows a miniature landscape of moss and tiny seedlings, infinite depth through layered translucent soil planes, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DEEP BROWN-BLACK BACKGROUND — beneath the forest floor, dark soil strata threaded with pale roots at every depth, mycorrhizal threads glowing faint green-gold where root meets root, small hollow chambers opening like dark rooms in the earth, the buried network pulsing softly through it all, no text no signatures no watermarks no letters no writing",
        "microscopic — inside the soil between two root hairs, a single glowing mycelial thread reaching across the dark gap grain by grain, green-gold light pulsing along it as the connection closes, earth crystals glinting around the meeting, no text no signatures no watermarks no letters no writing",
        "spirit-hint — in a root-hollow deep under the forest, the green-gold glow half-gathers into low ancient earthen almost-presences, translucent and featureless, made of spore-light, gathered around the brightest root the way ancestors keep a fire, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "it's growing...",
        "everything connects...",
        "feel the network..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion"
    },
    {
      "intensityMultiplier": 0.64,
      "aiPrompt": "DEEP SOIL-BLACK BACKGROUND — a single enormous mushroom cap at cosmic scale arranged along the left edge and lower third of vast dark void, viewed from below looking up at the luminous gill structure radiating outward in precise geometric patterns, the gills glowing warm gold and soft green bioluminescence, tiny ferns and curling moss growing on the cap surface visible at the edges, photorealistic water droplets hanging from the gill ridges catching and refracting the bioluminescent light into tiny prismatic spectra, fine spore particles drifting downward from the gills like luminous snow into dark void below, asymmetric leaving the upper right vast and open, quiet power in the contrast of organic intricacy against boundless darkness, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DEEP SOIL-BLACK BACKGROUND — a single enormous mushroom cap at cosmic scale from below, luminous gill structure radiating in precise geometry, warm gold and soft green bioluminescence, water droplets on the gill ridges refracting tiny prismatic spectra, spore particles drifting down like luminous snow, no text no signatures no watermarks no letters no writing",
        "macro — one water droplet hanging from a gill ridge at closest range, the whole radiating gill-cathedral curved inside it upside down, a prism-spark burning at its heart, no text no signatures no watermarks no letters no writing",
        "abstract — the gill geometry alone: radiating blades of gold-green light fanning from an unseen center across darkness, spore-snow drifting through the spokes, architecture grown rather than built, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "the garden knows you...",
        "every leaf is aware...",
        "this intelligence is ancient..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion"
    },
    {
      "intensityMultiplier": 0.78,
      "aiPrompt": "fallen log covered in thick moss and small plants floating in deep space arcing from lower left toward upper right, the log photorealistic with weathered bark and soft green moss texture, shelf fungi growing in tiers along its length glowing faint warm amber and pale green, tiny seedlings and unfurling fern fronds emerging from the decomposing bark, seeds and luminous spores trailing off from the log into generous dark negative space above and right like a comet tail of organic matter, the forms impossibly detailed even as they thin and dissolve into pure particle at the trailing edge, composition weighted to the lower half with cosmic darkness opening above, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "a fallen log at rest on the night forest floor, shelf fungi in glowing amber tiers along its mossy length, seedlings and fern fronds unfurling from the soft bark, luminous spores drifting up from it lit against the dark trunks beyond, no text no signatures no watermarks no letters no writing",
        "intimate — among the shelf fungi at close range, tiered amber lights stacked up the dark bark like lantern balconies, one new fern frond unrolling into their glow, no text no signatures no watermarks no letters no writing",
        "spirit-hint — above the old log, the rising spore-light half-gathers into a slow procession of small ancestral almost-presences, translucent and featureless, drifting up between the dark trunks like elders returning home, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "the forest settles...",
        "roots remember...",
        "return to soil..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion"
    },
    {
      "intensityMultiplier": 0.91,
      "aiPrompt": "cosmic-scale bioluminescent network sweeping across infinite brown-black void — millions of luminous green-gold points connected by hair-thin filaments forming a web-like structure that could be neurons or galaxies or mycorrhizal connections, the network dense and intricate in the upper-right third but dissolving into scattered individual points at its edges, warm amber pulses traveling along the filaments between nodes creating a sense of living communication, the spaces between filled with drifting spore-like particles of pale green light, composition fills the frame off-center with the densest cluster upper-right and filament bridges reaching across into generous darkness lower-left, no mushrooms no plants no landscape no figures, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic-scale bioluminescent network sweeping across infinite brown-black void, millions of green-gold points joined by hair-thin filaments like neurons or galaxies, amber pulses traveling between nodes, drifting spore-light filling the spaces, densest cluster upper-right with bridges reaching into generous darkness, no text no signatures no watermarks no letters no writing",
        "interior kinetic — flying along one filament inside the network, node-lights flaring past like stations, amber signal-pulses overtaking and racing ahead, branches curving away into deep green-black on every side, no text no signatures no watermarks no letters no writing",
        "aerial — the network spread across a dark ground filling the frame seen from very high above, green-gold veins netting the whole dark ground, slow pulses crossing wide fields of darkness, one region blazing awake, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "you are the network...",
        "all is one organism...",
        "breathe with the forest..."
      ],
      "analysisRole": "peak",
      "gradeAs": "transcendence"
    },
    {
      "intensityMultiplier": 0.74,
      "aiPrompt": "sparse scattered bioluminescent particles drifting across vast brown-black silence — some green-gold some pale amber — moving in barely perceptible spiral paths like the memory of a network dissolving, one faintly brighter point in the lower-left corner pulsing with gathered light as if all the network's energy has condensed to a single node, the faintest filament trails still connecting it to a few nearby motes before they fade to nothing, enormous open darkness everywhere, asymmetric and quiet — the last signal in an infinite dark, no mushrooms no plants no landscape no figures, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "sparse scattered bioluminescent particles drifting across vast brown-black silence, green-gold and pale amber motes in barely perceptible spirals, one brighter point pulsing with gathered light, the faintest filament trails fading around it, enormous open darkness, no text no signatures no watermarks no letters no writing",
        "extreme macro — the single bright node at closest range, a seed of condensed green-gold light with the memory of filaments still flickering faint at its rim, darkness pressing close and kind, no text no signatures no watermarks no letters no writing",
        "cosmic finale — the dark from very far away, one green-gold point alone in brown-black immensity, indistinguishable from a first star or a last spore, holding everything either way, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "one spore holds everything...",
        "you carry the forest..."
      ],
      "analysisRole": "calm",
      "gradeAs": "illumination"
    }
  ],
  "the-bloom": [
    {
      "intensityMultiplier": 0.45,
      "aiPrompt": "DARK BACKGROUND, enormous seed pod cracking open in the lower-right third of deep brown-black void, the pod shell rendered with photorealistic dark bark-like texture split along fibonacci spiral lines, but inside the pod instead of seeds there is a miniature world — tiny trees with green canopies, a winding stream of blue-silver water, clusters of wildflowers in white and gold, all contained within the pod shell like a terrarium, warm green-gold light spilling from the interior world into the surrounding darkness, fine spores and tiny flower petals ejecting from the opening along diagonal paths upward-left into vast dark space, the impossible nursery of an entire landscape inside a seed at cosmic scale, two-thirds of the frame open dark void above and left, asymmetric composition with the pod anchored low-right, no figures no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND, enormous seed pod cracking open in the lower-right third of deep brown-black void, the pod shell rendered with photorealistic dark bark-like texture split along fibonacci spiral lines, but inside the pod instead of seeds there is a miniature world — tiny trees with green canopies, a winding stream of blue-silver water, clusters of wildflowers in white and gold, all contained within the pod shell like a terrarium, warm green-gold light spilling from the interior world into the surrounding darkness, fine spores and tiny flower petals ejecting from the opening along diagonal paths upward-left into vast dark space, the impossible nursery of an entire landscape inside a seed at cosmic scale, two-thirds of the frame open dark void above and left, asymmetric composition with the pod anchored low-right, no figures no text no signatures no watermarks no letters no writing",
        "interior — inside the pod's miniature world, at the bank of its tiny silver stream under trees no taller than grass, the shell curving overhead like a wooden sky with day leaking through the split, no text no signatures no watermarks no letters no writing",
        "macro — the pod's split edge at closest range, bark fibers parting one by one, green-gold interior light flooding out across the dark shell like dawn under a door, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "wait for it...",
        "feel the thaw beginning...",
        "something stirs beneath..."
      ],
      "analysisRole": "dark",
      "gradeAs": "threshold"
    },
    {
      "intensityMultiplier": 0.58,
      "aiPrompt": "DARK BACKGROUND, giant fiddlehead fern unfurling at cosmic scale from a tight coil in the upper-left corner of deep green-black void, but as each frond unfurls it reveals a different spring scene contained within — one frond opens to show cherry blossoms in pale pink, another reveals meadow wildflowers in gold and white, another shows new translucent green leaves — like pages of a book of spring turning open, the spiral structure following a golden ratio with photorealistic fern texture and translucent hairs along the rachis catching warm gold backlight, fine pollen particles of pale rose and chartreuse dispersing from the unfurling tips rightward and downward into vast dark void filling two-thirds of the frame, the frond architecture impossibly detailed as if viewing a fern the size of a galaxy, asymmetric composition with the coil anchored upper-left, no figures no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND, giant fiddlehead fern unfurling at cosmic scale from a tight coil in the upper-left corner of deep green-black void, but as each frond unfurls it reveals a different spring scene contained within — one frond opens to show cherry blossoms in pale pink, another reveals meadow wildflowers in gold and white, another shows new translucent green leaves — like pages of a book of spring turning open, the spiral structure following a golden ratio with photorealistic fern texture and translucent hairs along the rachis catching warm gold backlight, fine pollen particles of pale rose and chartreuse dispersing from the unfurling tips rightward and downward into vast dark void filling two-thirds of the frame, the frond architecture impossibly detailed as if viewing a fern the size of a galaxy, asymmetric composition with the coil anchored upper-left, no figures no text no signatures no watermarks no letters no writing",
        "macro — one unfurling frond-tip at closest range caught mid-turn, the spring scene inside it half-revealed, translucent hairs along the coil lit gold, no text no signatures no watermarks no letters no writing",
        "wide — the giant fern from far back, its opened fronds glowing like lit pages held at many angles in the green-black void, pollen drifting between them, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "it's happening...",
        "the green is unstoppable...",
        "everything at once..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion"
    },
    {
      "intensityMultiplier": 0.8,
      "aiPrompt": "vast cross-section of vascular architecture rendered at impossible scale against deep black-green void — luminous circular vessels and tubular channels arranged in a designed ring pattern at cosmic scale, each vessel a different size with green-gold bioluminescent fluid flowing through them in visible currents, between the vessels a matrix of cellular forms glowing soft rose-pink and warm gold, fine particles of luminous sap streaming from the vessel ends into surrounding darkness, the living architecture of growth at cosmic scale where each vessel could be a tunnel through a galaxy, asymmetric composition offset lower-left with generous dark void upper-right, no landscape no ground no soil no figures, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "vast cross-section of vascular architecture rendered at impossible scale against deep black-green void — luminous circular vessels and tubular channels arranged in a designed ring pattern at cosmic scale, each vessel a different size with green-gold bioluminescent fluid flowing through them in visible currents, between the vessels a matrix of cellular forms glowing soft rose-pink and warm gold, fine particles of luminous sap streaming from the vessel ends into surrounding darkness, the living architecture of growth at cosmic scale where each vessel could be a tunnel through a galaxy, asymmetric composition offset lower-left with generous dark void upper-right, no landscape no ground no soil no figures, no text no signatures no watermarks no letters no writing",
        "interior kinetic — riding a vessel's current, green-gold sap-light streaming past, rose cell-chambers glowing as they pass, the channel curving toward a brightness ahead, no text no signatures no watermarks no letters no writing",
        "macro — one cell at the vessel wall at closest range, its membrane a warm rose lantern, gold fluid pulsing past in the channel beyond it, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "this is what was waiting...",
        "every cell remembers this...",
        "the bloom is you..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion"
    },
    {
      "intensityMultiplier": 1,
      "aiPrompt": "DARK BACKGROUND, field of wildflowers on a floating chunk of meadow earth viewed from within at eye-level with the flower heads, the flowers rendered with photorealistic detail — daisies, poppies in warm red, cornflowers in deep blue, buttercups in bright gold — swaying gently, bees and butterflies visible among the blooms with iridescent wing detail, the earth fragment visible at the edges where the meadow surface drops away revealing soil layers and dangling roots above deep cosmic blue void below, warm golden sunlight illuminating the flowers from the upper-left casting soft shadows, fine pollen particles drifting in the warm light, the meadow anchored across the lower two-thirds with cosmic blue space visible beyond the earth edge, the impossible intimacy of standing in a floating garden at atmospheric scale, no figures no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND, field of wildflowers on a floating chunk of meadow earth viewed from within at eye-level with the flower heads, the flowers rendered with photorealistic detail — daisies, poppies in warm red, cornflowers in deep blue, buttercups in bright gold — swaying gently, bees and butterflies visible among the blooms with iridescent wing detail, the earth fragment visible at the edges where the meadow surface drops away revealing soil layers and dangling roots above deep cosmic blue void below, warm golden sunlight illuminating the flowers from the upper-left casting soft shadows, fine pollen particles drifting in the warm light, the meadow anchored across the lower two-thirds with cosmic blue space visible beyond the earth edge, the impossible intimacy of standing in a floating garden at atmospheric scale, no figures no text no signatures no watermarks no letters no writing",
        "extreme macro — inside one poppy at eye level with its stamens, red petal-walls glowing with sunlight, pollen grains like gold boulders on the curved floor, no text no signatures no watermarks no letters no writing",
        "spirit-hint — across the floating meadow, the pollen-light half-gathers into a soft drifting cloud of radiance among the blooms, translucent and featureless, warm light moving like a careful wind, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "the garden is complete...",
        "everything is alive...",
        "rest here in the green..."
      ],
      "analysisRole": "peak",
      "gradeAs": "transcendence"
    },
    {
      "intensityMultiplier": 0.81,
      "aiPrompt": "DARK BACKGROUND, dandelion seed-head at macro scale in the right third of deep blue-black void, the sphere of seed-parachutes rendered with photorealistic detail — each individual pappus a perfect radial structure of impossibly fine silver-white filaments, several seeds detaching and drifting leftward and upward into the darkness, each floating seed-parachute catching faint warm gold and spring green light as it separates, the most distant seeds already tiny luminous points dissolving into deep space like newborn stars, fine individual filaments trailing behind each drifting seed, the main seed-head still holding dozens of seeds with the stem visible below, vast quiet dark void filling two-thirds of the frame at left, the beautiful dispersal of life into the cosmos at impossible scale, asymmetric composition weighted right, no figures no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND, dandelion seed-head at macro scale in the right third of deep blue-black void, the sphere of seed-parachutes rendered with photorealistic detail — each individual pappus a perfect radial structure of impossibly fine silver-white filaments, several seeds detaching and drifting leftward and upward into the darkness, each floating seed-parachute catching faint warm gold and spring green light as it separates, the most distant seeds already tiny luminous points dissolving into deep space like newborn stars, fine individual filaments trailing behind each drifting seed, the main seed-head still holding dozens of seeds with the stem visible below, vast quiet dark void filling two-thirds of the frame at left, the beautiful dispersal of life into the cosmos at impossible scale, asymmetric composition weighted right, no figures no text no signatures no watermarks no letters no writing",
        "macro — a single seed-parachute mid-flight at closest range, its silver filaments a perfect radial star, deep space soft and dark behind it, no text no signatures no watermarks no letters no writing",
        "cosmic — the drifting seeds from far back scattered across the dark like a new constellation being sown, the seed-head a dim sphere at one edge of the frame, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "the day was full...",
        "the garden sleeps...",
        "carry the pollen with you..."
      ],
      "analysisRole": "calm",
      "gradeAs": "illumination"
    },
    {
      "intensityMultiplier": 0.37,
      "aiPrompt": "DARK BACKGROUND, single thin plant stem with one closed bud at its tip rising from a tiny mound of dark rich earth floating in the lower-left corner of absolute black void, the stem rendered in muted olive-green with photorealistic cellular texture, the bud a small tight spiral of pale green and faint rose holding the memory of everything the bloom was inside its folded layers, a single dewdrop clinging to the bud tip catching faint warm prismatic light — a tiny spectrum visible in the drop, nearly the entire frame vast dark silence with only this single living form and its single drop of light, the quiet promise that what bloomed will bloom again at infinite scale, asymmetric composition with the stem small and anchored lower-left, no figures no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND, single thin plant stem with one closed bud at its tip rising from a tiny mound of dark rich earth floating in the lower-left corner of absolute black void, the stem rendered in muted olive-green with photorealistic cellular texture, the bud a small tight spiral of pale green and faint rose holding the memory of everything the bloom was inside its folded layers, a single dewdrop clinging to the bud tip catching faint warm prismatic light — a tiny spectrum visible in the drop, nearly the entire frame vast dark silence with only this single living form and its single drop of light, the quiet promise that what bloomed will bloom again at infinite scale, asymmetric composition with the stem small and anchored lower-left, no figures no text no signatures no watermarks no letters no writing",
        "extreme macro — the dewdrop on the bud tip at closest range, a tiny living spectrum inside it, the folded petals a soft green-rose spiral behind the glass, no text no signatures no watermarks no letters no writing",
        "wide — the small stem and its bud alone in vast dark from further back, the single point of prismatic light the only color in the silence, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "you bloomed...",
        "the spring is in you now..."
      ],
      "analysisRole": "last",
      "gradeAs": "integration"
    }
  ]
};
