// GENERATED by scripts/retheme-from-analysis.mjs — do not edit by hand.
// Per-phase beats + measured intensity for built-in journeys re-themed or
// re-arced from their v2 deep analysis (2026-10-05). Applied at module load
// in analysis-phase-bounds.ts. Mastered journeys are never listed here.
import type { JourneyPhase } from "./types";

export const BUILTIN_ANALYSIS_RETHEME: Record<string, Array<Partial<JourneyPhase> & { analysisRole?: string; gradeAs?: string }>> = {
  "the-ascent": [
    {
      "intensityMultiplier": 0.62,
      "aiPrompt": "DARK BACKGROUND — a single thin seam of cold silver light resting along the crest of a dark rock ridge in the lower right of vast darkness, a faint veil of luminous mist breathing over its edge, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — a single thin seam of cold silver light resting along the crest of a dark rock ridge in the lower right of vast darkness, a faint veil of luminous mist breathing over its edge, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — fine mist spilling over the edge of dark rock at closest range, countless suspended droplets glowing silver and faint amber, drifting at different depths, translucent and weightless, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "from high above, looking straight down on a long ridge of black rock dividing two pools of luminous mist, one pale glow slowly widening beneath the cloud on the left, the camera beginning to descend toward the crest, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "dark",
      "gradeAs": "threshold",
      "shaderOpacity": 0.62,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.9,
      "aiPrompt": "gliding inside a slow river of luminous cloud as it pours through a dark saddle between ridges, deep teal and silver billows of light folding over one another on every side, a faint amber sheen rising through them, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "gliding inside a slow river of luminous cloud as it pours through a dark saddle between ridges, deep teal and silver billows of light folding over one another on every side, a faint amber sheen rising through them, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "abstract — two broad bands of slate-blue and amber light rocking against each other across black in a slow repeating sigh, their edges dissolving into fine particles, wide dark space in the upper half, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro — a fine rime of light coating dark rock at the crest, one trembling patch of reflected silver rippling across it and resettling again and again, deep shadow filling the left side, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "gathering",
      "gradeAs": "expansion",
      "shaderOpacity": 0.49,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 1,
      "aiPrompt": "cosmic — an immense sea of luminous cloud heaving in slow swells beneath a long black ridge, seen from far above, cold silver and smoky violet light rolling across its surface like a galaxy turning, the camera rising through the dark, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — an immense sea of luminous cloud heaving in slow swells beneath a long black ridge, seen from far above, cold silver and smoky violet light rolling across its surface like a galaxy turning, the camera rising through the dark, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro at the height of the surge — the crest of one swell of glowing mist breaking over dark rock in a spray of silver particles, blazing against deep darkness in the right third, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "looking straight down on the dark ridge as luminous cloud surges against it from both sides, long plumes of lit mist torn upward from the crest and dissolving, the camera pulling back, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "peak",
      "gradeAs": "transcendence",
      "shaderOpacity": 0.46,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.96,
      "aiPrompt": "abstract — a sudden bloom of white-gold light unfolding across the dark in wide radiant fans, layers of pale gold and rose light opening one inside the next, kaleidoscopic and weightless, filling the upper left, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "abstract — a sudden bloom of white-gold light unfolding across the dark in wide radiant fans, layers of pale gold and rose light opening one inside the next, kaleidoscopic and weightless, filling the upper left, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "from high above, the whole sea of cloud glowing white-gold from within for one long moment, luminous and impossibly still, the black ridge cutting a diagonal through the radiance, the light already dimming at the far edges, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "a single faint amber point of light pulsing low in the lower right where the bloom has withdrawn, luminous mist closing softly around it, the ache left hanging in the dark, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "calm",
      "gradeAs": "illumination",
      "shaderOpacity": 0.47,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.69,
      "aiPrompt": "DARK BACKGROUND — one small wisp of pale blue lit mist suspended alone in the upper left of immense darkness, a few fine motes drifting upward from it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — one small wisp of pale blue lit mist suspended alone in the upper left of immense darkness, a few fine motes drifting upward from it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "rising slowly while looking straight down as the luminous cloud sinks back between the dark ridges, its surface softening to blue-grey, pale gold catching the high crests one by one, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — a single droplet of pale gold light clinging to the edge of dark rock at closest range, holding a tiny upside-down reflection of the whole ridge above the cloud, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "calm",
      "gradeAs": "integration",
      "shaderOpacity": 0.6,
      "sparse": true,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.37,
      "aiPrompt": "cosmic — from immense height the ridge becomes a faint silver line across deep blue darkness, a thin band of rose light lying along it, a quiet star field opening all around, still and unresolved, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — from immense height the ridge becomes a faint silver line across deep blue darkness, a thin band of rose light lying along it, a quiet star field opening all around, still and unresolved, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — the last veil of mist on dark rock at closest range turning pale dawn gold, translucent droplets dissolving into the dark one by one, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "DARK BACKGROUND — a single thin seam of pale gold light resting along the crest of a dark ridge in the lower right of vast darkness, the bookend of the first silver seam, left open, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "last",
      "gradeAs": "integration",
      "shaderOpacity": 0.62,
      "shaderOwned": true
    }
  ],
  "cosmic-drift": [
    {
      "intensityMultiplier": 0.53,
      "aiPrompt": "DARK BACKGROUND — a single small jagged shard of dark stone drifting in the lower left of deep space, its broken edge lit warm amber, a faint breath of golden dust lifting off it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — a single small jagged shard of dark stone drifting in the lower left of deep space, its broken edge lit warm amber, a faint breath of golden dust lifting off it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — the rough broken surface of the shard at closest range, warm amber light grazing every ridge, fine motes of golden dust lifting off it and hanging weightless in the beam, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "cosmic — from far away, a loose scatter of small amber shards drifting slowly through a vast star field, a faint warm haze of golden dust trailing between them, the camera gliding toward them, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "dark",
      "gradeAs": "threshold",
      "shaderOpacity": 0.62,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.87,
      "aiPrompt": "drifting inside a warm luminous cloud of golden dust, shards of dark stone passing slowly close on every side, their broken edges glowing honey and amber, the light pooling and spreading between them, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "drifting inside a warm luminous cloud of golden dust, shards of dark stone passing slowly close on every side, their broken edges glowing honey and amber, the light pooling and spreading between them, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "abstract — slow currents of golden dust flowing in long curving bands across black, pooling into soft spirals of honey light, wide dark space below, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro — golden dust settling across the broken surface of one shard in fine luminous drifts, faint sage-green glints in its hollows, impossible stillness, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "gathering",
      "gradeAs": "expansion",
      "shaderOpacity": 0.49,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.43,
      "aiPrompt": "DARK BACKGROUND — one small curl of golden dust suspended alone in the upper right of immense dark space, a few fine motes drifting away from it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — one small curl of golden dust suspended alone in the upper right of immense dark space, a few fine motes drifting away from it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "cosmic — one slow ring of pale gold light widening across the infinite void in the lower left, fading as it spreads, the dark around it perfectly still, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — one mote of golden dust at closest range, glowing softly and hanging motionless in the dark, a tiny warm spark held at its heart, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "gathering",
      "gradeAs": "integration",
      "shaderOpacity": 0.6,
      "sparse": true,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.94,
      "aiPrompt": "cosmic — an immense slow river of honey-gold dust flowing diagonally across deep space, countless small amber shards carried within it, light rising and widening along its length, the densest glow left of centre, the camera gliding with it, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — an immense slow river of honey-gold dust flowing diagonally across deep space, countless small amber shards carried within it, light rising and widening along its length, the densest glow left of centre, the camera gliding with it, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro — the leading edge of one shard blazing with warm light at closest range, golden dust streaming off it in fine luminous threads, deep dark filling the right side, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "abstract — gentle swells of amber and honey light rocking in slow repeating waves across black, each swell reaching a little further than the last, the long golden glow held motionless at the crest, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "gathering",
      "gradeAs": "illumination",
      "shaderOpacity": 0.48,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 1,
      "aiPrompt": "cosmic — vast slate-blue veils of nebula rolling across the golden river of dust, shafts of warm light breaking through the gaps and closing again, infinite darkness beyond, the camera rising through, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — vast slate-blue veils of nebula rolling across the golden river of dust, shafts of warm light breaking through the gaps and closing again, infinite darkness beyond, the camera rising through, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro — one shard caught in the passing slate-blue veil, its amber surface dimming and flaring as the shadow moves over it, fine dust glittering along its broken edge, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "from high above, the whole river of golden dust half-veiled in drifting blue-grey haze, long luminous bands of light and shadow trading across it, the camera pulling back, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "peak",
      "gradeAs": "transcendence",
      "shaderOpacity": 0.46,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.37,
      "aiPrompt": "cosmic — from immense distance the river of dust thinning to a faint thread of gold across a quiet star field, a few small shards drifting away into the deep dark, at peace, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — from immense distance the river of dust thinning to a faint thread of gold across a quiet star field, a few small shards drifting away into the deep dark, at peace, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — a last ember of gold light glowing in the hollow of one dark shard, fine motes lifting off it and dissolving into the dark, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "DARK BACKGROUND — a single small ember of warm gold light drifting in the lower left of vast dark space, the bookend of the first amber shard, slowly softening, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "last",
      "gradeAs": "integration",
      "shaderOpacity": 0.62,
      "shaderOwned": true
    }
  ],
  "the-ascension": [
    {
      "intensityMultiplier": 0.75,
      "aiPrompt": "DARK BACKGROUND — a single seed of golden light cracking open in the lower left of vast darkness, thin filaments of warm honey light reaching upward out of the split, a faint haze of gold dust lifting off it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — a single seed of golden light cracking open in the lower left of vast darkness, thin filaments of warm honey light reaching upward out of the split, a faint haze of gold dust lifting off it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — inside the seed's split at closest range, translucent amber walls glowing like warm resin, single grains of gold dust rising slowly through a thin shaft of light, a gentle rocking shimmer passing across them, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "looking straight down on a dark plain of soft umber haze filling the frame edge to edge, one small gold glow waking in the lower right, its first thread of light rising toward the camera, a slow slate shadow drifting across it, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "breathe...",
        "feel the warmth...",
        "light is coming..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "threshold",
      "shaderOpacity": 0.62,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.97,
      "aiPrompt": "inside a vertical ascent through layered golden strata, rivers of luminous particles streaming straight upward past translucent amber membranes stacked sky above sky, the camera rising with the current as the next layer glows rose-gold, one shade too bright, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "inside a vertical ascent through layered golden strata, rivers of luminous particles streaming straight upward past translucent amber membranes stacked sky above sky, the camera rising with the current as the next layer glows rose-gold, one shade too bright, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro — one gold particle of the climb at closest range, its facets flashing amber below and rose-gold above as it spins in the updraft, a soft shift of colour sliding across its surface, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "abstract — a sideways slip of the whole light: two broad bands of honey amber and brighter rose-gold sliding past each other across darkness, the lower band dropping half a step as the upper one blooms, fine particles shed along the seam, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "rise...",
        "the light knows you...",
        "open..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion",
      "shaderOpacity": 0.47,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.75,
      "aiPrompt": "from high above a boundless sea of radiant golden mist, luminous vapour rolling in slow immense swells to every edge of the frame, deep wells opening where shafts of white-gold light pour down into amber depth, the camera drifting slowly over the crests, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "from high above a boundless sea of radiant golden mist, luminous vapour rolling in slow immense swells to every edge of the frame, deep wells opening where shafts of white-gold light pour down into amber depth, the camera drifting slowly over the crests, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — motes of gold light suspended in one warm beam at closest range, each mote a tiny translucent sphere holding a reflection of the golden sea, turning weightless in still air, deep umber shadow filling the left side, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "cosmic — the golden sea seen from immense height as a slow spiral of honey and rose light breathing in infinite darkness, a cool band of slate-blue swelling at its rim before the summit, the camera rising away, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "see how vast you are...",
        "every direction is warmth...",
        "stay in this light..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "illumination",
      "shaderOpacity": 0.52,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 1,
      "aiPrompt": "abstract — weightless within an immense lattice of pure golden light, colossal ribs of radiant gold geometry curving in fibonacci spirals above and below, white brilliance blazing in the upper right, the light fracturing into shifting rose and violet colour along every curve, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "abstract — weightless within an immense lattice of pure golden light, colossal ribs of radiant gold geometry curving in fibonacci spirals above and below, white brilliance blazing in the upper right, the light fracturing into shifting rose and violet colour along every curve, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "cosmic — the golden geometry seen from far outside, a radiant fibonacci bloom of gold light hanging in the upper left of infinite dark space, its light pouring out through its own curves in long still rays, chromatic fringes of rose and violet planing across it, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro — one rib of the golden lattice at closest range, light flowing inside it like warm sap, its edge fraying into prismatic motes of rose and violet, an aching held brightness, deep shadow below, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "you are light...",
        "there is no boundary...",
        "this is home..."
      ],
      "analysisRole": "peak",
      "gradeAs": "transcendence",
      "shaderOpacity": 0.46,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.66,
      "aiPrompt": "DARK BACKGROUND — one small petal of amber light settling slowly downward in the upper right of immense darkness, a few high specks of gold still turning in the air above it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — one small petal of amber light settling slowly downward in the upper right of immense darkness, a few high specks of gold still turning in the air above it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — that petal of light at closest range as it turns over, rose iridescence sweeping across its translucent surface, fine veins of gold glowing faintly, soft dark all around, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "looking straight down through drifting layers of warm amber lit mist, each translucent layer thinning into particles as the camera descends toward a dim rose-gold glow in the lower left, the brighter place now far and dusky, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "gently now...",
        "the glow remains...",
        "carry the warmth..."
      ],
      "analysisRole": "lowering",
      "gradeAs": "integration",
      "shaderOpacity": 0.6,
      "sparse": true,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.37,
      "aiPrompt": "extreme macro — a slow gold pulse at closest range inside soft darkness, the last motes of light settling into it like dust after a long day, a faint halo of concentric amber rings breathing around it, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "extreme macro — a slow gold pulse at closest range inside soft darkness, the last motes of light settling into it like dust after a long day, a faint halo of concentric amber rings breathing around it, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "cosmic — from very far away a single warm gold point in vast dark space among faint stars, the whole ascent folded inside it, the camera pulling back into stillness, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "DARK BACKGROUND — a single small seed of amber light resting closed in the lower left of vast darkness, a faint glow kept inside it, the bookend of the first gold seed, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "you are changed...",
        "the light lives in you now..."
      ],
      "analysisRole": "last",
      "gradeAs": "integration",
      "shaderOpacity": 0.62,
      "shaderOwned": true
    }
  ],
  "mycelium-dream": [
    {
      "intensityMultiplier": 0.37,
      "aiPrompt": "DARK BACKGROUND — a single small bioluminescent spore glowing soft green-gold in the lower right of vast brown-black darkness, a faint warm glow breathing around it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — a single small bioluminescent spore glowing soft green-gold in the lower right of vast brown-black darkness, a faint warm glow breathing around it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "cosmic — a scatter of green-gold points of light spiraling slowly upward through an infinite dark void like the first stars forming, each one pulsing at its own pace, the camera drifting toward them, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — one translucent mushroom cap at closest range, cyan and amber light glowing through its flesh from within, a single spore lifting off its gill edge lit gold, luminous against the dark, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "the spores are waking...",
        "feel the soil...",
        "life begins small..."
      ],
      "analysisRole": "dark",
      "gradeAs": "threshold",
      "shaderOpacity": 0.62,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.49,
      "aiPrompt": "inside the dark earth beneath the glowing caps, countless pale threads of light reaching downward through brown-black depth, green-gold pulses travelling along them as they take root, the camera descending, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "inside the dark earth beneath the glowing caps, countless pale threads of light reaching downward through brown-black depth, green-gold pulses travelling along them as they take root, the camera descending, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "microscopic — two glowing mycelial threads reaching across a dark gap toward each other, green-gold light pulsing along them as the connection closes, fine motes glinting around the meeting, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "looking straight down on a dark ground netted with faint green-gold veins of light spreading outward from one bright point in the upper left, luminous and fractal, the web widening across the frame, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "it's growing...",
        "everything connects...",
        "feel the network..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion",
      "shaderOpacity": 0.58,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.64,
      "aiPrompt": "abstract — the gill geometry of one enormous mushroom cap seen from below, radiating blades of gold-green light fanning from an off-centre point in the upper left, a slow umber shadow sliding across them, prismatic motes drifting through the spokes, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "abstract — the gill geometry of one enormous mushroom cap seen from below, radiating blades of gold-green light fanning from an off-centre point in the upper left, a slow umber shadow sliding across them, prismatic motes drifting through the spokes, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro — one water droplet hanging from a gill ridge at closest range, the whole radiating gill structure curved inside it upside down, a prism-spark of amber burning at its heart, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "cosmic — dark umber clouds of dust drifting slowly across a glowing green-gold nebula, shadows passing over its light and lifting again, infinite darkness beyond, the camera passing through, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "the garden knows you...",
        "every leaf is aware...",
        "this intelligence is ancient..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion",
      "shaderOpacity": 0.55,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.78,
      "aiPrompt": "DARK BACKGROUND — one small node of green-gold light pulsing slowly alone in the upper left of immense brown-black darkness, a few faint motes drifting around it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — one small node of green-gold light pulsing slowly alone in the upper left of immense brown-black darkness, a few faint motes drifting around it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "from high above, a calm sheet of deep amber light lying across the dark ground, slow concentric ripples spreading outward from one point and fading, luminous and impossibly still, the camera hovering, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — a single bead of amber light resting at the tip of one fine mycelial thread at closest range, breathing slowly brighter and dimmer, darkness close around it, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "the forest settles...",
        "roots remember...",
        "return to soil..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "integration",
      "shaderOpacity": 0.6,
      "sparse": true,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.91,
      "aiPrompt": "cosmic — a vast bioluminescent network sweeping across an infinite brown-black void, millions of green-gold points joined by hair-thin threads of light like galaxies, ember-orange pulses racing between the nodes, the densest cluster blazing in the lower right, the camera pulling back to reveal it all, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — a vast bioluminescent network sweeping across an infinite brown-black void, millions of green-gold points joined by hair-thin threads of light like galaxies, ember-orange pulses racing between the nodes, the densest cluster blazing in the lower right, the camera pulling back to reveal it all, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "flying inside one glowing thread of the network, node-lights flaring past, amber signal-pulses overtaking and racing ahead, branches of light curving away into deep umber dark on every side, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "from very high above, the network spread across the whole dark ground filling the frame edge to edge, green-gold veins netting it, slow tides of ember-orange light rolling across it wave after wave, luminous and fractal, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "you are the network...",
        "all is one organism...",
        "breathe with the forest..."
      ],
      "analysisRole": "peak",
      "gradeAs": "transcendence",
      "shaderOpacity": 0.46,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.74,
      "aiPrompt": "abstract — the network slowly drawing inward, threads of green-gold light folding toward one point in long fractal spirals, the ember glow cooling to blue-black at the edges, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "abstract — the network slowly drawing inward, threads of green-gold light folding toward one point in long fractal spirals, the ember glow cooling to blue-black at the edges, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — the single bright node at closest range, a seed of condensed green-gold light with the memory of its threads still flickering faint at its rim, darkness pressing close, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "DARK BACKGROUND — a single green-gold point of light alone in the lower right of brown-black immensity, indistinguishable from a first star or a last seed, the bookend of the first light, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "one spore holds everything...",
        "you carry the forest..."
      ],
      "analysisRole": "calm",
      "gradeAs": "integration",
      "shaderOpacity": 0.53,
      "shaderOwned": true
    }
  ],
  "the-bloom": [
    {
      "intensityMultiplier": 0.45,
      "aiPrompt": "DARK BACKGROUND — a single seed pod of dark bark-like shell cracking open along fibonacci spiral lines in the lower right of deep brown-black void, a thin seam of green-gold light leaking out of the split, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — a single seed pod of dark bark-like shell cracking open along fibonacci spiral lines in the lower right of deep brown-black void, a thin seam of green-gold light leaking out of the split, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — the pod's split edge at closest range, translucent fibers parting one by one, green-gold light flooding out across the dark shell, fine luminous pollen lifting off into the void, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "looking straight down into the opened pod as into a tiny luminous world, a miniature silver stream winding through moss-soft green light far below, a mist of pale silver particles drifting over it, the camera slowly descending, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "wait for it...",
        "feel the thaw beginning...",
        "something stirs beneath..."
      ],
      "analysisRole": "dark",
      "gradeAs": "threshold",
      "shaderOpacity": 0.62,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.58,
      "aiPrompt": "DARK BACKGROUND — a single small fiddlehead coil of muted sage-green light curled tight in the upper left of deep green-black void, translucent hairs along its spiral glowing faintly gold, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — a single small fiddlehead coil of muted sage-green light curled tight in the upper left of deep green-black void, translucent hairs along its spiral glowing faintly gold, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "abstract — the slow unfurling as a fibonacci spiral of pale gold and fog-blue light opening across darkness, each turn a little wider than the last, a lifting veil of luminous mist thinning at its outer edge, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro — one frond-tip at closest range caught mid-turn, its translucent surface glowing sage and soft gold, a bead of light held in the curl with a tiny misty spring world curved inside it, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "it's happening...",
        "the green is unstoppable...",
        "everything at once..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "integration",
      "shaderOpacity": 0.6,
      "sparse": true,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.8,
      "aiPrompt": "cosmic — a vast cross-section of luminous vascular rings at impossible scale in deep black-green space, circular vessels of green-gold bioluminescent light arranged like a slow galaxy, a heavy swell of bronze light rolling through them, the camera rising through the dark, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — a vast cross-section of luminous vascular rings at impossible scale in deep black-green space, circular vessels of green-gold bioluminescent light arranged like a slow galaxy, a heavy swell of bronze light rolling through them, the camera rising through the dark, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "inside a translucent green stem at closest range, streams of green-gold sap-light flowing upward in a low rocking surge, tiny rose-lit cells glowing as they pass, abstract and luminous, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "from high above, a slow tide of luminous gold light rolling across a dark expanse of opened fronds filling the frame edge to edge, a high clearing of pale silver-gold glowing in the upper right, translucent and weightless, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "this is what was waiting...",
        "every cell remembers this...",
        "the bloom is you..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "illumination",
      "shaderOpacity": 0.51,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 1,
      "aiPrompt": "cosmic — a floating island of blooming meadow seen from far out in deep space, its flowers made of light in gold, crimson and deep blue blazing together, a vast spiral of pollen-light streaming off it like a galaxy arm across infinite darkness, the camera soaring back, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — a floating island of blooming meadow seen from far out in deep space, its flowers made of light in gold, crimson and deep blue blazing together, a vast spiral of pollen-light streaming off it like a galaxy arm across infinite darkness, the camera soaring back, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — inside one poppy of glowing red light at closest range, petal walls blazing translucent amber and crimson, pollen grains like luminous gold boulders on its curved floor, sparks of light lifting off them, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "abstract — the summit as resonance: concentric rings of gold and sage light pulsing outward across darkness from the lower left, layer over layer ringing at full force, fine luminous pollen caught in each band, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "the garden is complete...",
        "everything is alive...",
        "rest here in the green..."
      ],
      "analysisRole": "peak",
      "gradeAs": "transcendence",
      "shaderOpacity": 0.46,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.81,
      "aiPrompt": "macro — a dandelion seed-head of fine silver-white light in the right third of deep blue-black void, each pappus a perfect radial star of luminous filaments, a fast violet shadow sweeping across half of the sphere, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "macro — a dandelion seed-head of fine silver-white light in the right third of deep blue-black void, each pappus a perfect radial star of luminous filaments, a fast violet shadow sweeping across half of the sphere, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "cosmic — the seeds drifting free across the dark like a new constellation being sown, the dim seed-head at one edge of the frame, a band of violet shade passing over them and gold light returning, the camera drifting after them, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — a single seed-parachute at closest range, its silver filaments a radial star of light, a faint violet glow fading from its tip as warm bronze light returns, weightless, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "the day was full...",
        "the garden sleeps...",
        "carry the pollen with you..."
      ],
      "analysisRole": "calm",
      "gradeAs": "return",
      "shaderOpacity": 0.51,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.37,
      "aiPrompt": "DARK BACKGROUND — a single thin stem of muted olive light with one closed bud at its tip in the lower left of absolute black void, a tiny dewdrop of prismatic light resting on the bud, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — a single thin stem of muted olive light with one closed bud at its tip in the lower left of absolute black void, a tiny dewdrop of prismatic light resting on the bud, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — the dewdrop on the bud tip at closest range, a tiny living spectrum inside it, the folded petals a soft green-rose spiral behind the translucent drop, amber dusk fading, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "cosmic — the small bud seen from far away as one point of prismatic light in vast dark space among faint stars, the whole spring kept folded inside it, the camera slowly pulling back, left open, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "you bloomed...",
        "the spring is in you now..."
      ],
      "analysisRole": "last",
      "gradeAs": "integration",
      "shaderOpacity": 0.62,
      "shaderOwned": true
    }
  ],
  "inferno": [
    {
      "intensityMultiplier": 0.9,
      "aiPrompt": "DARK BACKGROUND — a single small shard of black volcanic glass floating alone in the lower right of immense blackness, one hairline seam of deep orange heat glowing inside it, its obsidian edges catching a faint rim of light, a few ash motes hanging weightless beside it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — a single small shard of black volcanic glass floating alone in the lower right of immense blackness, one hairline seam of deep orange heat glowing inside it, its obsidian edges catching a faint rim of light, a few ash motes hanging weightless beside it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — the hairline seam inside the volcanic glass shard at closest range, white-hot light breathing through the fracture from deep within, its razor edge dusted with fine grey ash, heat shimmer rising off it in slow ripples, black glass mirroring the glow, the camera pushing in toward the light, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "cosmic — pulling back as the first sparks escape the shard and scatter upward across infinite black, the glowing fragment now a tiny ember among drifting motes of orange light, ash particles trailing into vast empty darkness above and left, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "gradeAs": "threshold",
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 1,
      "aiPrompt": "from high above, looking straight down at an immense ember network spread across black far below, fractal fire threads branching between white-hot nodes like a dying star's skeleton, the network clustered in the lower right, the camera descending toward it through drifting ash, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "from high above, looking straight down at an immense ember network spread across black far below, fractal fire threads branching between white-hot nodes like a dying star's skeleton, the network clustered in the lower right, the camera descending toward it through drifting ash, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "PURE WHITE BACKGROUND — abstract — a designed lattice of black volcanic glass sweeping diagonally from the upper left across a brilliant pale ash-white ground, obsidian planes holding deep orange fire inside them, white-hot edges, scattered dark ash particles drifting down into vast open white space below, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — one curl of black smoke at closest range, lit from beneath by hidden orange fire, its folds turning slowly like heavy velvet, embers glinting inside the curl, the smoke unfurling upward out of the lower left into empty darkness, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "gradeAs": "expansion",
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 1.25,
      "aiPrompt": "cosmic — a black sun of fire burning in the upper right of infinite darkness, its corona a fractal crown of white-hot streamers and deep crimson flares lashing outward, ash and sparks wheeling around it like a galaxy, the camera plunging toward it, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — a black sun of fire burning in the upper right of infinite darkness, its corona a fractal crown of white-hot streamers and deep crimson flares lashing outward, ash and sparks wheeling around it like a galaxy, the camera plunging toward it, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "abstract — a vast fractal fire network sweeping in a descending spiral arc across black, white-hot nodes pulsing at every intersection, amber light coursing through interlinked ember threads, the spiral core low in the left third, burning streamers dissolving into ash trails and open dark, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — a single droplet of molten fire falling through black at closest range in the upper left third, its skin crawling with white-hot light and dark cooling crust, sparks shearing off its trailing edge in a curving wake, heat shimmer bending the darkness around it, menacing and alive, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "gradeAs": "transcendence",
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 1,
      "aiPrompt": "DARK BACKGROUND — a single small coal glowing deep orange in the lower left of vast black silence, its light swelling and dimming like slow breath, one thin ribbon of grey smoke rising from it and dissolving into the dark, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — a single small coal glowing deep orange in the lower left of vast black silence, its light swelling and dimming like slow breath, one thin ribbon of grey smoke rising from it and dissolving into the dark, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "PURE WHITE BACKGROUND — looking straight down into a boundless ash-white haze, fine dark ash particles falling slowly through the pale light toward the camera, two or three still carrying a faint orange core, immense open white space, weightless and still, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — the skin of one coal at closest range, gold light breathing slowly through a lace of white ash, the pulse slow as sleep, tiny sparks lifting off its cracks and drifting into the dark, the glow gathered to the right edge of the frame, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "gradeAs": "integration",
      "sparse": true,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.9,
      "aiPrompt": "abstract — a connected ember lattice arcing up from the lower left across deep charcoal darkness, prismatic heat threading through it from orange to amber to rose to cool silver, ash particles drifting upward into open space above, the camera rising through, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "abstract — a connected ember lattice arcing up from the lower left across deep charcoal darkness, prismatic heat threading through it from orange to amber to rose to cool silver, ash particles drifting upward into open space above, the camera rising through, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "close — a single rising spark cooling from gold to silver as it climbs through the dark in the right third of the frame, a faint curving trail of light behind it, fine ash motes turning slowly around it, cool grey-blue air opening above, everything beyond soft and empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "cosmic — a dim eclipsed sun of copper and rose hanging in the upper left of deep charcoal space, its fire banked to a thin glowing rim, streams of cooling sparks and ash rising past it into infinite darkness, the menace gone out of the fire, the camera drifting upward beside them, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "gradeAs": "return",
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.75,
      "aiPrompt": "cosmic — sparse ash particles and fading ember traces drifting across vast cool grey-black silence, the last connected fire forms clustered small in the lower left, dissolving into scattered sparks that trail diagonally toward infinite upper darkness, the particles carrying the fire's memory as they cool, almost nothing against everything, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — sparse ash particles and fading ember traces drifting across vast cool grey-black silence, the last connected fire forms clustered small in the lower left, dissolving into scattered sparks that trail diagonally toward infinite upper darkness, the particles carrying the fire's memory as they cool, almost nothing against everything, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — one flake of charcoal ash drifting at closest range in the lower right, its lace edge still holding the faintest orange core, the last living coal of the whole descent, a few cinder motes suspended weightless beside it in cool grey dark, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "DARK BACKGROUND — a single small shard of black volcanic glass resting in the lower right of vast cool darkness, its hairline seam cooled to a faint silver-rose glow, one ash mote settling beside it, nearly the entire frame empty, the bookend of the first light, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "gradeAs": "integration",
      "shaderOwned": true
    }
  ]
};
