// GENERATED by scripts/retheme-from-analysis.mjs — do not edit by hand.
// Per-phase beats + measured intensity for built-in journeys re-themed or
// re-arced from their v2 deep analysis (2026-10-05). Applied at module load
// in analysis-phase-bounds.ts. Mastered journeys are never listed here.
import type { JourneyPhase } from "./types";

export const BUILTIN_ANALYSIS_RETHEME: Record<string, Array<Partial<JourneyPhase> & { analysisRole?: string; gradeAs?: string }>> = {
  "the-ascent": [
    {
      "intensityMultiplier": 0.62,
      "aiPrompt": "DARK BACKGROUND — a single thin seam of cold silver light resting along the crest of a dark rock ridge in the lower right of vast darkness, a faint veil of luminous mist breathing over its edge, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — a single thin seam of cold silver light resting along the crest of a dark rock ridge in the lower right of vast darkness, a faint veil of luminous mist breathing over its edge, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — fine mist spilling over the edge of dark rock at closest range, countless suspended droplets glowing silver and faint amber, drifting at different depths, translucent and weightless, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "from high above, looking straight down on a long ridge of black rock dividing two pools of luminous mist, one pale glow slowly widening beneath the cloud on the left, the camera beginning to descend toward the crest, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "dark",
      "gradeAs": "threshold",
      "shaderOpacity": 0.62,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.9,
      "aiPrompt": "gliding inside a slow river of luminous cloud as it pours through a dark saddle between ridges, deep teal and silver billows of light folding over one another on every side, a faint amber sheen rising through them, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "gliding inside a slow river of luminous cloud as it pours through a dark saddle between ridges, deep teal and silver billows of light folding over one another on every side, a faint amber sheen rising through them, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "abstract — two broad bands of slate-blue and amber light rocking against each other across black in a slow repeating sigh, their edges dissolving into fine particles, wide dark space in the upper half, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro — a fine rime of light coating dark rock at the crest, one trembling patch of reflected silver rippling across it and resettling again and again, deep shadow filling the left side, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "gathering",
      "gradeAs": "expansion",
      "shaderOpacity": 0.49,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 1,
      "aiPrompt": "cosmic — an immense sea of luminous cloud heaving in slow swells beneath a long black ridge, seen from far above, cold silver and smoky violet light rolling across its surface like a galaxy turning, the camera rising through the dark, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — an immense sea of luminous cloud heaving in slow swells beneath a long black ridge, seen from far above, cold silver and smoky violet light rolling across its surface like a galaxy turning, the camera rising through the dark, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro at the height of the surge — the crest of one swell of glowing mist breaking over dark rock in a spray of silver particles, blazing against deep darkness in the right third, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "looking straight down on the dark ridge as luminous cloud surges against it from both sides, long plumes of lit mist torn upward from the crest and dissolving, the camera pulling back, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "peak",
      "gradeAs": "transcendence",
      "shaderOpacity": 0.46,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.96,
      "aiPrompt": "abstract — a sudden bloom of white-gold light unfolding across the dark in wide radiant fans, layers of pale gold and rose light opening one inside the next, kaleidoscopic and weightless, filling the upper left, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "abstract — a sudden bloom of white-gold light unfolding across the dark in wide radiant fans, layers of pale gold and rose light opening one inside the next, kaleidoscopic and weightless, filling the upper left, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "from high above, the whole sea of cloud glowing white-gold from within for one long moment, luminous and impossibly still, the black ridge cutting a diagonal through the radiance, the light already dimming at the far edges, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "a single faint amber point of light pulsing low in the lower right where the bloom has withdrawn, luminous mist closing softly around it, the ache left hanging in the dark, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "calm",
      "gradeAs": "illumination",
      "shaderOpacity": 0.47,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.69,
      "aiPrompt": "DARK BACKGROUND — one small wisp of pale blue lit mist suspended alone in the upper left of immense darkness, a few fine motes drifting upward from it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — one small wisp of pale blue lit mist suspended alone in the upper left of immense darkness, a few fine motes drifting upward from it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "rising slowly while looking straight down as the luminous cloud sinks back between the dark ridges, its surface softening to blue-grey, pale gold catching the high crests one by one, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — a single droplet of pale gold light clinging to the edge of dark rock at closest range, holding a tiny upside-down reflection of the whole ridge above the cloud, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "calm",
      "gradeAs": "integration",
      "shaderOpacity": 0.6,
      "sparse": true,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.37,
      "aiPrompt": "cosmic — from immense height the ridge becomes a faint silver line across deep blue darkness, a thin band of rose light lying along it, a quiet star field opening all around, still and unresolved, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — from immense height the ridge becomes a faint silver line across deep blue darkness, a thin band of rose light lying along it, a quiet star field opening all around, still and unresolved, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — the last veil of mist on dark rock at closest range turning pale dawn gold, translucent droplets dissolving into the dark one by one, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "DARK BACKGROUND — a single thin seam of pale gold light resting along the crest of a dark ridge in the lower right of vast darkness, the bookend of the first silver seam, left open, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "last",
      "gradeAs": "integration",
      "shaderOpacity": 0.62,
      "shaderOwned": true
    }
  ],
  "cosmic-drift": [
    {
      "intensityMultiplier": 0.53,
      "aiPrompt": "DARK BACKGROUND — a single small jagged shard of dark stone drifting in the lower left of deep space, its broken edge lit warm amber, a faint breath of golden dust lifting off it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — a single small jagged shard of dark stone drifting in the lower left of deep space, its broken edge lit warm amber, a faint breath of golden dust lifting off it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — the rough broken surface of the shard at closest range, warm amber light grazing every ridge, fine motes of golden dust lifting off it and hanging weightless in the beam, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "cosmic — from far away, a loose scatter of small amber shards drifting slowly through a vast star field, a faint warm haze of golden dust trailing between them, the camera gliding toward them, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "dark",
      "gradeAs": "threshold",
      "shaderOpacity": 0.62,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.87,
      "aiPrompt": "drifting inside a warm luminous cloud of golden dust, shards of dark stone passing slowly close on every side, their broken edges glowing honey and amber, the light pooling and spreading between them, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "drifting inside a warm luminous cloud of golden dust, shards of dark stone passing slowly close on every side, their broken edges glowing honey and amber, the light pooling and spreading between them, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "abstract — slow currents of golden dust flowing in long curving bands across black, pooling into soft spirals of honey light, wide dark space below, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro — golden dust settling across the broken surface of one shard in fine luminous drifts, faint sage-green glints in its hollows, impossible stillness, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "gathering",
      "gradeAs": "expansion",
      "shaderOpacity": 0.49,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.43,
      "aiPrompt": "DARK BACKGROUND — one small curl of golden dust suspended alone in the upper right of immense dark space, a few fine motes drifting away from it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — one small curl of golden dust suspended alone in the upper right of immense dark space, a few fine motes drifting away from it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "cosmic — one slow ring of pale gold light widening across the infinite void in the lower left, fading as it spreads, the dark around it perfectly still, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — one mote of golden dust at closest range, glowing softly and hanging motionless in the dark, a tiny warm spark held at its heart, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "gathering",
      "gradeAs": "integration",
      "shaderOpacity": 0.6,
      "sparse": true,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.94,
      "aiPrompt": "cosmic — an immense slow river of honey-gold dust flowing diagonally across deep space, countless small amber shards carried within it, light rising and widening along its length, the densest glow left of centre, the camera gliding with it, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — an immense slow river of honey-gold dust flowing diagonally across deep space, countless small amber shards carried within it, light rising and widening along its length, the densest glow left of centre, the camera gliding with it, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro — the leading edge of one shard blazing with warm light at closest range, golden dust streaming off it in fine luminous threads, deep dark filling the right side, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "abstract — gentle swells of amber and honey light rocking in slow repeating waves across black, each swell reaching a little further than the last, the long golden glow held motionless at the crest, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "gathering",
      "gradeAs": "illumination",
      "shaderOpacity": 0.48,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 1,
      "aiPrompt": "cosmic — vast slate-blue veils of nebula rolling across the golden river of dust, shafts of warm light breaking through the gaps and closing again, infinite darkness beyond, the camera rising through, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — vast slate-blue veils of nebula rolling across the golden river of dust, shafts of warm light breaking through the gaps and closing again, infinite darkness beyond, the camera rising through, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro — one shard caught in the passing slate-blue veil, its amber surface dimming and flaring as the shadow moves over it, fine dust glittering along its broken edge, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "from high above, the whole river of golden dust half-veiled in drifting blue-grey haze, long luminous bands of light and shadow trading across it, the camera pulling back, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "peak",
      "gradeAs": "transcendence",
      "shaderOpacity": 0.46,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.37,
      "aiPrompt": "cosmic — from immense distance the river of dust thinning to a faint thread of gold across a quiet star field, a few small shards drifting away into the deep dark, at peace, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — from immense distance the river of dust thinning to a faint thread of gold across a quiet star field, a few small shards drifting away into the deep dark, at peace, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — a last ember of gold light glowing in the hollow of one dark shard, fine motes lifting off it and dissolving into the dark, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "DARK BACKGROUND — a single small ember of warm gold light drifting in the lower left of vast dark space, the bookend of the first amber shard, slowly softening, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [],
      "analysisRole": "last",
      "gradeAs": "integration",
      "shaderOpacity": 0.62,
      "shaderOwned": true
    }
  ],
  "the-ascension": [
    {
      "intensityMultiplier": 0.75,
      "aiPrompt": "extreme macro in deep darkness — a single seed of golden light cracking open on dark soil at closest range, thin filaments of warm light reaching upward out of the split, fine gold dust lifting off it, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "extreme macro in deep darkness — a single seed of golden light cracking open on dark soil at closest range, thin filaments of warm light reaching upward out of the split, fine gold dust lifting off it, asymmetric off-center composition with strong diagonal weight, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "microscopic — inside the seed's crack, a stair of light no wider than a vein climbing out of the dark kernel, gold dust rising through it in single grains, no text no signatures no watermarks no letters no writing",
        "wide — a dark plain under starless black, one small gold glow waking low in the frame, its light reaching upward in a thin first thread, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "breathe...",
        "feel the warmth...",
        "light is coming..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion"
    },
    {
      "intensityMultiplier": 0.97,
      "aiPrompt": "vertical ascent through layered golden strata — rivers of luminous particles streaming straight upward past translucent amber membranes stacked like sky above sky, each layer brighter than the one below, the viewpoint rising with the current, gold dust accelerating along the climb, warm light strengthening toward an unseen brilliance overhead, strong vertical energy with the densest stream off-center left, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "vertical ascent through layered golden strata — rivers of luminous particles streaming straight upward past translucent amber membranes stacked like sky above sky, each layer brighter than the one below, the viewpoint rising with the current, gold dust accelerating along the climb, warm light strengthening toward an unseen brilliance overhead, strong vertical energy with the densest stream off-center left, no text no signatures no watermarks no letters no writing",
        "interior — passing through one amber membrane, the layer parting around the viewpoint like warm mist, the next brighter sky already glowing through from above, no text no signatures no watermarks no letters no writing",
        "macro — one gold particle of the climb at closest range, its facets flashing the layered skies above and below as it spins in the updraft, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "rise...",
        "the light knows you...",
        "open..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion"
    },
    {
      "intensityMultiplier": 0.75,
      "aiPrompt": "aerial view from above a boundless sea of radiant golden cloud, the sunlit vapor rolling in slow immense swells to every edge of frame, deep wells opening in the cloud where shafts of white-gold light pour down into amber depth, the cloud tops burning brightest along one diagonal, serene altitude and total clarity, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "aerial view from above a boundless sea of radiant golden cloud, the sunlit vapor rolling in slow immense swells to every edge of frame, deep wells opening in the cloud where shafts of white-gold light pour down into amber depth, the cloud tops burning brightest along one diagonal, serene altitude and total clarity, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "intimate — skimming the radiant cloud-tops, gold vapor curling past the viewpoint, a deep well opening ahead with white-gold light standing in it like a pillar, no text no signatures no watermarks no letters no writing",
        "spirit-hint — over the cloud sea, the light half-gathers into a tall ancestral almost-presence of white-gold, translucent and featureless, standing on nothing, opening back into brightness, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "see how vast you are...",
        "every direction is warmth...",
        "stay in this light..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion"
    },
    {
      "intensityMultiplier": 1,
      "aiPrompt": "suspended weightless inside a monumental vault of pure golden light with no floor and no ground anywhere — colossal ribs of radiant gold geometry filling the entire frame in fibonacci curves above and below and to every side, white brilliance blazing at the convergence point off-center, luminous particles drifting through the vast interior like slow embers, only light architecture and glowing air in all directions, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "suspended weightless inside a monumental vault of pure golden light with no floor and no ground anywhere — colossal ribs of radiant gold geometry filling the entire frame in fibonacci curves above and below and to every side, white brilliance blazing at the convergence point off-center, luminous particles drifting through the vast interior like slow embers, only light architecture and glowing air in all directions, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro — one rib of the golden vault at closest range, light flowing inside it like sap in a branch of dawn, luminous motes drifting slowly past, no text no signatures no watermarks no letters no writing",
        "cosmic — the vault seen from outside, a lantern of gold geometry hanging alone in black space, its light spilling through its own ribs in long still rays, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "you are light...",
        "there is no boundary...",
        "this is home..."
      ],
      "analysisRole": "peak",
      "gradeAs": "transcendence"
    },
    {
      "intensityMultiplier": 0.66,
      "aiPrompt": "intimate slow descent through hanging veils of warm amber light, translucent petals of gold luminance planing gently downward past the viewpoint in long glide paths, each catching rose and violet iridescence as it turns, the veils parting softly ahead and closing above, warmth deepening from white-gold toward ember amber with the fall, tender unhurried motion, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "intimate slow descent through hanging veils of warm amber light, translucent petals of gold luminance planing gently downward past the viewpoint in long glide paths, each catching rose and violet iridescence as it turns, the veils parting softly ahead and closing above, warmth deepening from white-gold toward ember amber with the fall, tender unhurried motion, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro — one petal of gold light planing down at closest range, rose iridescence sweeping across its face as it turns over, no text no signatures no watermarks no letters no writing",
        "wide — the veils from below, layer after amber layer parting as the light descends toward a warm deep glow waiting at the bottom of the frame, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "gently now...",
        "the glow remains...",
        "carry the warmth..."
      ],
      "analysisRole": "lowering",
      "gradeAs": "return"
    },
    {
      "intensityMultiplier": 0.37,
      "aiPrompt": "macro stillness — one small warm amber glow resting in deep soft darkness, a faint halo of concentric golden rings breathing around it, a few last luminous motes settling toward it like sparks coming to rest, the light steady and kept, enormous quiet dark all around with the glow held low in the frame, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "macro stillness — one small warm amber glow resting in deep soft darkness, a faint halo of concentric golden rings breathing around it, a few last luminous motes settling toward it like sparks coming to rest, the light steady and kept, enormous quiet dark all around with the glow held low in the frame, no text no signatures no watermarks no letters no writing",
        "extreme macro — the glow's heart at closest range, a slow gold pulse inside soft dark, the last motes settling into it like dust after glory, no text no signatures no watermarks no letters no writing",
        "cosmic finale — the small warm glow seen from very far away, one gold point in vast dark, the whole ascent kept inside it, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "you are changed...",
        "the light lives in you now..."
      ],
      "analysisRole": "last",
      "gradeAs": "integration"
    }
  ],
  "mycelium-dream": [
    {
      "intensityMultiplier": 0.37,
      "aiPrompt": "DARK BACKGROUND — a single small bioluminescent spore glowing soft green-gold in the lower right of vast brown-black darkness, a faint warm glow breathing around it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — a single small bioluminescent spore glowing soft green-gold in the lower right of vast brown-black darkness, a faint warm glow breathing around it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "cosmic — a scatter of green-gold points of light spiraling slowly upward through an infinite dark void like the first stars forming, each one pulsing at its own pace, the camera drifting toward them, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — one translucent mushroom cap at closest range, cyan and amber light glowing through its flesh from within, a single spore lifting off its gill edge lit gold, luminous against the dark, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "the spores are waking...",
        "feel the soil...",
        "life begins small..."
      ],
      "analysisRole": "dark",
      "gradeAs": "threshold",
      "shaderOpacity": 0.62,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.49,
      "aiPrompt": "inside the dark earth beneath the glowing caps, countless pale threads of light reaching downward through brown-black depth, green-gold pulses travelling along them as they take root, the camera descending, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "inside the dark earth beneath the glowing caps, countless pale threads of light reaching downward through brown-black depth, green-gold pulses travelling along them as they take root, the camera descending, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "microscopic — two glowing mycelial threads reaching across a dark gap toward each other, green-gold light pulsing along them as the connection closes, fine motes glinting around the meeting, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "looking straight down on a dark ground netted with faint green-gold veins of light spreading outward from one bright point in the upper left, luminous and fractal, the web widening across the frame, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "it's growing...",
        "everything connects...",
        "feel the network..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion",
      "shaderOpacity": 0.58,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.64,
      "aiPrompt": "abstract — the gill geometry of one enormous mushroom cap seen from below, radiating blades of gold-green light fanning from an off-centre point in the upper left, a slow umber shadow sliding across them, prismatic motes drifting through the spokes, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "abstract — the gill geometry of one enormous mushroom cap seen from below, radiating blades of gold-green light fanning from an off-centre point in the upper left, a slow umber shadow sliding across them, prismatic motes drifting through the spokes, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "macro — one water droplet hanging from a gill ridge at closest range, the whole radiating gill structure curved inside it upside down, a prism-spark of amber burning at its heart, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "cosmic — dark umber clouds of dust drifting slowly across a glowing green-gold nebula, shadows passing over its light and lifting again, infinite darkness beyond, the camera passing through, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "the garden knows you...",
        "every leaf is aware...",
        "this intelligence is ancient..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion",
      "shaderOpacity": 0.55,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.78,
      "aiPrompt": "DARK BACKGROUND — one small node of green-gold light pulsing slowly alone in the upper left of immense brown-black darkness, a few faint motes drifting around it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — one small node of green-gold light pulsing slowly alone in the upper left of immense brown-black darkness, a few faint motes drifting around it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "from high above, a calm sheet of deep amber light lying across the dark ground, slow concentric ripples spreading outward from one point and fading, luminous and impossibly still, the camera hovering, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — a single bead of amber light resting at the tip of one fine mycelial thread at closest range, breathing slowly brighter and dimmer, darkness close around it, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "the forest settles...",
        "roots remember...",
        "return to soil..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "integration",
      "shaderOpacity": 0.6,
      "sparse": true,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.91,
      "aiPrompt": "cosmic — a vast bioluminescent network sweeping across an infinite brown-black void, millions of green-gold points joined by hair-thin threads of light like galaxies, ember-orange pulses racing between the nodes, the densest cluster blazing in the lower right, the camera pulling back to reveal it all, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — a vast bioluminescent network sweeping across an infinite brown-black void, millions of green-gold points joined by hair-thin threads of light like galaxies, ember-orange pulses racing between the nodes, the densest cluster blazing in the lower right, the camera pulling back to reveal it all, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "flying inside one glowing thread of the network, node-lights flaring past, amber signal-pulses overtaking and racing ahead, branches of light curving away into deep umber dark on every side, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "from very high above, the network spread across the whole dark ground filling the frame edge to edge, green-gold veins netting it, slow tides of ember-orange light rolling across it wave after wave, luminous and fractal, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "you are the network...",
        "all is one organism...",
        "breathe with the forest..."
      ],
      "analysisRole": "peak",
      "gradeAs": "transcendence",
      "shaderOpacity": 0.46,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.74,
      "aiPrompt": "abstract — the network slowly drawing inward, threads of green-gold light folding toward one point in long fractal spirals, the ember glow cooling to blue-black at the edges, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "abstract — the network slowly drawing inward, threads of green-gold light folding toward one point in long fractal spirals, the ember glow cooling to blue-black at the edges, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — the single bright node at closest range, a seed of condensed green-gold light with the memory of its threads still flickering faint at its rim, darkness pressing close, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "DARK BACKGROUND — a single green-gold point of light alone in the lower right of brown-black immensity, indistinguishable from a first star or a last seed, the bookend of the first light, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "one spore holds everything...",
        "you carry the forest..."
      ],
      "analysisRole": "calm",
      "gradeAs": "integration",
      "shaderOpacity": 0.53,
      "shaderOwned": true
    }
  ],
  "the-bloom": [
    {
      "intensityMultiplier": 0.45,
      "aiPrompt": "DARK BACKGROUND, enormous seed pod cracking open in the lower-right third of deep brown-black void, the pod shell rendered with photorealistic dark bark-like texture split along fibonacci spiral lines, but inside the pod instead of seeds there is a miniature world — tiny trees with green canopies, a winding stream of blue-silver water, clusters of wildflowers in white and gold, all contained within the pod shell like a terrarium, warm green-gold light spilling from the interior world into the surrounding darkness, fine spores and tiny flower petals ejecting from the opening along diagonal paths upward-left into vast dark space, the impossible nursery of an entire landscape inside a seed at cosmic scale, two-thirds of the frame open dark void above and left, asymmetric composition with the pod anchored low-right, no figures no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND, enormous seed pod cracking open in the lower-right third of deep brown-black void, the pod shell rendered with photorealistic dark bark-like texture split along fibonacci spiral lines, but inside the pod instead of seeds there is a miniature world — tiny trees with green canopies, a winding stream of blue-silver water, clusters of wildflowers in white and gold, all contained within the pod shell like a terrarium, warm green-gold light spilling from the interior world into the surrounding darkness, fine spores and tiny flower petals ejecting from the opening along diagonal paths upward-left into vast dark space, the impossible nursery of an entire landscape inside a seed at cosmic scale, two-thirds of the frame open dark void above and left, asymmetric composition with the pod anchored low-right, no figures no text no signatures no watermarks no letters no writing",
        "interior — inside the pod's miniature world, at the bank of its tiny silver stream under trees no taller than grass, the shell curving overhead like a wooden sky with day leaking through the split, no text no signatures no watermarks no letters no writing",
        "macro — the pod's split edge at closest range, bark fibers parting one by one, green-gold interior light flooding out across the dark shell like dawn under a door, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "wait for it...",
        "feel the thaw beginning...",
        "something stirs beneath..."
      ],
      "analysisRole": "dark",
      "gradeAs": "threshold"
    },
    {
      "intensityMultiplier": 0.58,
      "aiPrompt": "DARK BACKGROUND, giant fiddlehead fern unfurling at cosmic scale from a tight coil in the upper-left corner of deep green-black void, but as each frond unfurls it reveals a different spring scene contained within — one frond opens to show cherry blossoms in pale pink, another reveals meadow wildflowers in gold and white, another shows new translucent green leaves — like pages of a book of spring turning open, the spiral structure following a golden ratio with photorealistic fern texture and translucent hairs along the rachis catching warm gold backlight, fine pollen particles of pale rose and chartreuse dispersing from the unfurling tips rightward and downward into vast dark void filling two-thirds of the frame, the frond architecture impossibly detailed as if viewing a fern the size of a galaxy, asymmetric composition with the coil anchored upper-left, no figures no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND, giant fiddlehead fern unfurling at cosmic scale from a tight coil in the upper-left corner of deep green-black void, but as each frond unfurls it reveals a different spring scene contained within — one frond opens to show cherry blossoms in pale pink, another reveals meadow wildflowers in gold and white, another shows new translucent green leaves — like pages of a book of spring turning open, the spiral structure following a golden ratio with photorealistic fern texture and translucent hairs along the rachis catching warm gold backlight, fine pollen particles of pale rose and chartreuse dispersing from the unfurling tips rightward and downward into vast dark void filling two-thirds of the frame, the frond architecture impossibly detailed as if viewing a fern the size of a galaxy, asymmetric composition with the coil anchored upper-left, no figures no text no signatures no watermarks no letters no writing",
        "macro — one unfurling frond-tip at closest range caught mid-turn, the spring scene inside it half-revealed, translucent hairs along the coil lit gold, no text no signatures no watermarks no letters no writing",
        "wide — the giant fern from far back, its opened fronds glowing like lit pages held at many angles in the green-black void, pollen drifting between them, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "it's happening...",
        "the green is unstoppable...",
        "everything at once..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion"
    },
    {
      "intensityMultiplier": 0.8,
      "aiPrompt": "vast cross-section of vascular architecture rendered at impossible scale against deep black-green void — luminous circular vessels and tubular channels arranged in a designed ring pattern at cosmic scale, each vessel a different size with green-gold bioluminescent fluid flowing through them in visible currents, between the vessels a matrix of cellular forms glowing soft rose-pink and warm gold, fine particles of luminous sap streaming from the vessel ends into surrounding darkness, the living architecture of growth at cosmic scale where each vessel could be a tunnel through a galaxy, asymmetric composition offset lower-left with generous dark void upper-right, no landscape no ground no soil no figures, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "vast cross-section of vascular architecture rendered at impossible scale against deep black-green void — luminous circular vessels and tubular channels arranged in a designed ring pattern at cosmic scale, each vessel a different size with green-gold bioluminescent fluid flowing through them in visible currents, between the vessels a matrix of cellular forms glowing soft rose-pink and warm gold, fine particles of luminous sap streaming from the vessel ends into surrounding darkness, the living architecture of growth at cosmic scale where each vessel could be a tunnel through a galaxy, asymmetric composition offset lower-left with generous dark void upper-right, no landscape no ground no soil no figures, no text no signatures no watermarks no letters no writing",
        "interior kinetic — riding a vessel's current, green-gold sap-light streaming past, rose cell-chambers glowing as they pass, the channel curving toward a brightness ahead, no text no signatures no watermarks no letters no writing",
        "macro — one cell at the vessel wall at closest range, its membrane a warm rose lantern, gold fluid pulsing past in the channel beyond it, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "this is what was waiting...",
        "every cell remembers this...",
        "the bloom is you..."
      ],
      "analysisRole": "gathering",
      "gradeAs": "expansion"
    },
    {
      "intensityMultiplier": 1,
      "aiPrompt": "DARK BACKGROUND, field of wildflowers on a floating chunk of meadow earth viewed from within at eye-level with the flower heads, the flowers rendered with photorealistic detail — daisies, poppies in warm red, cornflowers in deep blue, buttercups in bright gold — swaying gently, bees and butterflies visible among the blooms with iridescent wing detail, the earth fragment visible at the edges where the meadow surface drops away revealing soil layers and dangling roots above deep cosmic blue void below, warm golden sunlight illuminating the flowers from the upper-left casting soft shadows, fine pollen particles drifting in the warm light, the meadow anchored across the lower two-thirds with cosmic blue space visible beyond the earth edge, the impossible intimacy of standing in a floating garden at atmospheric scale, no figures no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND, field of wildflowers on a floating chunk of meadow earth viewed from within at eye-level with the flower heads, the flowers rendered with photorealistic detail — daisies, poppies in warm red, cornflowers in deep blue, buttercups in bright gold — swaying gently, bees and butterflies visible among the blooms with iridescent wing detail, the earth fragment visible at the edges where the meadow surface drops away revealing soil layers and dangling roots above deep cosmic blue void below, warm golden sunlight illuminating the flowers from the upper-left casting soft shadows, fine pollen particles drifting in the warm light, the meadow anchored across the lower two-thirds with cosmic blue space visible beyond the earth edge, the impossible intimacy of standing in a floating garden at atmospheric scale, no figures no text no signatures no watermarks no letters no writing",
        "extreme macro — inside one poppy at eye level with its stamens, red petal-walls glowing with sunlight, pollen grains like gold boulders on the curved floor, no text no signatures no watermarks no letters no writing",
        "spirit-hint — across the floating meadow, the pollen-light half-gathers into a soft drifting cloud of radiance among the blooms, translucent and featureless, warm light moving like a careful wind, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "the garden is complete...",
        "everything is alive...",
        "rest here in the green..."
      ],
      "analysisRole": "peak",
      "gradeAs": "transcendence"
    },
    {
      "intensityMultiplier": 0.81,
      "aiPrompt": "DARK BACKGROUND, dandelion seed-head at macro scale in the right third of deep blue-black void, the sphere of seed-parachutes rendered with photorealistic detail — each individual pappus a perfect radial structure of impossibly fine silver-white filaments, several seeds detaching and drifting leftward and upward into the darkness, each floating seed-parachute catching faint warm gold and spring green light as it separates, the most distant seeds already tiny luminous points dissolving into deep space like newborn stars, fine individual filaments trailing behind each drifting seed, the main seed-head still holding dozens of seeds with the stem visible below, vast quiet dark void filling two-thirds of the frame at left, the beautiful dispersal of life into the cosmos at impossible scale, asymmetric composition weighted right, no figures no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND, dandelion seed-head at macro scale in the right third of deep blue-black void, the sphere of seed-parachutes rendered with photorealistic detail — each individual pappus a perfect radial structure of impossibly fine silver-white filaments, several seeds detaching and drifting leftward and upward into the darkness, each floating seed-parachute catching faint warm gold and spring green light as it separates, the most distant seeds already tiny luminous points dissolving into deep space like newborn stars, fine individual filaments trailing behind each drifting seed, the main seed-head still holding dozens of seeds with the stem visible below, vast quiet dark void filling two-thirds of the frame at left, the beautiful dispersal of life into the cosmos at impossible scale, asymmetric composition weighted right, no figures no text no signatures no watermarks no letters no writing",
        "macro — a single seed-parachute mid-flight at closest range, its silver filaments a perfect radial star, deep space soft and dark behind it, no text no signatures no watermarks no letters no writing",
        "cosmic — the drifting seeds from far back scattered across the dark like a new constellation being sown, the seed-head a dim sphere at one edge of the frame, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "the day was full...",
        "the garden sleeps...",
        "carry the pollen with you..."
      ],
      "analysisRole": "calm",
      "gradeAs": "illumination"
    },
    {
      "intensityMultiplier": 0.37,
      "aiPrompt": "DARK BACKGROUND, single thin plant stem with one closed bud at its tip rising from a tiny mound of dark rich earth floating in the lower-left corner of absolute black void, the stem rendered in muted olive-green with photorealistic cellular texture, the bud a small tight spiral of pale green and faint rose holding the memory of everything the bloom was inside its folded layers, a single dewdrop clinging to the bud tip catching faint warm prismatic light — a tiny spectrum visible in the drop, nearly the entire frame vast dark silence with only this single living form and its single drop of light, the quiet promise that what bloomed will bloom again at infinite scale, asymmetric composition with the stem small and anchored lower-left, no figures no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND, single thin plant stem with one closed bud at its tip rising from a tiny mound of dark rich earth floating in the lower-left corner of absolute black void, the stem rendered in muted olive-green with photorealistic cellular texture, the bud a small tight spiral of pale green and faint rose holding the memory of everything the bloom was inside its folded layers, a single dewdrop clinging to the bud tip catching faint warm prismatic light — a tiny spectrum visible in the drop, nearly the entire frame vast dark silence with only this single living form and its single drop of light, the quiet promise that what bloomed will bloom again at infinite scale, asymmetric composition with the stem small and anchored lower-left, no figures no text no signatures no watermarks no letters no writing",
        "extreme macro — the dewdrop on the bud tip at closest range, a tiny living spectrum inside it, the folded petals a soft green-rose spiral behind the glass, no text no signatures no watermarks no letters no writing",
        "wide — the small stem and its bud alone in vast dark from further back, the single point of prismatic light the only color in the silence, no text no signatures no watermarks no letters no writing"
      ],
      "guidancePhrases": [
        "you bloomed...",
        "the spring is in you now..."
      ],
      "analysisRole": "last",
      "gradeAs": "integration"
    }
  ],
  "inferno": [
    {
      "intensityMultiplier": 0.9,
      "aiPrompt": "DARK BACKGROUND — a single small shard of black volcanic glass floating alone in the lower right of immense blackness, one hairline seam of deep orange heat glowing inside it, its obsidian edges catching a faint rim of light, a few ash motes hanging weightless beside it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — a single small shard of black volcanic glass floating alone in the lower right of immense blackness, one hairline seam of deep orange heat glowing inside it, its obsidian edges catching a faint rim of light, a few ash motes hanging weightless beside it, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — the hairline seam inside the volcanic glass shard at closest range, white-hot light breathing through the fracture from deep within, its razor edge dusted with fine grey ash, heat shimmer rising off it in slow ripples, black glass mirroring the glow, the camera pushing in toward the light, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "cosmic — pulling back as the first sparks escape the shard and scatter upward across infinite black, the glowing fragment now a tiny ember among drifting motes of orange light, ash particles trailing into vast empty darkness above and left, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "gradeAs": "threshold",
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 1,
      "aiPrompt": "from high above, looking straight down at an immense ember network spread across black far below, fractal fire threads branching between white-hot nodes like a dying star's skeleton, the network clustered in the lower right, the camera descending toward it through drifting ash, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "from high above, looking straight down at an immense ember network spread across black far below, fractal fire threads branching between white-hot nodes like a dying star's skeleton, the network clustered in the lower right, the camera descending toward it through drifting ash, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "PURE WHITE BACKGROUND — abstract — a designed lattice of black volcanic glass sweeping diagonally from the upper left across a brilliant pale ash-white ground, obsidian planes holding deep orange fire inside them, white-hot edges, scattered dark ash particles drifting down into vast open white space below, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — one curl of black smoke at closest range, lit from beneath by hidden orange fire, its folds turning slowly like heavy velvet, embers glinting inside the curl, the smoke unfurling upward out of the lower left into empty darkness, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "gradeAs": "expansion",
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 1.25,
      "aiPrompt": "cosmic — a black sun of fire burning in the upper right of infinite darkness, its corona a fractal crown of white-hot streamers and deep crimson flares lashing outward, ash and sparks wheeling around it like a galaxy, the camera plunging toward it, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — a black sun of fire burning in the upper right of infinite darkness, its corona a fractal crown of white-hot streamers and deep crimson flares lashing outward, ash and sparks wheeling around it like a galaxy, the camera plunging toward it, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "abstract — a vast fractal fire network sweeping in a descending spiral arc across black, white-hot nodes pulsing at every intersection, amber light coursing through interlinked ember threads, the spiral core low in the left third, burning streamers dissolving into ash trails and open dark, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — a single droplet of molten fire falling through black at closest range in the upper left third, its skin crawling with white-hot light and dark cooling crust, sparks shearing off its trailing edge in a curving wake, heat shimmer bending the darkness around it, menacing and alive, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "gradeAs": "transcendence",
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 1,
      "aiPrompt": "DARK BACKGROUND — a single small coal glowing deep orange in the lower left of vast black silence, its light swelling and dimming like slow breath, one thin ribbon of grey smoke rising from it and dissolving into the dark, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "DARK BACKGROUND — a single small coal glowing deep orange in the lower left of vast black silence, its light swelling and dimming like slow breath, one thin ribbon of grey smoke rising from it and dissolving into the dark, nearly the entire frame empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "PURE WHITE BACKGROUND — looking straight down into a boundless ash-white haze, fine dark ash particles falling slowly through the pale light toward the camera, two or three still carrying a faint orange core, immense open white space, weightless and still, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — the skin of one coal at closest range, gold light breathing slowly through a lace of white ash, the pulse slow as sleep, tiny sparks lifting off its cracks and drifting into the dark, the glow gathered to the right edge of the frame, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "gradeAs": "integration",
      "sparse": true,
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.9,
      "aiPrompt": "abstract — a connected ember lattice arcing up from the lower left across deep charcoal darkness, prismatic heat threading through it from orange to amber to rose to cool silver, ash particles drifting upward into open space above, the camera rising through, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "abstract — a connected ember lattice arcing up from the lower left across deep charcoal darkness, prismatic heat threading through it from orange to amber to rose to cool silver, ash particles drifting upward into open space above, the camera rising through, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "close — a single rising spark cooling from gold to silver as it climbs through the dark in the right third of the frame, a faint curving trail of light behind it, fine ash motes turning slowly around it, cool grey-blue air opening above, everything beyond soft and empty, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "cosmic — a dim eclipsed sun of copper and rose hanging in the upper left of deep charcoal space, its fire banked to a thin glowing rim, streams of cooling sparks and ash rising past it into infinite darkness, the menace gone out of the fire, the camera drifting upward beside them, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "gradeAs": "return",
      "shaderOwned": true
    },
    {
      "intensityMultiplier": 0.75,
      "aiPrompt": "cosmic — sparse ash particles and fading ember traces drifting across vast cool grey-black silence, the last connected fire forms clustered small in the lower left, dissolving into scattered sparks that trail diagonally toward infinite upper darkness, the particles carrying the fire's memory as they cool, almost nothing against everything, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
      "aiPromptSequence": [
        "cosmic — sparse ash particles and fading ember traces drifting across vast cool grey-black silence, the last connected fire forms clustered small in the lower left, dissolving into scattered sparks that trail diagonally toward infinite upper darkness, the particles carrying the fire's memory as they cool, almost nothing against everything, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "extreme macro — one flake of charcoal ash drifting at closest range in the lower right, its lace edge still holding the faintest orange core, the last living coal of the whole descent, a few cinder motes suspended weightless beside it in cool grey dark, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing",
        "DARK BACKGROUND — a single small shard of black volcanic glass resting in the lower right of vast cool darkness, its hairline seam cooled to a faint silver-rose glow, one ash mote settling beside it, nearly the entire frame empty, the bookend of the first light, asymmetric composition with generous dark negative space, completely uninhabited, no text no signatures no watermarks no letters no writing"
      ],
      "gradeAs": "integration",
      "shaderOwned": true
    }
  ]
};
