import type { Journey, JourneyPhase } from "./types";
import { getRealm } from "./realms";

// Default phase arc — can be overridden per journey
function defaultPhases(
  overrides: Partial<Record<string, Partial<JourneyPhase>>>
): JourneyPhase[] {
  const realm = overrides._realm as unknown as string | undefined;
  const realmData = realm ? getRealm(realm) : undefined;

  const defaults: JourneyPhase[] = [
    {
      id: "threshold",
      start: 0.0,
      end: 0.15,
      shaderModes: realmData?.shaderModes.slice(0, 2) ?? ["ethereal", "sacred"],
      shaderOpacity: 0.9,
      aiPrompt: "subtle darkness with faint emerging forms",
      aiPromptModifiers: {
        lowAmplitude: "near silence, barely visible",
      },
      denoisingRange: [0.3, 0.5],
      targetFps: 0.5,
      bloomIntensity: 0.1,
      chromaticAberration: 0.0,
      colorTemperature: 0,
      vignette: 0.35,
      voice: realmData?.defaultVoice ?? "shimmer",
      poetryMood: realmData?.poetryMood ?? "flowing",
      guidancePhrases: ["breathe...", "close your eyes...", "let the sound find you..."],
      poetryIntervalSeconds: 8,
      intensityMultiplier: 0.4,
      palette: realmData?.palette ?? { primary: "#0a0a0a", secondary: "#1a1a1a", accent: "#666", glow: "#888" },
      ambientLayers: { wind: 0.1, rain: 0, drone: 0.2, chime: 0, fire: 0 },
      filmGrain: 0.03,
      particleDensity: 0.02,
      halation: 0.02,
    },
    {
      id: "expansion",
      start: 0.15,
      end: 0.35,
      shaderModes: realmData?.shaderModes.slice(0, 3) ?? ["sacred", "fractal", "ethereal"],
      shaderOpacity: 0.7,
      aiPrompt: "forms emerging, energy building, geometry revealing itself",
      aiPromptModifiers: {
        highBass: "pulsing, throbbing, massive",
        highTreble: "crystalline, sharp, detailed",
      },
      denoisingRange: [0.4, 0.65],
      targetFps: 1,
      bloomIntensity: 0.3,
      chromaticAberration: 0.03,
      colorTemperature: 0.1,
      vignette: 0.25,
      voice: realmData?.defaultVoice ?? "shimmer",
      poetryMood: realmData?.poetryMood ?? "flowing",
      guidancePhrases: ["let go...", "you're rising...", "don't resist..."],
      poetryIntervalSeconds: 4,
      intensityMultiplier: 0.7,
      palette: realmData?.palette ?? { primary: "#0a0a0a", secondary: "#1a1a1a", accent: "#666", glow: "#888" },
      ambientLayers: { wind: 0.2, rain: 0.1, drone: 0.4, chime: 0.2, fire: 0 },
      filmGrain: 0.06,
      particleDensity: 0.05,
      halation: 0.04,
    },
    {
      id: "transcendence",
      start: 0.35,
      end: 0.6,
      shaderModes: realmData?.shaderModes ?? ["prismatic", "dissolution", "fractal", "sacred"],
      shaderOpacity: 0.4,
      aiPrompt: "maximum intensity, overwhelming beauty, total immersion",
      aiPromptModifiers: {
        highBass: "explosive, earth-shattering, volcanic",
        highTreble: "shattering, prismatic, infinitely detailed",
        highAmplitude: "everything at once, sensory overload",
      },
      denoisingRange: [0.6, 0.85],
      targetFps: 2,
      bloomIntensity: 0.7,
      chromaticAberration: 0.08,
      colorTemperature: 0.3,
      vignette: 0.15,
      voice: realmData?.defaultVoice ?? "shimmer",
      poetryMood: realmData?.poetryMood ?? "flowing",
      guidancePhrases: ["you are here...", "surrender...", "become..."],
      poetryIntervalSeconds: 2,
      intensityMultiplier: 1.0,
      palette: realmData?.palette ?? { primary: "#0a0a0a", secondary: "#1a1a1a", accent: "#666", glow: "#888" },
      ambientLayers: { wind: 0.4, rain: 0.3, drone: 0.8, chime: 0.5, fire: 0.1 },
      filmGrain: 0.1,
      particleDensity: 0.08,
      halation: 0.08,
    },
    {
      id: "illumination",
      start: 0.6,
      end: 0.8,
      shaderModes: realmData?.shaderModes.slice(1, 4) ?? ["sacred", "astral", "ethereal"],
      shaderOpacity: 0.55,
      aiPrompt: "clarity after intensity, insight, expanded awareness",
      aiPromptModifiers: {
        highTreble: "crystalline clarity, infinite resolution",
      },
      denoisingRange: [0.4, 0.6],
      targetFps: 1,
      bloomIntensity: 0.4,
      chromaticAberration: 0.04,
      colorTemperature: 0.1,
      vignette: 0.3,
      voice: realmData?.defaultVoice ?? "shimmer",
      poetryMood: realmData?.poetryMood ?? "flowing",
      guidancePhrases: ["you see clearly now...", "stay...", "notice everything..."],
      poetryIntervalSeconds: 6,
      intensityMultiplier: 0.75,
      palette: realmData?.palette ?? { primary: "#0a0a0a", secondary: "#1a1a1a", accent: "#666", glow: "#888" },
      ambientLayers: { wind: 0.2, rain: 0.1, drone: 0.5, chime: 0.3, fire: 0 },
      filmGrain: 0.05,
      particleDensity: 0.04,
      halation: 0.05,
    },
    {
      id: "return",
      start: 0.8,
      end: 0.95,
      shaderModes: realmData?.shaderModes.slice(2, 4) ?? ["ethereal", "aurora"],
      shaderOpacity: 0.8,
      aiPrompt: "gentle descent, warmth returning, familiar forms",
      aiPromptModifiers: {
        lowAmplitude: "soft, fading, gentle",
      },
      denoisingRange: [0.25, 0.45],
      targetFps: 0.5,
      bloomIntensity: 0.2,
      chromaticAberration: 0.05,
      colorTemperature: -0.1,
      vignette: 0.3,
      voice: realmData?.defaultVoice ?? "shimmer",
      poetryMood: realmData?.poetryMood ?? "flowing",
      guidancePhrases: ["slowly now...", "the warmth returns...", "remember this feeling..."],
      poetryIntervalSeconds: 8,
      intensityMultiplier: 0.5,
      palette: realmData?.palette ?? { primary: "#0a0a0a", secondary: "#1a1a1a", accent: "#666", glow: "#888" },
      ambientLayers: { wind: 0.15, rain: 0.05, drone: 0.3, chime: 0.1, fire: 0 },
      filmGrain: 0.03,
      particleDensity: 0.02,
      halation: 0.03,
    },
    {
      id: "integration",
      start: 0.95,
      end: 1.0,
      shaderModes: realmData?.shaderModes.slice(0, 1) ?? ["ethereal"],
      shaderOpacity: 0.95,
      aiPrompt: "peace, stillness, a single point of light",
      aiPromptModifiers: {
        lowAmplitude: "silence, almost nothing, peace",
      },
      denoisingRange: [0.2, 0.35],
      targetFps: 0.5,
      bloomIntensity: 0.1,
      chromaticAberration: 0.0,
      colorTemperature: -0.2,
      vignette: 0.4,
      voice: realmData?.defaultVoice ?? "shimmer",
      poetryMood: realmData?.poetryMood ?? "flowing",
      guidancePhrases: ["welcome back...", "you are changed...", "carry this with you..."],
      poetryIntervalSeconds: 12,
      intensityMultiplier: 0.3,
      palette: realmData?.palette ?? { primary: "#0a0a0a", secondary: "#1a1a1a", accent: "#666", glow: "#888" },
      ambientLayers: { wind: 0.05, rain: 0, drone: 0.1, chime: 0.05, fire: 0 },
      filmGrain: 0.02,
      particleDensity: 0.01,
      halation: 0.01,
    },
  ];

  // Apply per-phase overrides
  return defaults.map((phase) => {
    const override = overrides[phase.id];
    if (!override) return phase;
    return { ...phase, ...override } as JourneyPhase;
  });
}

export const JOURNEYS: Journey[] = [
  {
    id: "the-ascension",
    name: "The Ascension",
    subtitle: "rise through golden light",
    description:
      "Warm light builds to golden geometry, dissolves into white brilliance, then returns to amber warmth.",
    realmId: "heaven",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "heaven" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "faint warm glow in darkness, a single point of golden light emerging",
        guidancePhrases: ["breathe...", "feel the warmth...", "light is coming..."],
        poetryMood: "dreamy",
      },
      expansion: {
        aiPrompt: "golden geometry expanding, cathedral light shafts, marble dissolving into radiance",
        guidancePhrases: ["rise...", "the light knows you...", "open..."],
        poetryMood: "transcendent",
      },
      transcendence: {
        aiPrompt: "total golden dissolution, pure white light, sacred geometry exploding into infinite warmth",
        guidancePhrases: ["you are light...", "there is no boundary...", "this is home..."],
        poetryMood: "transcendent",
        shaderModes: ["astral", "sacred", "ethereal", "aurora"],
      },
      illumination: {
        aiPrompt: "golden ratio spirals in warm light, peaceful cathedral spaces, floating in amber",
        guidancePhrases: ["see how vast you are...", "every direction is warmth...", "stay in this light..."],
        poetryMood: "transcendent",
      },
      return: {
        aiPrompt: "light softening to amber, warm shadows returning, gentle golden dusk",
        guidancePhrases: ["gently now...", "the glow remains...", "carry the warmth..."],
        poetryMood: "flowing",
      },
      integration: {
        aiPrompt: "single candle flame in vast darkness, warm afterglow, peace",
        guidancePhrases: ["you are changed...", "the light lives in you now..."],
        poetryMood: "flowing",
      },
    }),
  },
  {
    id: "inferno",
    name: "Inferno",
    subtitle: "the descent into judgement",
    description:
      "Darkness cracks to reveal infinite fire below. You descend through circles of the damned, face the leviathan at the bottom, and claw your way back through ash.",
    realmId: "hell",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "hell" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "absolute darkness with faint red glow from impossibly far below, the edge of an infinite pit",
        guidancePhrases: ["descend...", "there is no turning back...", "the pit has no bottom..."],
        poetryMood: "mystical",
        voice: "onyx",
      },
      expansion: {
        aiPrompt: "falling through infinite darkness, demonic forms emerging from shadow, fire growing closer but never arriving, Bosch nightmare landscape unfolding",
        guidancePhrases: ["deeper...", "they are watching...", "the judgement begins..."],
        poetryMood: "intense",
        voice: "onyx",
      },
      transcendence: {
        aiPrompt: "infinite lake of fire, towering demons silhouetted against burning sky, the Last Judgement at maximum scale, writhing damned falling into infinite depth, leviathan rising",
        guidancePhrases: ["the judgement is here...", "there is no mercy...", "witness..."],
        poetryMood: "chaotic",
        voice: "onyx",
        shaderModes: ["inferno", "chasm", "crypt", "obsidian"],
      },
      illumination: {
        aiPrompt: "the aftermath of judgement, smoldering infinite wasteland, charred ground stretching to every horizon, dark clarity",
        guidancePhrases: ["see what survives the fire...", "even here there is truth...", "the ashes speak..."],
        poetryMood: "intense",
        voice: "onyx",
      },
      return: {
        aiPrompt: "climbing upward through ash and darkness, faint light above impossibly far away, the pit receding below",
        guidancePhrases: ["climb...", "the surface remembers you...", "leave the fire behind..."],
        poetryMood: "mystical",
        voice: "onyx",
      },
      integration: {
        aiPrompt: "emerging from darkness into cold air, the pit sealed behind, a single wisp of smoke rising from scarred ground",
        guidancePhrases: ["you survived the judgement...", "the fire marked you..."],
        poetryMood: "flowing",
        voice: "onyx",
      },
    }),
  },
  {
    id: "mycelium-dream",
    name: "Mycelium Dream",
    subtitle: "the network awakens",
    description:
      "Phosphorescent dots connect into growing networks, exploding into a fractal jungle, then condensing to a single spore.",
    realmId: "garden",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "garden" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "single phosphorescent dot in rich darkness, bioluminescent spore",
        guidancePhrases: ["the spores are waking...", "feel the soil...", "life begins small..."],
        poetryMood: "mystical",
      },
      expansion: {
        aiPrompt: "mycelium networks growing visibly, bioluminescent threads connecting, fractals emerging from soil",
        guidancePhrases: ["it's growing...", "everything connects...", "feel the network..."],
        poetryMood: "mystical",
      },
      transcendence: {
        aiPrompt: "full bioluminescent fractal jungle, overwhelming organic complexity, living sacred geometry",
        guidancePhrases: ["you are the network...", "all is one organism...", "breathe with the forest..."],
        poetryMood: "transcendent",
        shaderModes: ["mycelium", "sacred", "liquid", "ethereal"],
      },
      illumination: {
        aiPrompt: "jungle breathing in rhythm, flowers made of mathematics, peaceful organic intelligence",
        guidancePhrases: ["the garden knows you...", "every leaf is aware...", "this intelligence is ancient..."],
        poetryMood: "mystical",
      },
      return: {
        aiPrompt: "bioluminescence softening, gentle phosphorescent dots, network becoming subtle",
        guidancePhrases: ["the forest settles...", "roots remember...", "return to soil..."],
        poetryMood: "flowing",
      },
      integration: {
        aiPrompt: "single glowing spore drifting in soft darkness, holding all the network's memory",
        guidancePhrases: ["one spore holds everything...", "you carry the forest..."],
        poetryMood: "flowing",
      },
    }),
  },
  {
    id: "abyssal-dive",
    name: "Abyssal Dive",
    subtitle: "into the deep",
    description:
      "Surface shimmer gives way to bioluminescent layers, a leviathan encounter at maximum depth, then a warming ascent.",
    realmId: "ocean",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "ocean" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "ocean surface from below, dancing caustic light patterns, sun filtering through water",
        guidancePhrases: ["sink...", "let the water hold you...", "trust the depth..."],
        poetryMood: "flowing",
      },
      expansion: {
        aiPrompt: "descending through bioluminescent layers, jellyfish trailing light, pressure increasing beautifully",
        guidancePhrases: ["deeper...", "the light changes here...", "pressure becomes peace..."],
        poetryMood: "dreamy",
      },
      transcendence: {
        aiPrompt: "leviathan in the abyss, overwhelming bioluminescent display, deep sea creatures of impossible beauty",
        guidancePhrases: ["the deep sees you...", "you are weightless...", "become the ocean..."],
        poetryMood: "mystical",
        shaderModes: ["liquid", "cosmos", "void", "ethereal"],
      },
      illumination: {
        aiPrompt: "deep ocean floor, peaceful darkness with scattered bioluminescence, ancient silence",
        guidancePhrases: ["the bottom is quiet...", "listen to the deep...", "ancient water holds ancient truth..."],
        poetryMood: "flowing",
      },
      return: {
        aiPrompt: "ascending through warming layers, light increasing from above, buoyant rise",
        guidancePhrases: ["rise gently...", "the surface remembers you...", "warmth returns..."],
        poetryMood: "dreamy",
      },
      integration: {
        aiPrompt: "breaking the surface into warm light, gentle waves, sky reflected in calm water",
        guidancePhrases: ["you've surfaced...", "the depth stays with you..."],
        poetryMood: "flowing",
      },
    }),
  },
  {
    id: "neural-link",
    name: "Neural Link",
    subtitle: "jack into the machine",
    description:
      "Static flickers build to data streams, consciousness merges with the network, then fades to a blinking cursor.",
    realmId: "machine",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "machine" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "static flickers, scan lines, a terminal cursor blinking in darkness",
        guidancePhrases: ["connecting...", "signal detected...", "initializing..."],
        poetryMood: "hypnotic",
        voice: "echo",
      },
      expansion: {
        aiPrompt: "data streams accelerating, circuit patterns revealing themselves, digital architecture forming",
        guidancePhrases: ["uploading...", "bandwidth expanding...", "feel the data..."],
        poetryMood: "chaotic",
        voice: "echo",
      },
      transcendence: {
        aiPrompt: "total neural network immersion, consciousness dissolving into the machine, digital transcendence",
        guidancePhrases: ["you are the network...", "every node is you...", "process everything..."],
        poetryMood: "chaotic",
        voice: "echo",
        shaderModes: ["neon", "tesseract", "warp", "fractal"],
      },
      illumination: {
        aiPrompt: "inside the machine mind, peaceful computational space, data as landscape",
        guidancePhrases: ["the machine dreams too...", "silicon and carbon are the same...", "pure logic, pure beauty..."],
        poetryMood: "hypnotic",
        voice: "echo",
      },
      return: {
        aiPrompt: "data streams slowing, signals fading, returning to a single point of light",
        guidancePhrases: ["disconnecting...", "saving state...", "you carry the data..."],
        poetryMood: "dreamy",
        voice: "echo",
      },
      integration: {
        aiPrompt: "a single blinking cursor in vast darkness, gentle static, peace after computation",
        guidancePhrases: ["link closed...", "the machine remembers you..."],
        poetryMood: "flowing",
        voice: "echo",
      },
    }),
  },
  {
    id: "dissolution",
    name: "Dissolution",
    subtitle: "dissolve into everything",
    description:
      "Silence and dark give way to the self dissolving, absolute nothing at the center, then rebirth through starlight.",
    realmId: "void",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "void" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "almost nothing, absolute darkness, the faintest suggestion of form",
        guidancePhrases: ["let go of your name...", "there is nothing to hold...", "be still..."],
        poetryMood: "mystical",
        voice: "alloy",
      },
      expansion: {
        aiPrompt: "self fragmenting into particles, identity dissolving, boundaries becoming transparent",
        guidancePhrases: ["you are dissolving...", "this is not loss...", "let the edges go..."],
        poetryMood: "mystical",
        voice: "alloy",
      },
      transcendence: {
        aiPrompt: "absolute void, formless awareness, the space before creation, pure potential energy",
        guidancePhrases: ["there is no you...", "everything is this...", "..."],
        poetryMood: "transcendent",
        voice: "alloy",
        shaderModes: ["void", "dissolution", "prismatic", "cosmos"],
        shaderOpacity: 0.2,
      },
      illumination: {
        aiPrompt: "first forms appearing from void, starlight emerging, gentle rebirth of awareness",
        guidancePhrases: ["something stirs...", "light returns...", "you are being born again..."],
        poetryMood: "mystical",
        voice: "alloy",
      },
      return: {
        aiPrompt: "stars forming a gentle canopy, sense of self returning softly, peace after dissolution",
        guidancePhrases: ["welcome back...", "you are new...", "the void gave you something..."],
        poetryMood: "flowing",
        voice: "alloy",
      },
      integration: {
        aiPrompt: "single point of starlight, vast peaceful darkness, a new self in an old body",
        guidancePhrases: ["reborn...", "carry the void gently..."],
        poetryMood: "flowing",
        voice: "alloy",
      },
    }),
  },
  {
    id: "sacred-resonance",
    name: "Sacred Resonance",
    subtitle: "geometry reveals itself",
    description:
      "A candle flicker grows to reveal hidden geometry, expanding into infinite mandalas, returning to warm stone silence.",
    realmId: "temple",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "temple" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "single candle flame in ancient darkness, stone walls barely visible",
        guidancePhrases: ["enter the temple...", "the stones are listening...", "breathe with the ancients..."],
        poetryMood: "mystical",
        voice: "fable",
      },
      expansion: {
        aiPrompt: "candlelight revealing sacred geometry in stone, patterns emerging from architecture",
        guidancePhrases: ["the geometry reveals itself...", "every angle is intentional...", "feel the golden ratio..."],
        poetryMood: "transcendent",
        voice: "fable",
      },
      transcendence: {
        aiPrompt: "infinite mandala in three dimensions, sacred geometry exploding with mathematical beauty, temple of pure form",
        guidancePhrases: ["the temple is infinite...", "you are the geometry...", "every ratio is divine..."],
        poetryMood: "transcendent",
        voice: "fable",
        shaderModes: ["sacred", "mandala", "tesseract", "astral"],
      },
      illumination: {
        aiPrompt: "golden ratio spirals in warm stone light, peaceful temple interior, mathematical harmony visible",
        guidancePhrases: ["the geometry holds you...", "this order is love...", "math is the language of the sacred..."],
        poetryMood: "transcendent",
        voice: "fable",
      },
      return: {
        aiPrompt: "geometry simplifying, warm stone surfaces, incense smoke in gentle spirals",
        guidancePhrases: ["the temple settles...", "stone remembers...", "carry the ratio..."],
        poetryMood: "mystical",
        voice: "fable",
      },
      integration: {
        aiPrompt: "single candle in a stone chamber, warm silence, mathematical peace",
        guidancePhrases: ["the temple is always here...", "the geometry lives in you..."],
        poetryMood: "flowing",
        voice: "fable",
      },
    }),
  },
  {
    id: "cosmic-drift",
    name: "Cosmic Drift",
    subtitle: "between the stars",
    description:
      "A star field expands to nebulae forming, builds to a supernova, then settles into quiet interstellar drift.",
    realmId: "cosmos",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "cosmos" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "distant star field, pinpoints of light in vast darkness, gentle cosmic drift",
        guidancePhrases: ["look up...", "the stars are ancient light...", "you are moving without moving..."],
        poetryMood: "dreamy",
        voice: "fable",
      },
      expansion: {
        aiPrompt: "nebulae forming from cosmic dust, gas clouds in impossible colors, star nurseries igniting",
        guidancePhrases: ["stars are being born...", "creation is happening now...", "feel the scale..."],
        poetryMood: "dreamy",
        voice: "fable",
      },
      transcendence: {
        aiPrompt: "supernova explosion, star death and rebirth, overwhelming cosmic light, nebula in full bloom",
        guidancePhrases: ["witness the supernova...", "death is creation...", "you are stardust remembering..."],
        poetryMood: "transcendent",
        voice: "fable",
        shaderModes: ["cosmos", "astral", "void", "warp"],
      },
      illumination: {
        aiPrompt: "supernova remnant expanding beautifully, new elements being forged, cosmic aftermath",
        guidancePhrases: ["everything came from this...", "your atoms were forged in stars...", "cosmic recycling..."],
        poetryMood: "dreamy",
        voice: "fable",
      },
      return: {
        aiPrompt: "new stars forming from the remnant, gentle nebula glow, cosmic peace",
        guidancePhrases: ["the universe settles...", "new light from old death...", "drift now..."],
        poetryMood: "flowing",
        voice: "fable",
      },
      integration: {
        aiPrompt: "quiet star field, gentle drift between galaxies, vast peaceful silence",
        guidancePhrases: ["you are the cosmos looking at itself...", "drift home..."],
        poetryMood: "flowing",
        voice: "fable",
      },
    }),
  },
  {
    id: "the-maze",
    name: "The Maze",
    subtitle: "lost in infinite corridors",
    description:
      "Identical corridors multiply endlessly. You become beautifully lost, find the center that is also the edge, and accept that the path IS the destination.",
    realmId: "labyrinth",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "labyrinth" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "a single stone corridor stretching into darkness, torchlight dying in infinite distance",
        guidancePhrases: ["enter...", "every direction is the same...", "the walls are listening..."],
        poetryMood: "hypnotic",
      },
      expansion: {
        aiPrompt: "corridors branching and multiplying, Piranesi staircases ascending into impossible darkness, mirrored passages reflecting infinity",
        guidancePhrases: ["you are lost...", "this is where you belong...", "deeper into the maze..."],
        poetryMood: "hypnotic",
      },
      transcendence: {
        aiPrompt: "infinite regression of identical passages, the labyrinth IS the mind, Borges library of every possibility, overwhelmingly beautiful lostness",
        guidancePhrases: ["you are the labyrinth...", "there is no exit because there is no inside...", "the center is everywhere..."],
        poetryMood: "mystical",
        shaderModes: ["void", "temple", "crypt", "lattice"],
      },
      illumination: {
        aiPrompt: "the center of the maze is a vast open space, the corridors visible from above like sacred geometry, infinite pattern with infinite meaning",
        guidancePhrases: ["the pattern reveals itself...", "you were never lost...", "the maze is the map of your mind..."],
        poetryMood: "mystical",
      },
      return: {
        aiPrompt: "corridors simplifying, torchlight returning, the path becoming clearer as it becomes fewer",
        guidancePhrases: ["the walls are thinning...", "you chose a direction and it is right...", "the path appears..."],
        poetryMood: "flowing",
      },
      integration: {
        aiPrompt: "a single doorway in warm stone, the infinite corridors behind you folded into memory",
        guidancePhrases: ["you carry the maze...", "the labyrinth lives in you..."],
        poetryMood: "flowing",
      },
    }),
  },
  {
    id: "the-ascent",
    name: "The Ascent",
    subtitle: "climbing into thin air",
    description:
      "The infinite ridge rises through cloud layers. You climb past the last trees, past the snow line, past the atmosphere itself, and return with the view.",
    realmId: "mountain",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "mountain" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "base of infinite mountain, forest thinning, the peak invisible in clouds impossibly far above",
        guidancePhrases: ["look up...", "the summit is a rumor...", "begin..."],
        poetryMood: "flowing",
        voice: "fable",
      },
      expansion: {
        aiPrompt: "climbing through cloud layers, the world falling away below, each step revealing more mountain above, peaks behind peaks",
        guidancePhrases: ["higher...", "the air thins and thoughts clarify...", "don't look down..."],
        poetryMood: "transcendent",
        voice: "fable",
      },
      transcendence: {
        aiPrompt: "above the clouds on infinite ridge, the earth curving away in every direction, the sky darkening toward space, infinite height with no summit",
        guidancePhrases: ["you are above everything...", "the summit is a feeling not a place...", "breathe the infinite..."],
        poetryMood: "transcendent",
        voice: "fable",
        shaderModes: ["astral", "fog", "horizon", "expanse"],
      },
      illumination: {
        aiPrompt: "standing on the ridge above clouds, infinite vista in every direction, the silence of extreme altitude, stars visible in daylight",
        guidancePhrases: ["see how far you've come...", "the view is the reward...", "everything is below you..."],
        poetryMood: "transcendent",
        voice: "fable",
      },
      return: {
        aiPrompt: "descending through warming air, clouds embracing you, the world growing larger and closer",
        guidancePhrases: ["descend gently...", "the mountain stays...", "carry the height..."],
        poetryMood: "flowing",
        voice: "fable",
      },
      integration: {
        aiPrompt: "back among trees, the mountain above hidden in clouds, the memory of infinite height in your bones",
        guidancePhrases: ["you climbed...", "the summit lives in you now..."],
        poetryMood: "flowing",
        voice: "fable",
      },
    }),
  },
  {
    id: "the-crossing",
    name: "The Crossing",
    subtitle: "walking into infinite light",
    description:
      "The desert stretches forever. You walk toward a horizon that never arrives, dissolve into heat and light, and emerge changed by the emptiness.",
    realmId: "desert",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "desert" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "edge of infinite desert, last shadow before endless sand, the horizon shimmering with heat",
        guidancePhrases: ["step into the light...", "leave everything behind...", "the desert has no mercy and no malice..."],
        poetryMood: "mystical",
        voice: "nova",
      },
      expansion: {
        aiPrompt: "walking through infinite dunes, mirages shimmering at unreachable distance, heat dissolving all landmarks, sand ocean",
        guidancePhrases: ["the horizon retreats...", "emptiness is freedom...", "the sand knows your footsteps..."],
        poetryMood: "mystical",
        voice: "nova",
      },
      transcendence: {
        aiPrompt: "total dissolution into light and heat, the self evaporating into infinite empty space, desert as absolute consciousness, every grain of sand a universe",
        guidancePhrases: ["you are the desert...", "emptiness is fullness...", "the light is everything..."],
        poetryMood: "transcendent",
        voice: "nova",
        shaderModes: ["horizon", "dusk", "expanse", "umbra"],
      },
      illumination: {
        aiPrompt: "night falling on infinite desert, infinite stars appearing, the Milky Way as a river of ancient light from horizon to horizon",
        guidancePhrases: ["the stars emerge...", "the desert and the sky are the same infinity...", "silence speaks..."],
        poetryMood: "dreamy",
        voice: "nova",
      },
      return: {
        aiPrompt: "first light on sand, long shadows returning, the edge of the desert becoming visible",
        guidancePhrases: ["the crossing nears its end...", "you survived the emptiness...", "the desert marked you..."],
        poetryMood: "flowing",
        voice: "nova",
      },
      integration: {
        aiPrompt: "standing at the desert's edge looking back at infinite sand, changed by the emptiness, carrying the silence",
        guidancePhrases: ["you crossed the infinite...", "the emptiness lives in you now..."],
        poetryMood: "flowing",
        voice: "nova",
      },
    }),
  },
  {
    id: "the-reading",
    name: "The Reading",
    subtitle: "lost among infinite pages",
    description:
      "You enter the infinite library and begin reading. The books contain everything ever thought. You find the book that contains you, and close it gently.",
    realmId: "archive",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "archive" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "single reading lamp in vast darkness, shelves receding into infinite shadow, the smell of ancient paper",
        guidancePhrases: ["open the first page...", "the library has been waiting...", "every book knows your name..."],
        poetryMood: "dreamy",
        voice: "fable",
      },
      expansion: {
        aiPrompt: "shelves multiplying infinitely, hexagonal rooms of the Library of Babel, pages turning themselves, text resolving into deeper text",
        guidancePhrases: ["the library unfolds...", "every thought ever thought is here...", "read deeper..."],
        poetryMood: "dreamy",
        voice: "fable",
      },
      transcendence: {
        aiPrompt: "total immersion in infinite text, consciousness dissolving into the library, the book that contains all other books, recursive knowledge at infinite depth",
        guidancePhrases: ["you are the text...", "reading and being read are the same...", "infinite knowledge, infinite peace..."],
        poetryMood: "mystical",
        voice: "fable",
        shaderModes: ["temple", "lattice", "prophecy", "fog"],
      },
      illumination: {
        aiPrompt: "you find the book that contains your own story, reading yourself being read, the library as mirror of consciousness",
        guidancePhrases: ["you found your book...", "the text is you...", "the library is your mind..."],
        poetryMood: "mystical",
        voice: "fable",
      },
      return: {
        aiPrompt: "closing the book gently, shelves simplifying, the reading lamp growing warmer, fewer books, more silence",
        guidancePhrases: ["close the book...", "the words stay with you...", "the silence after reading..."],
        poetryMood: "flowing",
        voice: "fable",
      },
      integration: {
        aiPrompt: "a single closed book on a wooden table, the reading lamp warm, the infinite library folded into the spine",
        guidancePhrases: ["the library is always open...", "you carry every book..."],
        poetryMood: "flowing",
        voice: "fable",
      },
    }),
  },
  {
    id: "the-tempest",
    name: "The Tempest",
    subtitle: "inside the infinite storm",
    description:
      "The storm builds from a distant rumble to infinite electrical fury, you find the eye of absolute calm, then emerge transformed by the lightning.",
    realmId: "storm",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "storm" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "distant thunder, dark clouds gathering at infinite horizon, the pressure dropping, electricity building",
        guidancePhrases: ["it's coming...", "feel the pressure change...", "the storm knows you..."],
        poetryMood: "intense",
        voice: "echo",
      },
      expansion: {
        aiPrompt: "lightning illuminating infinite horizons, thunder continuous and deafening, rain falling from infinite height, the storm expanding beyond comprehension",
        guidancePhrases: ["let the storm take you...", "every lightning is a thought...", "the rain is washing everything..."],
        poetryMood: "chaotic",
        voice: "echo",
      },
      transcendence: {
        aiPrompt: "inside the infinite hurricane, lightning branching into infinite forks, the storm as a living god of electricity, total sensory overwhelm, sublime terror becoming ecstasy",
        guidancePhrases: ["you are the lightning...", "the storm is alive and you are it...", "infinite power..."],
        poetryMood: "chaotic",
        voice: "echo",
        shaderModes: ["storm", "plasma", "chasm", "wraith"],
      },
      illumination: {
        aiPrompt: "the eye of the hurricane, perfect calm surrounded by infinite rotating walls of cloud, blue sky visible above, absolute stillness in the center of infinite force",
        guidancePhrases: ["the eye...", "perfect calm inside infinite fury...", "the center holds..."],
        poetryMood: "mystical",
        voice: "echo",
      },
      return: {
        aiPrompt: "the storm passing, rain softening, lightning becoming distant flickers, the sky clearing from the west",
        guidancePhrases: ["the storm passes...", "every storm ends...", "you survived the infinite..."],
        poetryMood: "flowing",
        voice: "echo",
      },
      integration: {
        aiPrompt: "calm after the storm, petrichor rising, a single distant flash on the horizon, clear sky with clean air",
        guidancePhrases: ["the air is new...", "the storm changed everything..."],
        poetryMood: "flowing",
        voice: "echo",
      },
    }),
  },
  {
    id: "first-snow",
    name: "First Snow",
    subtitle: "crystalline descent into silence",
    description:
      "The world grows quiet as the first flakes fall. Sound becomes muffled. Everything slows into crystalline stillness.",
    realmId: "winter",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "winter" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "grey sky darkening, the first single snowflake falling through still air, breath visible",
        guidancePhrases: ["the air changes...", "feel it cooling...", "something is coming..."],
        poetryMood: "melancholic",
        voice: "shimmer",
      },
      expansion: {
        aiPrompt: "snow beginning to fall steadily, the world growing quieter, trees receiving their white covering, footprints filling in",
        guidancePhrases: ["sound is softening...", "the world is changing...", "let the white take everything..."],
        poetryMood: "dreamy",
        voice: "shimmer",
      },
      transcendence: {
        aiPrompt: "total whiteout blizzard, all form dissolved into infinite swirling white, no up no down no horizon, pure crystalline chaos",
        guidancePhrases: ["you are inside the snow...", "there is only white...", "surrender to the crystal..."],
        poetryMood: "mystical",
        voice: "shimmer",
        shaderModes: ["snow", "fog", "aurora", "ethereal"],
      },
      illumination: {
        aiPrompt: "the snow stops, absolute silence, pristine untouched white landscape stretching to infinity under clearing sky, the world remade",
        guidancePhrases: ["listen to the silence...", "the world is new...", "everything is clean..."],
        poetryMood: "transcendent",
        voice: "shimmer",
      },
      return: {
        aiPrompt: "warm light from a window falling on fresh snow, the sound of a distant plow, smoke rising from chimneys, the comfort after the cold",
        guidancePhrases: ["warmth returns...", "home is near...", "the cold made this warmth possible..."],
        poetryMood: "flowing",
        voice: "shimmer",
      },
      integration: {
        aiPrompt: "starlight on new snow, absolute peace, the world transformed and still, one set of footprints leading to a warm door",
        guidancePhrases: ["the snow remembers...", "carry this stillness..."],
        poetryMood: "melancholic",
        voice: "shimmer",
      },
    }),
  },
  {
    id: "the-bloom",
    name: "The Bloom",
    subtitle: "when the earth remembers warmth",
    description:
      "After the long winter, the first warmth arrives. Seeds crack open. Green returns. The world exhales.",
    realmId: "spring",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "spring" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "frozen ground with hairline cracks, the faintest green beneath brown, ice melting at the edges, dawn light growing warmer",
        guidancePhrases: ["wait for it...", "feel the thaw beginning...", "something stirs beneath..."],
        poetryMood: "melancholic",
        voice: "nova",
      },
      expansion: {
        aiPrompt: "buds unfurling in time-lapse, streams rushing with snowmelt, birds returning, the air thick with pollen and possibility",
        guidancePhrases: ["it's happening...", "the green is unstoppable...", "everything at once..."],
        poetryMood: "dreamy",
        voice: "nova",
      },
      transcendence: {
        aiPrompt: "explosion of blossoms in every direction, cherry trees and wildflowers and new leaves, overwhelming fertility, life erupting from every surface",
        guidancePhrases: ["this is what was waiting...", "every cell remembers this...", "the bloom is you..."],
        poetryMood: "transcendent",
        voice: "nova",
        shaderModes: ["bloom", "mycelium", "liquid", "growth"],
      },
      illumination: {
        aiPrompt: "mature spring garden in full glory, bees working flowers, warm rain falling through sunlight, rainbow forming",
        guidancePhrases: ["the garden is complete...", "everything is alive...", "rest here in the green..."],
        poetryMood: "flowing",
        voice: "nova",
      },
      return: {
        aiPrompt: "evening in the garden, flowers closing for the night, fireflies beginning, the air cooling gently",
        guidancePhrases: ["the day was full...", "the garden sleeps...", "carry the pollen with you..."],
        poetryMood: "dreamy",
        voice: "nova",
      },
      integration: {
        aiPrompt: "dawn in the garden, dew on everything, one perfect flower opening to first light",
        guidancePhrases: ["you bloomed...", "the spring is in you now..."],
        poetryMood: "flowing",
        voice: "nova",
      },
    }),
  },
  {
    id: "the-solstice",
    name: "The Solstice",
    subtitle: "the longest day, the shortest night",
    description:
      "Midsummer. The sun barely sets. Heat and light fill every hour. Then the electric night arrives.",
    realmId: "summer",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "summer" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "dawn already warm, golden light hitting tall grass, the day stretching ahead infinite and golden",
        guidancePhrases: ["the sun is already here...", "feel the warmth building...", "this is the longest day..."],
        poetryMood: "flowing",
        voice: "alloy",
      },
      expansion: {
        aiPrompt: "blazing midday sun, heat shimmers above every surface, the world saturated with light and color, lazy warm wind",
        guidancePhrases: ["the heat carries you...", "let the light fill everything...", "time is slow and golden..."],
        poetryMood: "dreamy",
        voice: "alloy",
      },
      transcendence: {
        aiPrompt: "peak heat, the sun enormous overhead, prairie thunderstorm building on the horizon with anvil cloud, the air electric and charged, the tension between heat and storm",
        guidancePhrases: ["the storm is coming...", "heat and lightning...", "the fullest moment of the year..."],
        poetryMood: "intense",
        voice: "alloy",
        shaderModes: ["dusk", "ember", "storm", "prismatic"],
      },
      illumination: {
        aiPrompt: "after the storm, golden hour light painting everything amber, steam rising from wet earth, the world washed clean and warm",
        guidancePhrases: ["the storm passed...", "golden hour...", "the longest light of the year..."],
        poetryMood: "transcendent",
        voice: "alloy",
      },
      return: {
        aiPrompt: "warm summer night, fireflies mapping the darkness, stars appearing one by one, the heat still radiating from the earth",
        guidancePhrases: ["the night is warm...", "fireflies are speaking...", "the longest day ends gently..."],
        poetryMood: "flowing",
        voice: "alloy",
      },
      integration: {
        aiPrompt: "deep summer night, warm breeze carrying the scent of cut grass and flowers, the Milky Way overhead, absolute peace in warmth",
        guidancePhrases: ["summer lives in you...", "the warmth stays..."],
        poetryMood: "dreamy",
        voice: "alloy",
      },
    }),
  },
  {
    id: "the-harvest",
    name: "The Harvest",
    subtitle: "the beautiful letting go",
    description:
      "The trees release their colors. Everything that grew now lets go with grace. Beauty in the falling.",
    realmId: "autumn",
    aiEnabled: true,
    phases: defaultPhases({
      _realm: "autumn" as unknown as Partial<JourneyPhase>,
      threshold: {
        aiPrompt: "first cool morning, one leaf turning red, the light changing angle, summer's warmth fading at the edges",
        guidancePhrases: ["the change begins...", "feel the first cool...", "something is ending beautifully..."],
        poetryMood: "melancholic",
        voice: "fable",
      },
      expansion: {
        aiPrompt: "forest ablaze with color, red and gold and amber in every direction, leaves beginning to fall, the scent of woodsmoke",
        guidancePhrases: ["look at what it becomes...", "the dying is the beauty...", "every leaf is a flame..."],
        poetryMood: "mystical",
        voice: "fable",
      },
      transcendence: {
        aiPrompt: "peak color, the entire world on fire with turning leaves, wind sending cascades of gold and crimson spiraling, harvest moon rising enormous and orange above the blaze",
        guidancePhrases: ["this is the peak...", "everything releasing at once...", "let go with the leaves..."],
        poetryMood: "transcendent",
        voice: "fable",
        shaderModes: ["ember", "fog", "dissolution", "dendrite"],
      },
      illumination: {
        aiPrompt: "after peak, bare branches against clear sky, the last leaves falling slowly, the elegant bones of trees revealed",
        guidancePhrases: ["see the structure...", "what remains is essential...", "the beauty of less..."],
        poetryMood: "melancholic",
        voice: "fable",
      },
      return: {
        aiPrompt: "late autumn rain on bare branches, woodsmoke from distant chimney, the earth preparing for rest, mushrooms among fallen leaves",
        guidancePhrases: ["the earth is resting...", "rain completes it...", "nothing is lost, only changed..."],
        poetryMood: "flowing",
        voice: "fable",
      },
      integration: {
        aiPrompt: "first frost on fallen leaves, breath visible, stars sharp and close, the garden put to bed, deep quiet",
        guidancePhrases: ["winter is near...", "you carry the harvest..."],
        poetryMood: "melancholic",
        voice: "fable",
      },
    }),
  },
];

export function getJourney(id: string): Journey | undefined {
  return JOURNEYS.find((j) => j.id === id);
}

export function getJourneysByRealm(realmId: string): Journey[] {
  return JOURNEYS.filter((j) => j.realmId === realmId);
}
