/** Design notes shown behind the "Read the design notes" affordance. */
export const README_TEXT = `Somatic Echo asks one question: what if your MOVEMENT were the music, and STILLNESS were the reward? It is a drug-free somatic-meditation instrument. Slow, deliberate, present movement is met with a calm, coherent, luminous field and a warm consonant drone; agitation makes the world scatter and detune. Over a session it trains you, gently, toward bodily presence.

The input is your webcam, read as pure optical flow — no ML, no MediaPipe, no network. The video is drawn to a hidden 96x72 canvas, downsampled to an 8x6 grid, and frame-differenced each frame to yield total motion energy, a motion centre of mass, and per-cell energy. The spine of the piece is smoothness: an inverse-jerk measure that tracks how much the motion ACCELERATES frame to frame. Slow, continuous, present motion reads as smooth (toward 1); jerky, fast, agitated motion reads as unsmooth (toward 0). Stillness and smoothness are what the instrument rewards.

The sound is an additive just-intonation drone — a fundamental near 58 Hz plus JI partials [1, 9/8, 5/4, 3/2, 5/3, 15/8, 2], deliberately non-pentatonic. When you move smoothly the partials lock to their pure ratios: a warm, sustained, consonant chord. When you jerk, the partials detune into roughness and beating and a band-passed noise edge fades in — the drone gets anxious. Energy fades the upper partials in (more voices when you move, but they only sound GOOD when you are smooth); the vertical centroid tilts the spectral filter; the horizontal centroid pans the stereo field. When your energy drops low and STAYS low, a reward bloom swells: the master gain lifts, the filter opens, the consonant partials brighten — the sound resolves. Stillness is audibly the reward.

The visual substrate is ~3,300 additive THREE.Points forming a body-aura. Motion and per-cell energy scatter the points outward and spin the mandala faster; smoothness and the reward bloom pull them back into a tight, coherent, slowly-rotating mandala that warms from deep indigo through violet to gold. Point size, opacity and luminance all rise as you settle — stillness is visibly the reward too. All luminance change is slow drift, never a strobe (well under 3 Hz), and prefers-reduced-motion calms the whole field.

No camera, or permission denied? A seeded ghost mover takes over: a Lissajous "body" that moves agitatedly for ~14 seconds, then decelerates over ~8 seconds to a barely-breathing residual — so the piece self-demos the entire agitation to calm to reward arc on a phone with no camera and no input. A manual "Use demo motion" button forces the same ghost. Everything is deterministic (a mulberry32 PRNG plus performance.now(); no Math.random, Date.now, or argless new Date()).

References: Kantan, Dahl & Spaich, "The Self-Aware Body", arXiv:2606.14664 (2026) — movement-to-sound biofeedback heightens bodily self-awareness as a gateway to somatic and meditative states. "Gesture2Music", arXiv:2511.00793. Anna Halprin's movement-and-presence practice, and Eliane Radigue's sustained just-intonation drone.`;
