// readme-text.ts — the design-notes prose shown in the in-page modal.
// Kept in one place so the modal and the README stay in sync.

export const README_TEXT = `What if your body's motion dynamics composed the energy ARC of one of Karel's real piano recordings over minutes — a journey-engine where sustained, broad movement BUILDS the piece and stillness lets it recede?

Surgeline is not another instrument. The headline is the journey: a single tension envelope, earned slowly. The camera reads your seated upper body as velocity, not position. That velocity is split into a SLOW band — heavily smoothed whole-body motion energy — and a FAST band — the high-pass flicker of quick gestures. Slow energy feeds a leaky integrator: sustained broad movement fills the arc faster than it drains, so the energy keeps climbing while you keep moving, and bleeds away gently when you hold still. Minute three is a materially bigger sonic and visual space than minute zero. Fast energy never touches the long arc; it sparks momentary articulation — a brightening of the tone, a short grain tap of his own piano.

The research anchor is "Where the Body Keeps the Beat: Structured Motion Conditioning and Music Dynamics Supervision for Dance-to-Music Generation" (Dyna2Music, arXiv:2610.00726, submitted 2026-09-30). Its idea is to decompose body-joint velocities into slow and fast components and to supervise the generated music's DYNAMICS — its frame-to-frame rate of change — with them. Under the lab's absolute rule we never generate audio, so the idea is INVERTED: the same slow/fast velocity decomposition instead conducts a TRANSFORMATION of Karel's existing recording. Slow drives the slow-varying tension envelope; fast drives the fast-varying articulation.

The sound is one real buffer, layered vertically. A dry base voice plays through a lowpass that opens as the arc rises; a reverb-wet voice runs through a convolver whose impulse response is a windowed, decaying slice of the SAME buffer, so the hall is literally made of his piano; a sub voice at half speed adds weight through the middle of the journey; a shimmer voice at double speed with a high-shelf lifts the crest. Each voice's gain is a smoothstep of the arc, ramped about a second. Nothing is synthesized — no oscillators, no noise. Everything terminates at the shared safe-master bus, and the visuals are driven from its analyser.

The picture is a raw WebGL2 fragment field in a "stormglass" palette: a graphite-black ground and a deep oceanic blue-green current that builds and brightens to a pale luminous jade crest at the peak, with a thin warm-amber rimlight only near the climax. A Canvas2D path mirrors the same palette and arc if WebGL2 is missing or its context is lost.

Honest note on what could NOT be verified: there is no webcam in the build environment, so the live-camera feel — whether the slow/fast thresholds are truly comfortable for a seated person, and whether the arc reads as a satisfying multi-minute build in a real room — is reasoned-through and demo-tested, not confirmed against a human body. The autonomous demo and the pointer fallback drive the identical arc, audio and visual chain, so the pipeline is complete on load; only the ergonomics of real motion remain untested.`;
