// Design-notes prose for the in-app modal. Kept as a plain string so the page
// and the README.md tell one story.

export const README_TEXT = `Aurora Conductor asks one question: what if you could conduct Karel's OWN piano recording with your whole body — move a hand in front of the webcam and the QUANTITY OF YOUR MOTION drives the tempo and intensity of his music, no baton, no mouse?

The recording is your orchestra. Your body is the baton. Allow the camera and start any track from Karel's verified catalog. Each animation frame the webcam image is downsampled to a small grayscale grid and a dense OPTICAL FLOW field is estimated in the browser — a Lucas–Kanade-lite least-squares solve of the brightness-gradient equations over a 32×24 grid of cells. Two things come out of that field. First, the OVERALL QUANTITY OF MOTION (the mean absolute frame-difference across the image) becomes the conducted tempo: hold still and his piano slows and broadens toward a held sustain; sweep your hand and it rushes. The rate is clamped to a musical 0.4×–1.6× so it never runs away. Second, the DIRECTION FIELD of the flow bends the aurora: where your motion points, the light-curtains lean and brighten.

The magic — rushing and slowing his piano without the pitch sliding up and down like a tape machine — is real-time, pitch-preserving GRANULAR TIME-STRETCH by synchronous overlap-add. A read-head walks through his recording. Every ~45 ms of OUTPUT we emit one short grain — a ~110 ms slice of his audio played at speed 1, so its pitch is exactly his — through its own raised-cosine (Hann) envelope, and the overlapping grains sum back into continuous sound. The read-head advances at the CONDUCTED rate rather than real time, so decoupling read-head speed from the constant grain-emission rate is what lets the music stretch while the pitch stays nailed to his piano. His whole mix is routed through the shared ear-safety master bus before the speakers.

The output is a full-viewport WebGL2 AURORA CURTAIN. Several vertical light-curtains hang in a cool violet → cyan → ice palette on near-black; they are advected and bent by the measured flow field, their filaments stream faster where you move faster, and the whole sheet pulses in brightness with the tamed audio analyser and the conducted intensity. A gentle SEEDED self-demo (a mulberry32 PRNG, never Math.random) drives a soft synthetic motion oscillation so the piece is alive and sounding within a second of Start, then hands control to you the moment real motion is detected.

NAMED REFERENCE. This is the literal webcam-optical-flow realization of "Real-Time Control of a Virtual Orchestra by Recognition of Conducting Gestures" (arXiv:2604.27957, 2026) — a Swedish museum dome where visitors conduct a pre-recorded orchestra purely by camera motion, deriving tempo and expression from the overall quantity of user motion. Here that idea is turned on Karel's OWN recording: his piano is the orchestra, your body in front of the lens is the baton. It is the webcam successor to the pointer-driven conductorwell (13536); the time-stretch engine sits in the granular overlap-add lineage (PhaVoRIT; Karrer, Lee & Borchers 2006) built for exactly this "conduct a recording" problem.

HONEST LIMITATIONS. In-browser optical flow is noisy: uneven lighting, webcam auto-exposure and rolling shutter all inject phantom motion, so the quantity signal is heavily smoothed and gated with a floor before it reaches the tempo — that smoothing adds a little latency between your gesture and the music. The flow is estimated on a small downsampled grid for speed, so it reads gross body motion, not fingers. Aperture and low-texture regions make Lucas–Kanade under-determined, so direction is a soft hint rather than a precise vector field. If the camera is denied or absent, the piece falls back to POINTER motion (mouse/touch velocity as the quantity of motion) with a clear on-brand notice; if WebGL2 is missing you still hear his piano conducted by ear.

PLAY. Allow the camera and move — bigger, faster motion rushes his piano and floods the aurora; go still and it slows and holds. Pick any track from his verified catalog. No camera? Move the pointer instead.`;
