#!/usr/bin/env python3
"""Journey colour palettes FROM THE IMAGES (Karel 2026-10-06: "the particle
system has to match the color of the journey theme. so realized has a lot of
amber … you should have a color palette and key color theme per journey based
on images. this way the particle system is connected to it").

For every journey in the Tramokyo pack: sample its stills (pixels weighted by
chroma × value — black and grey barely count), cluster in RGB (k-means),
and emit a 5-colour palette + KEY colour (the most dominant chromatic
cluster) for the whole journey and for each phase (stills are allocated to
phases in order, so phase i ≈ the i-th proportional slice).

Output: src/lib/particles/journey-palettes.generated.ts
Run:    python3 scripts/extract-journey-palettes.py [phaseCounts.json]
"""
import json, os, sys, colorsys, random
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PACK = os.path.join(ROOT, "public")
idx = json.load(open(os.path.join(ROOT, "public/tramokyo-pack/local-images.json")))
phase_counts = json.load(open(sys.argv[1])) if len(sys.argv) > 1 else {}

def pixels(path):
    try:
        im = Image.open(os.path.join(PACK, path.lstrip("/"))).convert("RGB").resize((48, 48))
    except Exception:
        return []
    out = []
    for r, g, b in im.getdata():
        h, s, v = colorsys.rgb_to_hsv(r / 255, g / 255, b / 255)
        w = (s ** 1.2) * (v ** 0.8)
        if v > 0.08 and w > 0.02:
            out.append(((r / 255, g / 255, b / 255), w))
    return out

def kmeans(px, k=5, iters=12, seed=7):
    if not px:
        return []
    rnd = random.Random(seed)
    # weighted sample to keep it fast
    pts = rnd.choices(px, weights=[w for _, w in px], k=min(4000, len(px) * 2))
    cents = [p for p, _ in rnd.sample(pts, min(k, len(pts)))]
    for _ in range(iters):
        groups = [[] for _ in cents]
        for (c, _w) in pts:
            j = min(range(len(cents)), key=lambda i: sum((c[t] - cents[i][t]) ** 2 for t in range(3)))
            groups[j].append(c)
        cents = [tuple(sum(x[t] for x in g) / len(g) for t in range(3)) if g else cents[i] for i, g in enumerate(groups)]
    sizes = [0] * len(cents)
    for (c, _w) in pts:
        j = min(range(len(cents)), key=lambda i: sum((c[t] - cents[i][t]) ** 2 for t in range(3)))
        sizes[j] += 1
    return sorted(zip(cents, sizes), key=lambda x: -x[1])

def hexc(c):
    return "#%02x%02x%02x" % tuple(max(0, min(255, round(x * 255))) for x in c)

def palette_of(paths):
    px = []
    for p in paths:
        px += pixels(p)
    cl = kmeans(px)
    if not cl:
        return None
    total = sum(n for _, n in cl)
    # key = dominant AND chromatic
    def chroma(c):
        h, s, v = colorsys.rgb_to_hsv(*c)
        return s * (0.4 + 0.6 * v)
    key = max(cl, key=lambda x: (x[1] / total) * (0.25 + chroma(x[0])))[0]
    return {"key": hexc(key), "colors": [hexc(c) for c, _ in cl], "weights": [round(n / total, 3) for _, n in cl]}

out = {}
for jid, paths in sorted(idx.items()):
    if not paths:
        continue
    whole = palette_of(paths[:: max(1, len(paths) // 24)])
    if not whole:
        continue
    n = int(phase_counts.get(jid, 0))
    phases = []
    if n > 1:
        for i in range(n):
            a, b = round(i * len(paths) / n), round((i + 1) * len(paths) / n)
            sl = paths[a:b] or paths[a:a + 1]
            phases.append(palette_of(sl[:: max(1, len(sl) // 8)]) or whole)
    whole["phases"] = phases
    out[jid] = whole
    print(jid, whole["key"], whole["colors"], file=sys.stderr)

ts = ("// GENERATED by scripts/extract-journey-palettes.py — do not edit.\n"
      "// Journey colour palettes sampled from each journey's own pack stills.\n"
      "export interface ImagePalette { key: string; colors: string[]; weights: number[] }\n"
      "export const JOURNEY_IMAGE_PALETTES: Readonly<Record<string, ImagePalette & { phases: ImagePalette[] }>> = "
      + json.dumps(out, indent=1) + ";\n")
open(os.path.join(ROOT, "src/lib/particles/journey-palettes.generated.ts"), "w").write(ts)
print(f"{len(out)} journeys", file=sys.stderr)
