// Re-themes from the v2 DEEP ANALYSIS (Karel 2026-10-05: "redo based on
// analysis as needed", "no figures"). Every journey whose world or arc did
// not fit its measured music. Applied by scripts/retheme-from-analysis.mjs.
//
// Entry kinds (phases[i] = the content of phase i AFTER the re-grouping of
// the measured sections into 6 phases — scripts/lib/phase-grouping.mjs):
//  - a STRING  = a new world line for that phase (3-shot sequence built
//                with the entry's micro/abstract, lit by the phase's
//                measured role),
//  - a NUMBER  = keep the old phase k's whole beat (aiPrompt + 3-shot
//                sequence + guidance) at this position (a re-order so the
//                peak imagery lands on the music's real peak).
//  - kind "arc" = world fits; only the per-phase arc (bounds + intensity
//                from measured dynamics) is applied, beats stay in order.
// Excluded by law: Ghost, Snowflake, Realized (mastered) and the five
// Kinetic Lab journeys. Shader casts are never touched (owned by
// recast-expansion / recast-featured). No figures, no text, no ice/aurora,
// no sun/moon discs (light as glow, seams, reflections), no drug language.

const SAME = [0, 1, 2, 3, 4, 5];

export const RETHEME = {
  // ═══════════════ Expansion (Phase C) ═══════════════
  "4cd35ec2-bc13-4b9a-b26c-9e38e956fb80": {
    name: "Night Wind 2",
    measured: "68 BPM elastic rubato, C# major (minor-weight 0.11), tender/contemplative/warm, arousal 0.40, arch peaking 1:57–2:28",
    old: "a plain 'surging' in great waves under a torrent of streaming cloud",
    world: "a warm night breeze breathing over a field of tall pale grass",
    why: "Slow, tender, warm major with low arousal = wind as a breath, not a gale; the fervent plateau at 1:57 = the whole field rolling in long luminous waves, still unhurried.",
    micro: "a single grass seed-head bending in a warm night breeze, its fine hairs lit silver at the edges",
    abstract: "long soft curves of moving air drawn as faint luminous streaks through dark grass",
    phases: [
      "DARK BACKGROUND — a field of tall pale grass at night under soft overcast, almost still, one slow breath of warm air bending a narrow band of seed-heads in the lower left, their tips catching a faint silver glow",
      "slow rocking waves of air moving through the tall grass in long gentle curves, the seed-heads leaning and returning, faint silver light gliding along their tips, the night calm and warm",
      "the breeze lifting a little, loose seed-fluff rising out of the grass and drifting in slow lit trajectories, pale gold glints travelling across the field in soft waves",
      "the whole field breathing at once seen from above, long luminous waves of bending grass rolling slowly across the dark land, the air full of drifting lit seed-fluff, warm silver-gold light along every crest, the largest wave crossing the frame on a diagonal, fervent but unhurried",
      "the waves easing into long slow swells, the drifting seeds settling in gentle slants, the light softening to a warm pearl glow over the grass",
      "DARK BACKGROUND — the grass upright and quiet, one last seed drifting alone across the lower right, a faint warm glow lingering low over the field",
    ],
  },
  "85124aed-c3b4-42e2-870a-b14bc5425b72": {
    name: "Night Wind 9",
    measured: "65 BPM steady, C# major (0.08), restless-warm/yearning/buoyant, arousal 0.52; a real 'Full Gale' section 2:01–2:23 but warm, not menacing",
    old: "night gale at sea, spindrift flying off every crest",
    world: "long warm swells on an open night sea, spray lit silver-gold",
    why: "Warm major and buoyant yearning keep the sea generous; the measured gale section becomes exhilarated plumes of lit spray at the peak only, then a long ebb.",
    micro: "fine spray lifting off the crest of a dark swell, each droplet lit warm silver",
    abstract: "long luminous curves of moving water and wind-blown spray across darkness",
    phases: [
      "DARK BACKGROUND — looking down at a dark open sea at night filling the frame, long slow swells barely moving, one thread of warm silver reflected light lying across the water in the lower left",
      "the swells lengthening and lifting, a warm breeze drawing faint streaks of spray off a few crests, silver light sliding along their backs",
      "looking down at a wide open sea of long glowing swells filling the frame, warm silver and pale gold reflected light spread across the water, buoyant and expansive",
      "the night wind at its height over the open sea, great rolling swells with long luminous plumes of spray streaming off their crests in warm silver-gold arcs, cloud racing above, the brightest crest set right of center, exhilarated rather than menacing",
      "the sea easing back into long calm swells, the last spray drifting down in fine glints, the light softening",
      "DARK BACKGROUND — looking down at calm black water filling the frame, a single soft band of pale reflected light lying on the surface in the upper left",
    ],
  },
  "e4658610-336d-452f-a4f8-7b652b339db6": {
    name: "Night Wind 11",
    measured: "66 BPM steady, C# major (0.11), yearning/flowing/tender, arousal 0.50; a calm 'Clearing Sky' valley 1:16–2:23, peak 2:23–2:56",
    old: "the sky river 'at full force', a torrent of cloud",
    world: "silk-smooth ribbons of luminous cloud drawn across a night sky over dark hills",
    why: "Flowing, tender major = smooth streaming ribbons rather than a torrent; the measured clearing becomes wide open calm sky; the 'storm of suspensions' peak = the whole sky in one great smooth sweep.",
    micro: "a fine filament of cloud drawn out by wind into silky strands, its edges glowing pale gold",
    abstract: "long smooth ribbons of luminous vapour flowing in parallel across darkness",
    phases: [
      "DARK BACKGROUND — dark low hills under a night sky, one thin silver cloud streamer drawn out slowly across the upper right, the air almost still",
      "warm air rising over the hills, a few long cloud ribbons unspooling across the sky, their edges lit pale gold",
      "streamers multiplying across the sky at different heights, silver edges braiding as they pass over the dark ridges, restless and airborne",
      "the sky clearing into wide calm open dark with only a few thin luminous ribbons resting high above the hills, spacious and suspended",
      "the whole sky alive with long flowing ribbons of luminous cloud streaming in one great smooth sweep over the dark hills, silver and warm gold filaments crossing and braiding, the densest flow crossing the frame left of center, exultant yet smooth",
      "DARK BACKGROUND — the hills at rest under a quiet sky, a single fading ribbon of pale cloud lying low over the lower left",
    ],
  },
  "87009cf3-8c07-48eb-88d8-e7acb6a14e41": {
    name: "Night Wind 4",
    measured: "67 BPM steady, C# major (0.12), nocturnal/warm/restless, arousal 0.45; Lydian plateau → crest 0:44–1:43, minor eddies after",
    old: "an entire canopy 'surging' in one direction",
    world: "a night forest canopy breathing in long silver-gold ripples",
    why: "Warm restlessness at low arousal = the canopy breathes rather than surges; the minor eddies (2:08) become circling swirls with a brooding shade.",
    micro: "a cluster of leaves turning their silver undersides to the wind at night, edges catching soft light",
    abstract: "slow luminous ripples travelling across a dark textured surface of leaves",
    phases: [
      "DARK BACKGROUND — the dark crown of a single broad tree at night, a few leaves turning silver-side up in a soft first breath of wind, deep darkness all around",
      "waves of moving leaves rolling gently through a night canopy seen from above, silver undersides flashing in soft streaks, warm air rising",
      "a top-down view of dense leafy treetops filling the entire frame like a textured sea, broad soft bands of silver-gold where the leaves turn their pale undersides in slow rippling waves, glowing and expansive, the brightest band right of center",
      "the wind circling back through the canopy in restless eddies, leaves spiralling in lit swirls, the ripples crossing and folding, a brooding shade in the deeper green",
      "the canopy easing, the waves of leaves slowing to a gentle drift, the silver fading to soft grey-green",
      "DARK BACKGROUND — the treetops still, one last leaf turning silver in the lower left and settling",
    ],
  },
  "954a7000-91ba-42eb-b5a7-a8d5bc21c8c2": {
    name: "Night Wind 5",
    measured: "68 BPM rubato, C# major-leaning with minor shading (0.41), restless/tender, arousal 0.55; minor undertow then tonic shimmer peak 1:43–2:29",
    old: "'the great wind over the dunes'",
    world: "night dunes trailing soft veils of lit sand",
    why: "Tender restlessness with real minor shading = the dunes keep their wind but it veils rather than storms; the minor undertow is a shadow moving through the troughs at the radiant peak.",
    micro: "fine grains of sand lifting off a sharp dune edge in a thin glowing veil",
    abstract: "smooth ripple patterns of sand and soft luminous veils of drifting grains",
    phases: [
      "DARK BACKGROUND — a dark dune crest at night seen from above, a thin veil of fine sand barely lifting off its sharp edge, a faint warm glow along the ridge",
      "the dunes stirring under a warm night wind, fine sand pouring off the ridges in soft luminous veils, ripples running across the slopes",
      "sand drifting in slow dreamy eddies between the dunes, curling veils of lit grains hanging in the air, a bittersweet calm",
      "an ocean of dune crests from above, every ridge trailing a long glowing veil of sand in the same direction, warm gold and silver shimmering across the whole frame, a deeper shadow moving through the troughs, radiant, the longest veil crossing the diagonal",
      "the veils thinning and falling back onto the slopes in slow golden slants, the ripples settling",
      "DARK BACKGROUND — the dunes still in deep night, one faint thread of sand drifting off a single crest in the lower right",
    ],
  },
  "1f5e3884-5317-4146-ba18-4742eaf74ce9": {
    name: "Chemiluminescence",
    measured: "60 BPM rubato, G# major (0.14), glowing/introspective/suspended, arousal 0.45; three quiet sections, subdominant bloom peak 1:49–2:16",
    old: "'the whole shore ignites', waves breaking in brilliant light",
    world: "quiet living light in still tide pools and a calm bay",
    why: "Slow, introspective and suspended = light that glows from within still water, not breaking waves; the single subdominant bloom = the whole calm bay softly alight.",
    micro: "a cluster of tiny living sparks of green-gold light suspended in clear dark water",
    abstract: "soft clouds of glowing light diffusing slowly through dark water",
    phases: [
      "DARK BACKGROUND — a still rock pool at night, one tiny point of cold green-gold light glimmering beneath the surface in the lower left",
      "looking straight down into still dark shallows filling the frame, faint living glows gathering small green-gold clouds of light drifting under the dark surface, inward and calm",
      "looking straight down into a calm dark lagoon filling the frame, scattered soft pools of green-gold glow suspended in the clear water, wide dark between them",
      "looking straight down into the shallows, a slow current moving through them, the glows stretching into faint trailing ribbons, a deeper blue shade gathering beneath",
      "looking straight down onto a quiet bay so the water fills the entire frame, the whole bay blooming with soft living light, vast slow clouds of green-gold and pale teal glow spreading through the still water, each ripple edged in light, the brightest bloom right of center, radiant and calm",
      "DARK BACKGROUND — the bay dark again, a few last faint glows fading slowly beneath the still surface",
    ],
  },
  "a96b4696-c02b-4004-a1a5-a0b1eee09308": {
    name: "Loire 2",
    measured: "85 BPM free time but slow feel, C major (0.14), tender/wistful/reflective, arousal 0.38; rising to a shimmering peak 0:46–1:09, minor-shadowed return",
    old: "'a bright young river racing over braided sandbars'",
    world: "a slow wide river gliding past willows in mist",
    why: "Slow, tender, reflective = a gliding river, not a racing one; the shimmering current peak = the whole bend lit; the minor-shadowed return = a soft shadow passing over still water.",
    micro: "willow leaves trailing in a slow current, a thin line of light along each leaf",
    abstract: "long slow reflections of warm light stretched on moving water",
    phases: [
      "DARK BACKGROUND — a slow wide river at night, mist on the water, long willow branches trailing into the current in the lower left, one faint pewter seam of light on the surface",
      "a slow wide river between dark willows and tall poplars, its open water smooth and empty, soft grey light on the surface, mist lifting in thin veils",
      "looking down onto the slow current filling the frame, willow leaves trailing in it holding small glints, long amber reflections stretching across the water",
      "seen from above looking down onto a wide river bend so the water fills the frame, the slow current shimmering gold and silver in reflected light, mist lit from within between the trailing willows, the brightest water set left of center, luminous and full",
      "looking down onto the river filling the frame, a soft shadow passing over it, the gold fading to muted rose and slate, the water still and reflective, nostalgic",
      "looking down onto the river at rest between dark willow banks, a quiet mirror, one last warm reflection on the current",
    ],
  },
  "8f3e82e2-0a30-499f-ba74-5158208a07a0": {
    name: "Never Forget 4",
    measured: "94 BPM free time, slow feel, E minor, minor-dominant (0.74), wistful/reverent/elegiac, valence −0.15; radiant plateau 1:23–1:59",
    old: "'an immense shining expanse' of sky-holding tide pools",
    world: "a low-tide beach at dusk where each pool keeps a small light",
    why: "Minor and elegiac = dusk, not shining day; memory as small held lights; the radiant (grateful) plateau = every pool glowing warm at once, then receding one by one.",
    micro: "a small tide pool holding a faint glow, its rim of wet sand shining",
    abstract: "scattered small lights held in dark rippled sand",
    phases: [
      "a low-tide beach at dusk seen from above, dark wet sand with scattered tide pools holding faint violet light, aching and quiet",
      "a cloud shadow drifting over the flats, the pools dimming to slate, thin ribbons of water threading between them",
      "the tide pools across the whole beach glowing warm rose-gold at once seen from above, each pool a small held light in the dark sand, the brightest cluster right of center, grateful and full",
      "the glow receding into the pools one by one, the sand darkening, the remaining lights soft and inward",
      "a few distant pools still holding the last violet light, long dark sand between them, poignant",
      "DARK BACKGROUND — the beach in deep dusk, one small pool still holding a faint glow in the lower left",
    ],
  },
  "05664df7-d355-40b7-85d2-e2badf26123a": {
    name: "Torraine 6",
    measured: "68 BPM rubato, A minor, minor-dominant (0.73), wistful/introspective, valence −0.25; a deep valley 1:29–1:59, Aeolian summit 2:24–2:48",
    old: "a sky of stars 'of every colour' over the river",
    world: "muted dusk stars and their long trembling reflections on a dark river",
    why: "Minor and introspective = muted, few stars instead of a festival of colour; the measured valley closes the sky; the heavy Aeolian summit = the sky filled with dim stars joined by faint threads.",
    micro: "a muted reflection of light trembling as a long streak on dark rippled water, seen close",
    abstract: "faint threads of light joining dim reflected points across dark rippled water",
    phases: [
      "DARK BACKGROUND — looking straight down at a dark river surface filling the frame, one faint muted reflection of light trembling as a long streak on the water",
      "looking straight down at the broad dark river filling the frame, a few dim reflections of distant light trembling as long streaks on its surface, colours muted to dusty rose and slate",
      "looking straight down at wide dark water, the reflections fading under drifting low mist, almost empty",
      "looking straight down at the dark current, muted reflections returning one by one, pulled into long trembling streaks by the steady flow",
      "looking straight down at the dark river filling the frame, its surface holding the reflections of countless muted points of light joined by faint threads, all trembling in the current, heavy and bittersweet, the densest reflections left of center",
      "looking straight down at the still dark river, a single muted reflection lingering on its surface",
    ],
  },
  "79cad85a-13fa-4db9-b4cd-a507b62a6084": {
    name: "Nothing 30",
    measured: "96 BPM free time, slow feel, D major (0.13), reflective/warm/tender/settled, valence 0.35; full-hearted peak 2:07–2:34",
    old: "a cold silver void, fog vortex around open dark",
    world: "a warm luminous emptiness — honey-grey haze and one amber mote",
    why: "The emptiness stays (the name), but the music is warm, tender major — so the void is warm umber and honey, not cold silver; the full-hearted peak opens the haze around a calm center.",
    micro: "fine grains of warm amber dust drifting through soft dark haze, seen close",
    abstract: "slow horizontal veils of warm haze at many depths in darkness",
    phases: [
      "DARK BACKGROUND — an immense empty dark with the faintest horizontal veils of warm grey haze at different depths, a fine drift of warm dust grains crossing the lower right",
      "the veils of warm haze drifting slowly past one another, their edges catching a soft honey light, fine warm dust drifting between them",
      "the haze deepening into wide umber shadows between the veils, fine dust drifting slowly through them, searching",
      "a vast warm haze filling the entire frame in every direction, layered veils of honey and rose glowing softly from within above and below, the light diffused evenly through all of them, fine warm dust drifting through every layer like held breaths, a softer darker hollow right of middle, full-hearted",
      "the veils swaying gently back into long quiet strata, the warm light dimming to soft grey-gold",
      "DARK BACKGROUND — near-total warm dark, a faint drift of warm dust settling low in the frame",
    ],
  },
  "6499ac06-2cb1-4970-b75f-1258587c84d8": {
    name: "The Other Side 10",
    measured: "84 BPM free time, slow feel, B♭ minor, minor-dominant (0.82), brooding/introspective, valence −0.35; rising to Lydian-shadow swell 1:11–1:34, grave unresolved close",
    old: "the far side 'pouring violet and aqua radiance' through a bright membrane",
    world: "the black mirror threshold — dark water lit faintly from beneath",
    why: "Strongly minor and brooding = the threshold stays dark and shadowed; the peak glows deep violet through dark water instead of pouring radiance; the grave, still-loud ending keeps the light steady but heavy.",
    micro: "slow ripple rings on black water bending a faint violet light",
    abstract: "dark translucent water lit faintly from beneath, slow interference ripples",
    phases: [
      "DARK BACKGROUND — a perfectly still black water surface seen at a low grazing angle, a faint inverted violet glow deep within its mirror, one slow ripple ring in the lower right",
      "the mirror stirring, a dim violet light rising slowly from beneath the surface, ripple rings crossing and bending it, the space above still dark",
      "the surface thinning to dark translucent water, faint shapes of light drifting beneath it, aching and restless",
      "a standing wall of dark water lit from behind by a deep violet and muted teal glow, light bending through its ripples in slow aching swells, droplets suspended in the air, the glow strongest off-center left, luminous but shadowed",
      "the standing water holding still and heavy, the violet light steady and grave behind it, slow ripples crossing",
      "the black mirror restored, the violet glow deep and steady within it, unresolved",
    ],
  },
  "86b64938-26ea-40b9-9ea1-461323a049d5": {
    name: "Chenin 3",
    measured: "98 BPM rubato, B♭ major (0.10), warm/rooted/grateful/serene, arousal 0.48; peak early (0:24–0:51), a hushed clearing 1:51–2:16",
    old: "rows of vines 'blazing gold' in a harvest blaze",
    world: "a vineyard in warm honey haze, translucent fruit holding the light",
    why: "Warm and grateful but serene, not ecstatic — the gold glows through fruit instead of blazing; the peak sits early where the music's home-ground hymn is; the measured hushed clearing becomes the sparse dark passage.",
    micro: "a translucent golden grape with warm light glowing through it",
    abstract: "soft honey light filtering through layered vine leaves",
    phases: [
      "a single translucent golden grape cluster among dark vine leaves in low warm light, its skin dusted with bloom",
      "looking down into the vines, clusters of translucent grapes and broad leaves filling the frame, warm honey light glowing through the fruit, warm and generous, the brightest clusters right of center",
      "the warm light deepening to amber across the vines, pollen and motes drifting slowly through the haze, yearning",
      "DARK BACKGROUND — the vineyard in deep dusk, one cluster faintly glowing in wide darkness",
      "warm light returning along the vines, grapes and leaves edged in gold, the haze glowing softly",
      "the vines at rest in fading amber, a few clusters holding the last warm glow",
    ],
  },

  // ═══════════════ Featured built-ins ═══════════════
  "the-ascent": {
    name: "The Summit",
    measured: "65 BPM free time, D minor (was mislabelled; minor-weight 0.74), wistful/suspended/nocturnal/unresolved; pedal-point surge peak 1:34–1:55",
    old: "floating boulder fields, bright green moss, balanced rock in pale haze",
    world: "a night summit ridge above a moving sea of cloud",
    why: "Minor, nocturnal and suspended = the summit at night, not a sunny fantasy of floating moss; the pedal-point surge = cloud pouring over the saddle; the Lydian crest = a warmer seam of light on the cloud; the descending bass with 'rising light' = the cloud sinking as the sky softens.",
    micro: "dark rock at the crest of a ridge, fine mist flowing over its edge lit silver",
    abstract: "slow luminous rivers of cloud flowing over dark ridgelines",
    phases: [
      "DARK BACKGROUND — looking down along a high bare ridge of dark rock at night, mist pooled on both sides, one thin seam of cold silver light along the crest in the lower right",
      "slow rivers of cloud flowing through a dark mountain saddle at night, their tops lit faint silver, the ridges rising above them, yearning and calm",
      "a long ridge of bare black rock at night seen from high above, an immense sea of moving cloud pouring over its saddle in a slow luminous cascade, cold silver and dusky violet light along every cloud edge, the brightest flow right of center, brooding and resolute",
      "looking down at the cloud cascade pouring over the dark ridge, a warmer pale gold seam along its crest, light and shadow trading across the rock, poignant and suspended",
      "looking straight down at the cloud sinking slowly back into the valleys between dark ridges, its surface softening to blue-grey, bittersweet and open",
      "DARK BACKGROUND — the ridge alone in deep night, one faint silver seam fading along the crest",
    ],
  },
  "cosmic-drift": {
    name: "Cosmic Drift",
    measured: "65 BPM free time, G major (0.10), nostalgic/tender/at peace; a 'subdominant pause' valley 1:11–1:38, suspended-longing peak 3:31–3:59",
    old: "an asteroid field and a SUPERNOVA explosion at the peak",
    world: "a slow drift of small asteroids through a river of warm golden dust",
    why: "Tender and at peace = no explosions; the drift and the rocks stay (the identity), warmed to gold; the measured pause is a nearly empty frame; the peak is the densest, glowing dust river — yearning, not violent.",
    micro: "the rough broken face of a jagged rock shard lit warm amber, fine dust lifting off it, seen close",
    abstract: "slow flowing currents of glowing golden dust in deep space",
    phases: [
      "DARK BACKGROUND — a loose scatter of small jagged irregular rock shards drifting slowly through deep space in the lower left, their broken edges catching a faint warm amber light",
      "a gentle field of jagged irregular rock shards of many sizes drifting in slow procession, warm golden dust trailing between them, glowing softly, content",
      "DARK BACKGROUND — wide empty dark space with a faint drift of warm golden dust across it, still",
      "jagged rock shards drifting through a vast cloud of warm golden dust, their broken faces lit amber and rose, fine particles glowing around them, uplifted",
      "an immense slow river of glowing golden dust flowing diagonally through deep space, countless small jagged rock shards carried within it lit warm gold, the densest glow left of center, yearning and tender",
      "DARK BACKGROUND — the last thin thread of golden dust and a few tiny jagged shards drifting away into deep dark, at peace",
    ],
  },
  "the-ascension": {
    name: "The Ascension",
    measured: "70 BPM free time, F major (0.06), nostalgic/tender; E-major window 0:24–1:00, chromatic summit 1:39–2:03 (unsettled)",
    old: "the vault of gold geometry sat on a calm 'return home' passage",
    world: "same golden ascent — beats re-ordered to the measured arc",
    why: "World fits (warm, luminous, nostalgic). The monumental vault now lands on the chromatic summit; the calm cloud-sea takes the reassuring 'return home'.",
    phases: [0, 1, 3, 2, 4, 5],
  },
  "mycelium-dream": {
    name: "Mycelium Dream",
    measured: "69 BPM free time, C major (0.17), devotional/grounded/patient; RISING — summit in C at 5:20–5:45 (old peak sat at 3:07)",
    old: "the cosmic bioluminescent network played at 3:07, long before the music's peak",
    world: "same forest/mycelium world — beats re-ordered so the network blooms at the real summit",
    why: "World fits (grounded, patient, organic); the arc did not — the luminous network now arrives with the late summit.",
    phases: [0, 1, 3, 4, 2, 5],
  },
  "the-bloom": { name: "The Bloom", kind: "arc", measured: "95 BPM, G major (0.06), warm/grounded; rising — summit on G 2:13–2:49", old: "template arc", world: "unchanged", why: "World fits; arc now from the measured dynamics (peak moves later)." },

  // ═══════════════ Welcome Home album ═══════════════
  "5a3e5044-9da5-404e-b3d6-c0c4fc757a5b": {
    name: "Playa",
    measured: "59 BPM steady, E minor with strong major light (0.52), bittersweet/tidal/wistful/spacious, arousal 0.38",
    old: "'colossal luminous dust storms walling the horizon'",
    world: "the playa — dust storm replaced by a mirror-thin sheet of water over the cracked clay",
    why: "Tidal, wistful and spacious at low arousal = no wall of storm; the clay flats keep their identity, the peak becomes a thin flood mirroring rose and violet light.",
    micro: "cracked clay polygons with a thin film of water catching rose light",
    abstract: "mirror-thin water spreading across patterned clay in soft rose and violet",
    phases: [0, 1, "seen from high above looking down, a vast thin sheet of water spreading slowly across the cracked clay flats, the polygon pattern glowing through it, reflecting soft rose and violet light, tidal and spacious", 3, 4, 5],
  },
  "08f4c26e-4185-440a-a25c-2440e8e7ae47": {
    name: "Isolation",
    measured: "70 BPM rubato, G minor (stored as F minor before the key fix; minor-weight 0.80), solitary/brooding/haunted, valence −0.5; 'hollow return' 2:15–2:36",
    old: "a gold doorway of light opening in the fog during the drained, numb return",
    world: "the lone pine island in fog — the hopeful doorway removed",
    why: "The measured 'hollow return' is drained and numb, not a door of hope; the fog closes back in, cold and grey.",
    micro: "fog beads on dark pine needles, cold and grey",
    abstract: "dense cold fog drifting in slow layers over dark water",
    phases: [0, 1, 2, "the fog closing in around the small island again, the light dimmed to a cold pale grey, the single pine still and small in the vast grey, drained and quiet", 4, 5],
  },
  "8997623d-8770-41ce-863d-f359d1a213c4": {
    name: "Rebound",
    measured: "86 BPM steady, D major (0.12), buoyant/resilient; full-bloom peak 2:05–2:30 (old peak 1:35–2:04 on a wistful relative-minor passage)",
    old: "the monumental ringing canyon sat on the wistful relative-minor shadow",
    world: "same water-impulse world — beats re-ordered",
    why: "World fits; the monumental canyon now lands on the measured full bloom, the calmer standing waves on the wistful shadow.",
    phases: [0, 1, 4, 3, 2, 5],
  },
  "5a3beb75-4788-4448-a024-4bfae30040c3": {
    name: "The Knife (Jam)",
    measured: "67 BPM free time, C# major (0.20), searching/restless; hushed 'subdominant shadows' 3:46–4:19, altered-ascent peak 5:04–5:30",
    old: "the cosmic shard storm sat on the hushed, murky subdominant passage",
    world: "same obsidian/molten world — beats re-ordered",
    why: "The kaleidoscopic storm now lands on the altered ascent; the quiet aerial plain takes the hushed shadow.",
    phases: [0, 1, 3, 2, 4, 5],
  },
  "38daff92-ae34-4448-8868-5f1df6029b94": {
    name: "Rolling",
    measured: "58 BPM rubato, G major (0.03), warm/serene/cyclical; Lydian summit 3:07–3:38",
    old: "the planetary ocean of hills sat on a 'settling breath'",
    world: "same rolling-hills world — beats re-ordered",
    why: "The largest hill-swell now lands on the Lydian summit; the drifting cloud shadows take the settling breath.",
    phases: [0, 1, 2, 4, 3, 5],
  },
  "b4ea4c60-d158-40ca-8bd5-4d2d57473e4f": {
    name: "Cosmic Homecoming",
    measured: "Welcome Home audio: 76 BPM, F major (0.11), tender homecoming; inward minor turn 1:25–1:58, summit 2:37–3:59",
    old: "'full cosmic maximalism' played on the inward minor turn",
    world: "same cosmic culmination — beats re-ordered",
    why: "The warm amber glow takes the hopeful glow, the violet mist takes the wistful minor turn, and the maximal cosmos lands on the measured summit.",
    phases: [0, 3, 1, 2, 4, 5],
  },

  // ═══════════════ Surrounded by Light album ═══════════════
  "b583c8d2-b3c3-4df8-9c51-9b035be2d3e1": {
    name: "Rise",
    measured: "96 BPM, B♭ major (0.14), hopeful/aspiring; serene pedal return 0:35–0:55, summit climb 0:55–1:18",
    old: "a cloud ocean 'torn open by the risen sun' (sun disc risk) on the serene passage",
    world: "same ascent-of-light world — peak beat rewritten without a sun, re-ordered",
    why: "The intimate updraft takes the serene pedal return; the cloud tear (now lit from within, no sun) lands on the summit climb.",
    micro: "a slow updraft of pale luminous air rising through a shaft of high light, thin gold particles orbiting",
    abstract: "immense waves of gold light breaking over dark cloud ridges",
    phases: [0, 1, 3, "an ocean of dark cloud torn open from within seen from high above, immense waves of gold light flooding up through the tear and breaking over the cloud ridges, aspiring and triumphant", 4, 5],
  },
  "db22c975-8f03-487b-ae44-437f7f153ac1": {
    name: "Surrender",
    measured: "65 BPM rubato, B♭ major (0.04), tender/yielding/consoling, arousal 0.32; fullest bridge 1:41–2:02",
    old: "opened on 'violent' whitewater 'mid-explosion' (old description said chaotic, 120 BPM)",
    world: "same water world — the violent opening replaced, beats re-ordered",
    why: "Tender, yielding and slow = surrender begins as one falling drop on still water, not an explosion; the cathedral light shafts land on the fullest bridge.",
    micro: "a single droplet rejoining a still surface, rings of pale teal light expanding",
    abstract: "slow ripple rings of warm light on dark still water",
    phases: ["DARK BACKGROUND — looking straight down at still dark water filling the frame, one slow ripple ring spreading from a single falling drop in the lower left, a faint warm reflection barely touching it, calm and expectant", 1, 4, 2, 3, 5],
  },
  "8b163c8b-cda5-4d7d-995b-41dd68fdd059": {
    name: "Drift",
    measured: "82 BPM rubato, F major (0.04), serene/rocking/tender; full bloom 2:31–3:09",
    old: "dunes 'under storm-lit clouds'; a macro still-life on the peak",
    world: "same drift world (sand, water, fog) — no storm, beats re-ordered",
    why: "Serene rocking = no storm light; the boundless sliding bands land on the full bloom, the single still ripple closes the piece.",
    micro: "sand grains streaming across a dune crest in soft warm light",
    abstract: "slow bands of luminous sand and haze sliding across the frame",
    phases: [
      "DARK BACKGROUND — looking straight down at a dune crest in razor focus, fine sand grains streaming sideways across it as lit particles in laminar flow",
      "an ocean of dunes seen from directly above filling the entire frame, ridgelines migrating slowly with warm reflected light along their crests, grain-rivers braiding gently between shadowed troughs",
      "looking straight down at thin sheets of silver water gliding across dark tidal sand filling the frame, wet ripples emerging and vanishing",
      "looking straight down at layered pale fog veils sliding slowly over black water filling the frame, drift at weather scale",
      "a top-down view of alternating bands of luminous sand-veil and soft indigo haze interleaved across the entire frame, everything sliding slowly in one direction, warm and full",
      "DARK BACKGROUND — looking straight down at a single ripple pattern in wet sand, its crests holding faint light, one grain rolling to rest",
    ],
  },
  "dd2ed3c9-67e9-4450-a9ca-c1426087fa9a": {
    name: "Message",
    measured: "85 BPM steady, C major (0.27), searching/tender/wistful/unresolved, arousal 0.42",
    old: "'cosmic storm' — teal fire and branching lightning",
    world: "same lagoon-of-light-rings world — the lightning storm replaced",
    why: "Tender, searching and unresolved = calls and answers as crossing rings of light, never a lightning storm.",
    micro: "a single ring of teal light spreading on black water",
    abstract: "overlapping luminous rings crossing on dark water",
    phases: [0, 1, "looking straight down onto a calm dark lagoon filling the frame, alive with slow overlapping rings of teal and soft gold light, every call answered, the rings crossing in quiet blooms to the edges of the frame, aching and luminous", 3, 4, 5],
  },
  "4ca8d765-71a2-401a-85eb-eb02c2780bc3": {
    name: "Grace",
    measured: "126 BPM flowing, D major (0.08), consoling/hymn-like; FALLING shape — the first blessing is the peak (0:00–1:09), shadowed turn 1:09–1:48",
    old: "opened on a single sparse meteor thread while the music opens at full voice",
    world: "same falling-light world — beats re-ordered",
    why: "Grace arrives first and fullest: the sky of descending embers opens the piece; the lone meteor thread takes the shadowed turn.",
    phases: [2, 1, 0, 3, 4, 5],
  },
  "01a395f7-04d6-4ff9-aecf-f8dacdcae0b1": {
    name: "Complete",
    measured: "61 BPM free time, D major (0.20), wistful/tender/searching, valence 0.2; full voice 0:23–0:41",
    old: "an ancient stone circle and standing-stone mandala (stone cliché)",
    world: "rings of warm light on dark water — a circle completing",
    why: "Wistful, tender completion; the circle motif stays but leaves stone behind: an almost-closed ring of light, then rings widening across a lake at the full-voiced peak.",
    micro: "a single thin ring of warm light on dark still water",
    abstract: "concentric rings of soft light crossing on dark water",
    phases: [
      "DARK BACKGROUND — looking straight down onto a dark still pond, a thin ring of soft amber light floating on the water surface almost closing, one small gap remaining in the lower left",
      "rings of warm light expanding across a wide dark lake seen from above, overlapping circles glowing amber and pale gold to the edges of the frame, ardent and full, the brightest ring right of center",
      1, 3, 4, 5,
    ],
  },
  "f7b01537-af1b-4ade-b788-f21c6565b057": {
    name: "Surrounded By Light (March Light)",
    measured: "93 BPM, E♭ major (0.14), radiant/tender; the summit is 2:36–3:02 (old peak sat on a 0.54 passage)",
    old: "the monumental corona sat on a quiet passage",
    world: "same forest-corona world — beats re-ordered",
    why: "The full crown of converging light now lands on the measured summit.",
    phases: [0, 1, 3, 2, 4, 5],
  },
  "fdc6470e-5c7e-43b4-968c-3e907f1fa88f": {
    name: "Grasshopper",
    measured: "93 BPM free time, slow feel, E minor (0.76), wistful/searching/contemplative, arousal 0.38",
    old: "a 'kinetic chorus' of dew-arcs launching like a fountain field",
    world: "same dew-meadow world — the kinetic chorus slowed",
    why: "Minor, contemplative and slow = drops slipping and falling in slow arcs, not launching.",
    micro: "a dew drop trembling at a grass blade tip",
    abstract: "slow arcs of falling droplets through green darkness",
    phases: [0, 1, "dozens of dew drops slipping from bending grass stems in slow arcs through shafts of soft green-gold light, the meadow trembling gently, wistful and searching", 3, 4, 5],
  },
};

// World fits its analysis; only the measured arc is applied.
for (const [id, name] of [
  ["27f52cf0-5fad-420f-8324-8017c414f1f8", "Interplay"], ["a5b5f0cf-9a6b-451a-8293-3d98f3904342", "Bath"],
  ["79e33115-7f1e-44bc-b950-7adf5055dd55", "Welcome Home"], ["00fcca2b-bc1e-461a-8dcd-3fff74587f3e", "The Knife"],
  ["eb79818b-c7e8-45a7-886c-2a432fe83332", "2019"], ["cd517f5a-c4eb-4d50-8a53-044aa668d087", "Stir Crazy"],
  ["019e1e1d-c7e2-4609-a9c6-364a2755b115", "Quarantine"], ["b207b557-e984-4a06-ae71-83124bcd80d5", "All Together"],
  ["f24cc5d9-66cd-4fae-a03a-14dda1698566", "Openings"], ["69ac68d7-30c9-4c1e-bb0e-1727fb5643f3", "Surrounded By Light"],
  ["89ff944d-f242-4f77-9b95-7cb1d3dc0af6", "Self"], ["549719aa-4a15-4981-8a9a-34ee66fca156", "Held"],
  ["a5de2004-f606-4277-a4cb-032c35e56c43", "Sway"], ["c110af67-40be-4a06-9878-eeec2a22bb3d", "Mystic"],
  ["5a07f0af-654f-4dab-b42c-aef83983b33f", "The First"], ["f0362f24-75f1-4717-8487-cc9cf12c7bcc", "The First (Expanded)"],
  ["9d901645-b8dd-4a62-b3e2-2613ccd64335", "Dad's Song II"], ["c80a89bc-2c88-4bde-bec8-4be6916acb62", "Yellow Bird"],
  ["800ed3f9-08d4-4b73-8a32-86ed8370e752", "Spectre"], ["a985d483-a948-4e3b-bad3-841a68f9992f", "Mexican Boy"],
  ["fb56b19e-ee23-43c6-ad41-5714e7969aad", "Afterglow"], ["46216435-4340-4ad4-9033-101e66fb29e7", "Love Again"],
]) RETHEME[id] = { name, kind: "arc", world: "unchanged", why: "World fits the v2 analysis; the template arc (0.4/0.7/1/0.75/0.5/0.3) is replaced by the measured dynamics.", phases: SAME };

// Arc-applied journeys whose existing beats also needed re-ordering so the
// largest image lands on the measured peak (world itself unchanged).
Object.assign(RETHEME["a5de2004-f606-4277-a4cb-032c35e56c43"], { kind: "re-order", world: "same kelp/bioluminescent sway — beats re-ordered", why: "The cosmic double-world now lands on the measured crest (0:55–1:11); the spirit-hint ribbon takes the earlier rocking cycle.", phases: [0, 1, 4, 3, 2, 5] });
Object.assign(RETHEME["f0362f24-75f1-4717-8487-cc9cf12c7bcc"], { kind: "re-order", world: "same waking-forest world — beats re-ordered", why: "The forest-waking monument lands on the measured homecoming glow; the quiet open-fifth farewell (last 20%) holds the resting valley instead of a bright aerial.", phases: [0, 1, 3, 2, 5, 5] });
Object.assign(RETHEME["800ed3f9-08d4-4b73-8a32-86ed8370e752"], { kind: "re-order", world: "same marsh-wisp world — beats re-ordered", why: "The standing curtains of pale light now land on the measured peak (1:54–2:15); the aerial marsh takes the plateau.", phases: [0, 1, 4, 3, 2, 5] });
Object.assign(RETHEME["46216435-4340-4ad4-9033-101e66fb29e7"], { kind: "re-order", world: "same burned-forest regrowth — beats re-ordered", why: "Love Again peaks EARLY (0:25–1:00, falling shape): the monumental bloom moves to the peak, the fern-shoot macro follows.", phases: [0, 2, 1, 3, 4, 5] });
