// Design-notes prose for the in-app modal. Kept as a plain string so the page
// and the README.md tell one story.

export const README_TEXT = `Hall of Songs asks one question: what if you could WALK INSIDE your own catalog — and where you stand IS the mix?

Karel's recordings become architecture. Eight of his real piano pieces stand as luminous violet monoliths ringed around one dark hall, and — this is the whole point — every one of them plays AT ONCE. You enter in first person: WASD walks and the mouse looks around on desktop (click the hall to capture the mouse, Esc to release); on a phone, twin on-screen joysticks walk and look. There is no track list to choose from. You just move, and the catalog re-mixes itself around your head.

The spatialization is real, not faked. Each track's looping recording is fed through its own Web Audio HRTF PannerNode fixed at its pillar's position in the room, and the AudioContext's single AudioListener is glued to the camera every frame — its position and its forward/up orientation follow exactly where you stand and which way you face. Distance is handled by the panner's inverse distance model (a small reference distance and a firm rolloff), so proximity is dramatic: step up to a pillar and its song blooms loud and close, turn your head and it swings across your ears, walk away and it decays toward a whisper — but because the model never reaches zero, distant songs stay as a faint far-off presence rather than cutting out. Standing between two pillars, you hear both, balanced by exactly how near each one is. Moving through the hall is continuous, physical, 3D re-mixing of his entire catalog.

Each body glows to its OWN contribution. Every track carries a private AnalyserNode tapped straight off its source, so a pillar's emissive brightness, its additive halo and a gentle height-pulse track that recording's own amplitude — combined with how near you stand — and the nearest, loudest song floats its title in the air above it. The palette is deliberate: cool violet, indigo and ice on near-black, an architectural floor grid receding into fog, slow drifting dust for depth. No warm amber, no cosmic tunnel — a quiet, Scandinavian room you happen to be standing inside.

Everything is routed through the shared ear-safety master bus before the speakers; nothing touches the audio destination directly. The subset is loaded sequentially so decode memory stays capped, each track fading in as it arrives, and each buffer loops forever so there is no re-fetch. All motion and timing come from performance.now and the AudioContext clock; any incidental placement uses a seeded mulberry32 PRNG, never Math.random or Date. The hall renders and slowly self-drifts from the moment it mounts so it is alive before you press a thing; Enter the hall starts the sound and hands you the controls.

NAMED REFERENCE. This sits in the lineage of the spatial SOUND-WALK: Janet Cardiff & George Bures Miller's audio walks, where recorded sound is bound to physical places you move through, and Bernhard Leitner's sound architecture, which treats sound as a material you inhabit and walk among rather than face. It is also a direct expression of the 2026 turn toward OBJECT-BASED immersive spatial audio — sound authored as discrete objects positioned in a scene and rendered to the listener's own position and head orientation, exactly what per-track HRTF panners plus a camera-locked listener do here. The difference from a gallery installation is that the objects are Karel's own songs, and the room is his catalog.

HONEST LIMITATIONS. HRTF panning is rendered with a generic head model, so front/back and elevation cues are weaker than left/right and are far more convincing on headphones than on speakers. Eight simultaneous decoded, looping buffers is the practical ceiling for a smooth laptop frame rate, so this walks a curated slice of the catalog, not all sixteen tracks at once. If a track fails to load it is skipped and the rest of the hall plays on; if WebGL is unavailable the piece shows a clear notice rather than crashing.

PLAY. Enter the hall, put on headphones, and walk. Let a song get loud, then leave it for another. Where you stand is the mix.`;
