// ════════════════════════════════════════════════════════════════════════════
// 1870 — Metastaseis :: geometry + deterministic seed
//
// Reconstructs Philips-Pavilion-style hyperbolic-paraboloid "shells" as ruled
// surfaces. A hypar is generated by two families of straight ruling lines: fix
// one bilinear parameter, sweep the other, and you trace a straight segment
// between two skew edges. Xenakis drew those same straight lines in Metastaseis
// as string glissandi; here we invert the move — each ruling line IS a
// glissando (its two endpoints' heights become the glide's pitch endpoints).
//
// No Math.random / Date — everything flows from mulberry32(SEED).
// ════════════════════════════════════════════════════════════════════════════

/** Deterministic PRNG. Fixed 32-bit seed → identical run on every load. */
export function mulberry32(seed: number): () => number {
  let a = seed >>> 0;
  return () => {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

export const SEED = 0x1870;

export interface Vec3 {
  x: number;
  y: number;
  z: number;
}

/** One straight ruling line of the u-family (v swept 0→1 at fixed u). */
export interface RulingLine {
  /** bilinear u parameter, 0→1 across the shell — the playhead axis. */
  u: number;
  a: Vec3; // endpoint at v = 0
  b: Vec3; // endpoint at v = 1
  freqA: number; // pitch at endpoint a (height-mapped, scale-quantized)
  freqB: number; // pitch at endpoint b — glide target
  span: number; // |b.y - a.y| normalized; large span → steep → energy cluster
}

export interface Shell {
  corners: [Vec3, Vec3, Vec3, Vec3]; // P00, P10, P01, P11
  uLines: RulingLine[];
  vLines: { a: Vec3; b: Vec3 }[]; // second ruling family — visual net only
  register: number; // base pitch register for this shell (Hz)
  maxHeight: number;
}

function lerp(a: number, b: number, t: number): number {
  return a + (b - a) * t;
}

function lerpVec(a: Vec3, b: Vec3, t: number): Vec3 {
  return { x: lerp(a.x, b.x, t), y: lerp(a.y, b.y, t), z: lerp(a.z, b.z, t) };
}

/** Bilinear (ruled) surface point of the skew quad P00,P10,P01,P11. */
function surfacePoint(c: [Vec3, Vec3, Vec3, Vec3], u: number, v: number): Vec3 {
  const bottom = lerpVec(c[0], c[1], u); // P(u,0)
  const top = lerpVec(c[2], c[3], u); // P(u,1)
  return lerpVec(bottom, top, v);
}

// Pentatonic-minor step pattern (semitones) — keeps every glissando musical.
const SCALE = [0, 3, 5, 7, 10];

/** Quantize a normalized height (0→1) to a scale pitch above `base` Hz. */
function heightToFreq(base: number, norm: number, octaves: number): number {
  const clamped = Math.max(0, Math.min(1, norm));
  const totalSteps = octaves * SCALE.length;
  const idx = Math.round(clamped * (totalSteps - 1));
  const octave = Math.floor(idx / SCALE.length);
  const semitone = SCALE[idx % SCALE.length] + 12 * octave;
  return base * Math.pow(2, semitone / 12);
}

/**
 * Build the shell architecture. `morph` (0→1.5) scales how far each corner
 * warps from the mean height — 0 is a near-flat plane, high is a deep saddle.
 */
export function buildShells(morph: number): Shell[] {
  const rand = mulberry32(SEED);
  const shells: Shell[] = [];
  const registers = [130.81, 174.61, 261.63]; // C3, F3, C4 anchors
  const shellCount = 3;

  const spanX = 9; // total horizontal spread across all shells
  const w = 5.2; // per-shell width
  const d = 4.4; // per-shell depth

  for (let i = 0; i < shellCount; i++) {
    const cx = (i - (shellCount - 1) / 2) * (spanX / shellCount) * 1.15;
    const h = 3.4 + rand() * 1.6;

    // Saddle: two opposite corners high, two low → true hyperbolic paraboloid.
    const lowH = (0.15 + rand() * 0.35) * h;
    const highH = (0.85 + rand() * 0.5) * h;
    const meanH = (lowH + highH) / 2;
    const warp = (base: number): number => meanH + morph * (base - meanH);

    // Alternate which diagonal rises so adjacent shells lean opposite ways.
    const flip = i % 2 === 0;
    const hA = flip ? lowH : highH;
    const hB = flip ? highH : lowH;

    const tilt = (rand() - 0.5) * 1.2;
    const corners: [Vec3, Vec3, Vec3, Vec3] = [
      { x: cx - w / 2, y: warp(lowH), z: -d / 2 }, // P00 low
      { x: cx + w / 2, y: warp(hA), z: -d / 2 + tilt }, // P10
      { x: cx - w / 2, y: warp(hB), z: d / 2 - tilt }, // P01
      { x: cx + w / 2, y: warp(highH), z: d / 2 }, // P11 high
    ];

    const maxHeight = Math.max(...corners.map((c) => c.y), 0.001);
    const octaves = 2 + (i % 2); // 2–3 octave glissando reach per shell

    // u-family: the sounded ruling lines (playhead sweeps u).
    const nU = 22;
    const uLines: RulingLine[] = [];
    for (let k = 0; k < nU; k++) {
      const u = k / (nU - 1);
      const a = surfacePoint(corners, u, 0);
      const b = surfacePoint(corners, u, 1);
      const normA = a.y / maxHeight;
      const normB = b.y / maxHeight;
      uLines.push({
        u,
        a,
        b,
        freqA: heightToFreq(registers[i], normA, octaves),
        freqB: heightToFreq(registers[i], normB, octaves),
        span: Math.abs(b.y - a.y) / maxHeight,
      });
    }

    // v-family: the crossing ruling lines that make the warp read as a shell.
    const nV = 14;
    const vLines: { a: Vec3; b: Vec3 }[] = [];
    for (let k = 0; k < nV; k++) {
      const v = k / (nV - 1);
      vLines.push({
        a: surfacePoint(corners, 0, v),
        b: surfacePoint(corners, 1, v),
      });
    }

    shells.push({ corners, uLines, vLines, register: registers[i], maxHeight });
  }

  return shells;
}

/**
 * Seeded, deterministic camera flight — a smooth loop that orbits the row of
 * shells and periodically dips toward and through them. `t` is seconds.
 */
export function cameraPath(t: number): { pos: Vec3; target: Vec3 } {
  const r = 11 + 2.6 * Math.sin(t * 0.11);
  const az = t * 0.09;
  const dip = Math.sin(t * 0.07);
  const pos: Vec3 = {
    x: Math.sin(az) * r,
    y: 3.4 + 2.2 * dip,
    z: Math.cos(az) * r * 0.72,
  };
  const target: Vec3 = {
    x: 2.4 * Math.sin(t * 0.05),
    y: 2.0 + 0.6 * Math.cos(t * 0.045),
    z: 0.6 * Math.cos(t * 0.06),
  };
  return { pos, target };
}
